Adding cost_estimator implementation considering parallelization
flexflow/flexflow-train pull request #1365
Opened 2024-04-12 20:07 UTC by Marsella8

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-04-17 09:12 UTC, lockshaw reviewed
Looks great! Stylistically it matches the existing code, which is much appreciated :slightly_smiling_face: 

Obviously tests need to get finished off and there are probably some minor edge cases to be handled, but as an initial draft this looks really good

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-:-NvfJT708ZefLpI5X24v:bsl4u7r)* status: all files reviewed, 8 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/src/machine_mapping.cc` line 123 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHPI7COkhD10dLtsJ:-NvfHPI7COkhD10dLtsK:b-sde1n5) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L123)):*
> ```cpp
>   std::unordered_set<UpwardOpenMultiDiEdge> incoming_edges =
>       get_incoming_edges(g, node);
>   std::vector<ParallelTensorShape> inputs = transform(
> ```

If the ordering here doesn't matter why is this a `vector`?
___
*[`lib/compiler/src/machine_mapping.cc` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHX2_AzaQvTc9OJOW:-NvfHX2_AzaQvTc9OJOX:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L124)):*
> ```cpp
>       get_incoming_edges(g, node);
>   std::vector<ParallelTensorShape> inputs = transform(
>       as_vector(incoming_edges), [&](UpwardOpenMultiDiEdge const &input_edge) {
> ```





_Suggestion:_
```cpp
  as_vector(get_incoming_edges(g, node)), [&](UpwardOpenMultiDiEdge const &input_edge) {
```
___
*[`lib/compiler/src/machine_mapping.cc` line 161 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHtw99l5ZCnuGj8xI:-NvfHtw99l5ZCnuGj8xJ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L161)):*
> ```cpp
> 
>   // Filling the frontier
>   for (auto &[edge, _] : frontier_machine_views) {
> ```





_Suggestion:_
```cpp
  for (auto const &[edge, _] : frontier_machine_views) {
```
___
*[`lib/compiler/src/machine_mapping.cc` line 161 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfJL7r9OeYPqgRXA7o:-NvfJL7r9OeYPqgRXA7p:byte1bn) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L161)):*
> ```cpp
> 
>   // Filling the frontier
>   for (auto &[edge, _] : frontier_machine_views) {
> ```

Maybe cleaner to just get the set of nodes with no incoming closed edges?
___
*[`lib/compiler/src/machine_mapping.cc` line 176 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHCmt7O370GFbhnAb:-NvfHCmt7O370GFbhnAc:bplhmwc) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L176)):*
> ```cpp
>       if (std::all_of(devices.begin(), devices.end(), [&occupied](int d) {
>             return occupied[d] == false
>           })) {
> ```

See `all_of` in `containers.h`



_Code quote:_
```cpp
      if (std::all_of(devices.begin(), devices.end(), [&occupied](int d) {
            return occupied[d] == false
          })) {
```
___
*[`lib/compiler/test/src/test_parallel_cost_estimator.cpp` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfIoO10IUThXfAbacY:-NvfIoO10IUThXfAbacZ:b6paz8s) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/test/src/test_parallel_cost_estimator.cpp#L10)):*
> ```cpp
>   TEST_CASE("parallel_estimate_cost") {
>     // Test graph structure
>     //     /-- 1 --\
> ```

Add a test case that starts with the simpler case of a straight line? Might be an easier starting point and I think should have a clean analytical answer you can check against
___
*[`lib/compiler/test/src/test_parallel_cost_estimator.cpp` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfIl6jAAMmlPrZQ9ZL:-NvfIl6jAAMmlPrZQ9ZM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/test/src/test_parallel_cost_estimator.cpp#L11)):*
> ```cpp
>     // Test graph structure
>     //     /-- 1 --\
>         //  0 -         - 3
> ```





_Suggestion:_
```cpp
  //  0 -         - 3
```
___
*[`lib/utils/src/graph/algorithms.cc` line 380 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfGuRI1uVPo0XhTXNk:-NvfGuRI1uVPo0XhTXNl:bz4r2v5) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/utils/src/graph/algorithms.cc#L380)):*
> ```cpp
> 
> std::unordered_map<Node, std::unordered_set<Node>>
>     get_successors(DiGraphView const &g,
> ```

Alternatively, implement this as `get_predecessors` on the flipped graph


<!-- Sent from Reviewable.io -->

2024-05-09 00:57 UTC, wmdi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @lockshaw and @Marsella8)



<!-- Sent from Reviewable.io -->

2024-06-03 09:45 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/machine_mapping.cc` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHX2_AzaQvTc9OJOW:-NzSK0R44tJZ5B8-E5ZL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L124)):*
> ```cpp
>       get_incoming_edges(g, node);
>   std::vector<ParallelTensorShape> inputs = transform(
>       as_vector(incoming_edges), [&](UpwardOpenMultiDiEdge const &input_edge) {
> ```

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 161 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHtw99l5ZCnuGj8xI:-NzSK-n85PVsyvBryVuU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L161)):*
> ```cpp
> 
>   // Filling the frontier
>   for (auto &[edge, _] : frontier_machine_views) {
> ```

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 161 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfJL7r9OeYPqgRXA7o:-NzSKFOb3BDt2RfVRh_0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L161)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe cleaner to just get the set of nodes with no incoming closed edges?
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 176 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHCmt7O370GFbhnAb:-NzSJce66GQhcgpRXTsv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L176)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See `all_of` in `containers.h`
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_parallel_cost_estimator.cpp` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfIoO10IUThXfAbacY:-NzSKH3N4zhOIyxdjXvK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/test/src/test_parallel_cost_estimator.cpp#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add a test case that starts with the simpler case of a straight line? Might be an easier starting point and I think should have a clean analytical answer you can check against
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_parallel_cost_estimator.cpp` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfIl6jAAMmlPrZQ9ZL:-NzSKGm4ET1ve_TOHpjT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/test/src/test_parallel_cost_estimator.cpp#L11)):*
> ```cpp
>     // Test graph structure
>     //     /-- 1 --\
>         //  0 -         - 3
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-12 18:10 UTC, wmdi reviewed
> Reviewed 2 of 4 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: all files reviewed, 8 unresolved discussions (waiting on @lockshaw and @Marsella8)



<!-- Sent from Reviewable.io -->

2024-07-01 23:00 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: 4 of 13 files reviewed, 8 unresolved discussions (waiting on @lockshaw, @Marsella8, and @wmdi)

___
*[`lib/compiler/src/machine_mapping.cc` line 123 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfHPI7COkhD10dLtsJ:-O0kWawbAzO8ENlWMoI8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/compiler/src/machine_mapping.cc#L123)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If the ordering here doesn't matter why is this a `vector`?
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/algorithms.cc` line 380 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfGuRI1uVPo0XhTXNk:-O0kWcRV06urg2kIguJL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/utils/src/graph/algorithms.cc#L380)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Alternatively, implement this as `get_predecessors` on the flipped graph
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-06 00:02 UTC, lockshaw requested changes
> Reviewed 2 of 8 files at r4, 5 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/include/compiler/cost_estimator.h` line 12 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14K0zA0H2gTz1-3Nuh:-O14K0zA0H2gTz1-3Nui:b1xj4et) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/include/compiler/cost_estimator.h#L12)):*
> ```objc
> 
> using SubParallelComputationGraphView =
>     OutputLabelledOpenMultiDiGraphView<Operator, ParallelTensor>;
> ```

Prefer dtgen-wrapped type (see current `SubParallelComputationGraph`, which honestly should probably be a `View` anyway so feel free to just change it to be a `View`)
___
*[`lib/compiler/src/cost_estimator.cc` line 29 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KHsgCn9riybSQx3J:-O14KHsgCn9riybSQx3K:b-pm2bvq) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L29)):*
> ```cpp
> }
> 
> struct TimedNode { // Node and associated finishing time
> ```

Prefer `dtgen` over `visitable`
___
*[`lib/compiler/src/cost_estimator.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14JDJ1AxS471D-1DVK:-O14JDJ31drevfchXG2N:bvwusvy) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L68)):*
> ```cpp
>     std::unordered_set<Node> copy(frontier);
>     for (Node const &node : copy) {
>       auto views = device_mapping.machine_views.at(node);
> ```

Prefer actual type over `auto`



_Code quote:_
```cpp
auto
```
___
*[`lib/compiler/src/cost_estimator.cc` line 73 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KRrP67d6kjLBAD2y:-O14KRrP67d6kjLBAD2z:bi9qpbu) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L73)):*
> ```cpp
>               devices.begin(), devices.end(), [&occupied](device_id_t d) {
>                 return occupied[d] == false;
>               })) {
> ```

Prefer functions from `containers.h`



_Code quote:_
```cpp
      if (std::all_of(
              devices.begin(), devices.end(), [&occupied](device_id_t d) {
                return occupied[d] == false;
              })) {
```
___
*[`lib/compiler/src/cost_estimator.cc` line 75 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KWgbBMZAa0c4qIoz:-O14KWgbBMZAa0c4qIp-:b-wsbx7b) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L75)):*
> ```cpp
>               })) {
>         float cost = node_estimate_cost(node, g, estimator, device_mapping);
>         processing.push({node, current_time + cost});
> ```

Pulling some of this out into separate lambdas might improve readability (say, a lambda named `start_node_processing`)
___
*[`lib/pcg/src/device_id.cc` line 19 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14Kn13EoxcaiAcMdXQ:-O14Kn13EoxcaiAcMdXR:bypb70l) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/pcg/src/device_id.cc#L19)):*
> ```cpp
> // Most likely not the best way to do it.
> device_id_t operator+(device_id_t device, size_t increment) {
>   if (std::holds_alternative<gpu_id_t>(device)) {
> ```

Refactor to use `dtgen` (but otherwise this isn't bad, just replace the `static_cast`s with actual field accesses)

Is this an operation we actually want to support for `device_id_t`, or should this just be done in the context of other functions?
___
*[`lib/utils/src/graph/algorithms.cc` line 380 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfGuRI1uVPo0XhTXNk:-O14L7CGAVlrQdC5luWn:b-xv9vsi) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/utils/src/graph/algorithms.cc#L380)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing it done? (though it doesn't necessarily need to be, just saying I don't see a change)


<!-- Sent from Reviewable.io -->

2024-07-15 07:30 UTC, Marsella8 reviewed
> Reviewed 2 of 5 files at r1, 2 of 8 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator.h` line 12 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14K0zA0H2gTz1-3Nuh:-O1pFZfHBMljkmfUp14u:bw8bqwt) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/include/compiler/cost_estimator.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer dtgen-wrapped type (see current `SubParallelComputationGraph`, which honestly should probably be a `View` anyway so feel free to just change it to be a `View`)
</blockquote></details>

Tried to sync my branch so as to `dtgen` and wasn't able to get it working, best if i get this PR merged and then finish this off in a separate branch (e.g. the `machine-related` one)?
___
*[`lib/compiler/src/cost_estimator.cc` line 29 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KHsgCn9riybSQx3J:-O1pFDEk7EOSbOgFkd_1:b-ojrovb) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `dtgen` over `visitable`
</blockquote></details>

See comment above

Also, we will always use `dtgen` going forward for all structs, including the ones that are only for private use / limited to a single module right?
___
*[`lib/compiler/src/cost_estimator.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14JDJ1AxS471D-1DVK:-O1p4VnuAitc6nTvncY5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L68)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer actual type over `auto`
</blockquote></details>

Done.
___
*[`lib/compiler/src/cost_estimator.cc` line 73 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KRrP67d6kjLBAD2y:-O1mO9wv7dcTCw8Z5hzR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L73)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer functions from `containers.h`
</blockquote></details>

Done.
___
*[`lib/compiler/src/cost_estimator.cc` line 75 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KWgbBMZAa0c4qIoz:-O1pAlgQ9BvShgrXuYOj:bkdt4up) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L75)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pulling some of this out into separate lambdas might improve readability (say, a lambda named `start_node_processing`)
</blockquote></details>

Done, let me know if this is ok.

As a general question, when do we use lambdas inside the function vs just having a separate function do the same thing? Only when the function is only applicable tto the function we are trying to write?
___
*[`lib/pcg/src/device_id.cc` line 19 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14Kn13EoxcaiAcMdXQ:-O1pF-t84P3hQbJ_Cq0D:bu64dt7) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/pcg/src/device_id.cc#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Refactor to use `dtgen` (but otherwise this isn't bad, just replace the `static_cast`s with actual field accesses)

Is this an operation we actually want to support for `device_id_t`, or should this just be done in the context of other functions?
</blockquote></details>

Due to problems above with `dtgen`, will clean up everything into the `machine-related` branch.

I don't think we'll ever intend for the user to directly increment `device_id_t` types, but it is useful for the functions that are part of `machine_views.cc` and associated modules (e.g. if we want to iterate over the range of IDs to generate all possible IDs)
___
*[`lib/utils/src/graph/algorithms.cc` line 380 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-NvfGuRI1uVPo0XhTXNk:-O1p5-NZ6sJ1QsDca0Qc:b-eo73zg) ([raw file](https://github.com/flexflow/FlexFlow/blob/9c03409269c4bc1aac9afd29cd90172563ec36ff/lib/utils/src/graph/algorithms.cc#L380)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing it done? (though it doesn't necessarily need to be, just saying I don't see a change)
</blockquote></details>

Now it's changed.


<!-- Sent from Reviewable.io -->

2024-07-17 02:55 UTC, lockshaw requested changes
> Reviewed 3 of 9 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1365)* status: all files reviewed, 15 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/cost_estimator.h` line 12 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14K0zA0H2gTz1-3Nuh:-O1yaNeA26MKLLFQKCb4:b-r7pcee) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/include/compiler/cost_estimator.h#L12)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Tried to sync my branch so as to `dtgen` and wasn't able to get it working, best if i get this PR merged and then finish this off in a separate branch (e.g. the `machine-related` one)?
</blockquote></details>

You're going to need to merge with `repo-refactor` anyway, so if you can't get `dtgen` to work I'm guessing the branch won't be mergeable. That said, if you want I'm already making the change to this specific struct in a different PR, so you can skip this one (though it would still be good to update the other structs such as `TimedNode` in this PR) 
___
*[`lib/compiler/src/cost_estimator.cc` line 29 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KHsgCn9riybSQx3J:-O1yaj2w78FboyeUHLsL:b-ar73jt) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L29)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

See comment above

Also, we will always use `dtgen` going forward for all structs, including the ones that are only for private use / limited to a single module right?
</blockquote></details>

I'd say use it when you can--it only captures a limited subset of what C++ structs can do (e.g., no methods, etc.), but it also removes a lot of difficulty of making your structs support expected behaviors (printability, equality, hashing, etc.) yourself, so if you struct fits in its semantic model I'd say use it
___
*[`lib/compiler/src/cost_estimator.cc` line 75 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O14KWgbBMZAa0c4qIoz:-O1yXvw4D2kbUglkAi9R:b-arcrik) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e6285f705b3ddc59139fb271c13acf2ffb5263/lib/compiler/src/cost_estimator.cc#L75)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done, let me know if this is ok.

As a general question, when do we use lambdas inside the function vs just having a separate function do the same thing? Only when the function is only applicable tto the function we are trying to write?
</blockquote></details>

We use lambdas for functions that aren't reusable across the codebase. They're especially useful when you want to manipulate local variables, like `occupied` here, as the lambdas can manipulate them directly. When in doubt I'd say start with lambdas
___
*[`lib/compiler/src/cost_estimator.cc` line 41 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1yZzUD5aP7jhI6MJb0:-O1yZzUD5aP7jhI6MJb1:b-2qokst) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L41)):*
> ```cpp
> };
> 
> bool predecessors_have_been_processed(
> ```

This should be a lambda
___
*[`lib/compiler/src/cost_estimator.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1y_6nr4ajDTT8DUDfW:-O1y_6nr4ajDTT8DUDfX:b-x30n5o) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L44)):*
> ```cpp
>     std::unordered_set<Node> const &predecessors,
>     std::unordered_set<TimedNode> processed) {
>   std::unordered_set<Node> simple_processed =
> ```

`processed_nodes`?



_Code quote:_
```cpp
 simple_processed
```
___
*[`lib/compiler/src/cost_estimator.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1y_A5i8hBm2X0n-RxM:-O1y_A5i8hBm2X0n-RxN:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L47)):*
> ```cpp
>       transform(processed, [](TimedNode const &tn) { return tn.node; });
> 
>   return all_of(predecessors, [&simple_processed](Node p) {
> ```





_Suggestion:_
```cpp
  return all_of(predecessors, [&](Node p) {
```
___
*[`lib/compiler/src/cost_estimator.cc` line 48 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1y_0h77ud9DR5XSzlg:-O1y_0h77ud9DR5XSzlh:b2khb5e) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L48)):*
> ```cpp
> 
>   return all_of(predecessors, [&simple_processed](Node p) {
>     return simple_processed.find(p) != simple_processed.end();
> ```

`contains` from `utils/containers.h`
___
*[`lib/compiler/src/cost_estimator.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1y_H_P82YS8F9pdYO-:-O1y_H_P82YS8F9pdYO0:b-qbzpng) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L55)):*
> ```cpp
>                                      MachineMapping const &device_mapping) {
>   return device_mapping.machine_views.at(node).device_ids();
> }
> ```

Should be moved to the corresponding header for `MachineMapping`



_Code quote:_
```cpp
std::vector<device_id_t> get_devices(Node const &node,
                                     MachineMapping const &device_mapping) {
  return device_mapping.machine_views.at(node).device_ids();
}
```
___
*[`lib/compiler/src/cost_estimator.cc` line 106 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1yZ1Id1gYE1Mnwti3T:-O1yZ1Id1gYE1Mnwti3U:b-fygg12) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L106)):*
> ```cpp
>       std::vector<device_id_t> devices = get_devices(node, device_mapping);
>       if (all_of(devices,
>                  [&occupied](device_id_t d) { return occupied[d] == false; })) {
> ```

Don't worry about explicitly managing lambda references unless there's a good reason (e.g., they're going to live outside of local scope)



_Suggestion:_
```cpp
                 [&](device_id_t d) { return occupied[d] == false; })) {
```
___
*[`lib/compiler/src/cost_estimator.cc` line 117 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1yZdalEt5wuxjERZLB:-O1yZdalEt5wuxjERZLC:bll2193) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L117)):*
> ```cpp
>       finish_node_processing(finished);
> 
>       // Adding candidates to the frontier
> ```

FYI these comments aren't really adding a huge amount here and can probably be removed. With the lambdas added the code is readable enough that I don't think they're contributing much over the code itself
___
*[`lib/compiler/src/cost_estimator.cc` line 121 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1y_VP55mJBxZDOeXY-:-O1y_VP55mJBxZDOeXY0:b-drbk7r) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/src/cost_estimator.cc#L121)):*
> ```cpp
>         std::unordered_set<Node> predecessors = get_predecessors(g, successor);
> 
>         if (predecessors_have_been_processed(predecessors, processed)) {
> ```

Why not just have `predecessors_have_been_processed` call `get_predecessors` directly?



_Code quote:_
```cpp
predecessors_have_been_processed(predecessors, processed)
```
___
*[`lib/compiler/test/CMakeLists.txt` line 13 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1365#-O1yYRRk6T_Ag5i4gzAf:-O1yYRRk6T_Ag5i4gzAg:b-8fzbeb) ([raw file](https://github.com/flexflow/FlexFlow/blob/44ed29e5b739c1420a69c5060a992566cbee7f86/lib/compiler/test/CMakeLists.txt#L13)):*
> ```CMake
>     doctest
>     utils-test-c [...]

2025-01-10 23:06 UTC, lockshaw commented
Closing in favor of #1565.

2025-01-10 23:06 UTC, closed without merging