Sp-ization Algorithm
flexflow/flexflow-train pull request #1423
Opened 2024-06-25 22:30 UTC by Marsella8

**Description of changes:**

Added basic sp-ization algorithm and associated tests

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-06-26 03:58 UTC, lockshaw requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: all files reviewed, 10 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/include/utils/graph/simple_sp_ization.h` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HS_Cd0ZgxXMJjhHN5:-O0HS_Cd0ZgxXMJjhHN6:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/include/utils/graph/simple_sp_ization.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> DiGraph simple_sp_ization(DiGraph g);
> ```





_Suggestion:_
```objc
DiGraph simple_sp_ization(DiGraphView const &g);
```
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HTu7k13ZHiDw7cTgF:-O0HTu7k13ZHiDw7cTgG:b-marz2d) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L12)):*
> ```cpp
> namespace FlexFlow {
> 
> DiGraph simple_sp_ization(DiGraph g) {
> ```

Maybe instead just output the serial-parallel decomposition of the resulting graph as produced by the existing serial-parallel algorithm? It seems like what you really want for this is a serial-parallel structure, not actually a graph, and this also solves the problem of what to do with these random barrier nodes that otherwise get inserted.
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSvWEEslUwrjQeBI4:-O0HSvWEEslUwrjQeBI5:b-r3ox1x) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L14)):*
> ```cpp
> DiGraph simple_sp_ization(DiGraph g) {
> 
>   std::unordered_set<Node> sources = get_sources(g);
> ```

Break this into two functions: one that finds the distances of all of the nodes from one the sources, and one that actually inserts the barrier nodes
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 44 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HThRA6WD1BRy-RKWY:-O0HThRA6WD1BRy-RKWZ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L44)):*
> ```cpp
>     if (layers.count(layer + 1)) { // Skip if last layer
>       std::vector<Node> successors = add_nodes(sp, layers.at(layer + 1).size());
>       Node barrier_node = add_nodes(sp, 1)[0];
> ```





_Suggestion:_
```cpp
    Node barrier_node = sp.add_node();
```
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HTXYmCQlp2zELk6yo:-O0HTXYmCQlp2zELk6yp:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L45)):*
> ```cpp
>       std::vector<Node> successors = add_nodes(sp, layers.at(layer + 1).size());
>       Node barrier_node = add_nodes(sp, 1)[0];
>       for (auto const &p : predecessors) {
> ```





_Suggestion:_
```cpp
      for (Node const &p : predecessors) {
```
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 51 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HUBuo27-TcMhXPrpS:-O0HUBuo27-TcMhXPrpT:b-5z9n2h) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L51)):*
> ```cpp
>         sp.add_edge({barrier_node, s});
>       }
>       predecessors = successors;
> ```

Try to not re-assign variables as much as possible, it makes the code much less readable when I have to track all the state changes through the loop. Here you could just have
```
std::vector<Node> predecessors = add_nodes(sp, layers.at(current_layer));
std::vector<Node> successors = add_nodes(sp, layers.at(current_layer + 1));
```
At the top of the loop head, which avoids all this reassignment. Even better, make `layers` a vector and then iterate through pairs of elements (and if a function that produces a vector of pairs of elements is not already in `utils/containers`, add it) (though this may all be obviated by the comment at the top of this function)
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HQjgaB7Lbwa6U_tmB:-O0HQjgd0sgGkxInqWAl:b-bh1r17) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L0)):*
Add this file to the list of tests in the `utils/test/CMakeLists.txt`
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HRQJD6-6JVwMfNr9i:-O0HRQJD6-6JVwMfNr9j:b-uf9aa1) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L13)):*
> ```cpp
>   TEST_CASE("Simple SP-ization: sanity checks") {
>     /*
>     graph TD;
> ```

Ideally prefer graphviz/dot syntax over mermaid (we just use mermaid in readmes because github auto-renders it in those cases). Here, the equivalent graphviz would be
```
digraph {
    n1 -> n2;
    n1 -> n3;
    n2 -> n4;
    n2 -> n5;
    n3 -> n4;
    n3 -> n5;
    n4 -> n6;
    n5 -> n6;
}
```
Also, isn't this graph serial-parallel as long as you treat all-to-all connections as sequential splits (which we do)?
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSLz14PGo1xRCbyhW:-O0HSETT0gee69c9xd0Y:bcyojp9) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L50)):*
> ```cpp
> 
>     std::unordered_set<DirectedEdge> sp_edges = get_edges(sp);
>     CHECK(sp_edges.size() == 3 + 4 + 3); // 3 for first layer, 4 for second, ...
> ```

Add a check that the resulting graph is sp-decomposable?
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 53 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSOXv-VrWROUdLWxM:-O0HSOXv-VrWROUdLWxN:b-dkzeza) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L53)):*
> ```cpp
>   }
> 
>   TEST_CASE("Simple SP-ization: integrity checks") {
> ```

Why two separate test cases here for the same input graph? Probably better to just move the checks into the previous test case?


<!-- Sent from Reviewable.io -->

2024-06-27 21:59 UTC, Marsella8 reviewed
For both get_longest_path_lengths and the simple_sp_ization the tests are failing due to the directed graph flipping the edges issue (I've checked and constructing the graphs in reverse makes the tests pass).

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-:-O0Qgpmw8M4L80ayWL5t:bl45vj4)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HTu7k13ZHiDw7cTgF:-O0QgEzP-QBwlw4qibvT:bauxvok) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe instead just output the serial-parallel decomposition of the resulting graph as produced by the existing serial-parallel algorithm? It seems like what you really want for this is a serial-parallel structure, not actually a graph, and this also solves the problem of what to do with these random barrier nodes that otherwise get inserted.
</blockquote></details>

Yes, sorry for that. Currently returns a SerialParallelDecomposition (which is a Serial Node that contains a vector of Parallel Nodes, each representing a layer).
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSvWEEslUwrjQeBI4:-O0QgEWHBz0EX74sVxI1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Break this into two functions: one that finds the distances of all of the nodes from one the sources, and one that actually inserts the barrier nodes
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 44 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HThRA6WD1BRy-RKWY:-O0QgCUjCKpl4DSeNrNK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L44)):*
> ```cpp
>     if (layers.count(layer + 1)) { // Skip if last layer
>       std::vector<Node> successors = add_nodes(sp, layers.at(layer + 1).size());
>       Node barrier_node = add_nodes(sp, 1)[0];
> ```

Done.
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HTXYmCQlp2zELk6yo:-O0QgDhtAwkWWHTCNk0k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L45)):*
> ```cpp
>       std::vector<Node> successors = add_nodes(sp, layers.at(layer + 1).size());
>       Node barrier_node = add_nodes(sp, 1)[0];
>       for (auto const &p : predecessors) {
> ```

Done.
___
*[`lib/utils/src/graph/simple_sp_ization.cc` line 51 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HUBuo27-TcMhXPrpS:-O0QgSAq59yNZblpdeuC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/src/graph/simple_sp_ization.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Try to not re-assign variables as much as possible, it makes the code much less readable when I have to track all the state changes through the loop. Here you could just have
```
std::vector<Node> predecessors = add_nodes(sp, layers.at(current_layer));
std::vector<Node> successors = add_nodes(sp, layers.at(current_layer + 1));
```
At the top of the loop head, which avoids all this reassignment. Even better, make `layers` a vector and then iterate through pairs of elements (and if a function that produces a vector of pairs of elements is not already in `utils/containers`, add it) (though this may all be obviated by the comment at the top of this function)
</blockquote></details>

Done.
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HRQJD6-6JVwMfNr9i:-O0QgUgu5l2lap76-1Zj:b-4kn5e8) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally prefer graphviz/dot syntax over mermaid (we just use mermaid in readmes because github auto-renders it in those cases). Here, the equivalent graphviz would be
```
digraph {
    n1 -> n2;
    n1 -> n3;
    n2 -> n4;
    n2 -> n5;
    n3 -> n4;
    n3 -> n5;
    n4 -> n6;
    n5 -> n6;
}
```
Also, isn't this graph serial-parallel as long as you treat all-to-all connections as sequential splits (which we do)?
</blockquote></details>

Changed the graph to non-sp
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSLz14PGo1xRCbyhW:-O0Qgl8W57ugpWpkBDjh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add a check that the resulting graph is sp-decomposable?
</blockquote></details>

Done.
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line 53 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HSOXv-VrWROUdLWxM:-O0QglbvE1VpwLE759Ba:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L53)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why two separate test cases here for the same input graph? Probably better to just move the checks into the previous test case?
</blockquote></details>

Done.
___
*[`lib/utils/test/src/test_simple_sp_ization.cc` line  at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HQjgaB7Lbwa6U_tmB:-O0QgTe240mgmOXpQtbb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/test/src/test_simple_sp_ization.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add this file to the list of tests in the `utils/test/CMakeLists.txt`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-27 22:07 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/simple_sp_ization.h` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0HS_Cd0ZgxXMJjhHN5:-O0QjDnG6kpPZES4jR-e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f0ca00ac5f1bc508f92feb653b220ae11ebb4059/lib/utils/include/utils/graph/simple_sp_ization.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> DiGraph simple_sp_ization(DiGraph g);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 19:31 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: 0 of 10 files reviewed, 11 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/test/src/test_sp_ization.cc` line 91 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O0jldt7Eu2VrDPOrXME:-O0jldt891MpfuRttjiU:b-ozgw5v) ([raw file](https://github.com/flexflow/FlexFlow/blob/dbfda833127db463e2591c407269e28661779b24/lib/utils/test/src/test_sp_ization.cc#L91)):*
> ```cpp
>     Serial sp2 = {{n[0], n[2]}};
>     Serial sp3 = {{Parallel{{sp2, sp1}}, n[3]}};
>     Serial expected = {{Parallel{{sp3, sp2}}, n[4]}};
> ```

Currently the order in which you put the nodes matter within Serial and Parallel, since their children attirbute is a vector. Wouldn't it make more sense to have an unordered_set? 


<!-- Sent from Reviewable.io -->

2024-07-10 00:52 UTC, lockshaw requested changes
> Reviewed 3 of 8 files at r3, 2 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: all files reviewed, 25 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/include/utils/graph/algorithms.h` line 320 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6QwDCiCiXTLYEsFZ:-O1P6QwDCiCiXTLYEsF_:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/include/utils/graph/algorithms.h#L320)):*
> ```objc
>                                       DiGraphView const &);
> 
> std::unordered_map<Node, int> get_longest_path_lengths(DiGraphView const &g);
> ```





_Suggestion:_
```objc
std::unordered_map<Node, int> get_longest_path_lengths_from_source_node(DiGraphView const &g);
```
___
*[`lib/utils/src/graph/algorithms.cc` line 674 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6YkJDtP9xmAx_Xg_:-O1P6YkJDtP9xmAx_Xga:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/algorithms.cc#L674)):*
> ```cpp
>           std::max(longest_path_lengths[n], longest_path_lengths[pred] + 1);
>     }
>   }
> ```





_Suggestion:_
```cpp
  for (Node const &n : topo_order) {
    std::unordered_set<int> predecessor_path_lengths = transform(get_predecessors(g, n), [&](Node const &pred) { return longest_path_lengths.at(pred); });
    longest_path_links[n] = maximum(predecessor_path_lengths) + 1;
  }
```
___
*[`lib/utils/src/graph/serialparallel.cc` line 291 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P064e13aPnWRuRJiP:-O1P064e13aPnWRuRJiQ:b-s62zt2) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/serialparallel.cc#L291)):*
> ```cpp
>     std::vector<SerialParallelDecomposition> const &sp_compositions) {
>   if (sp_compositions.size() == 1) {
>     return sp_compositions[0];
> ```

Prefer bounds checking



_Suggestion:_
```cpp
    return sp_compositions.at(0);
```
___
*[`lib/utils/src/graph/serialparallel.cc` line 315 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0PwB0Jy4FjDpLtoJ:-O1P0PwB0Jy4FjDpLtoK:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/serialparallel.cc#L315)):*
> ```cpp
>     std::vector<SerialParallelDecomposition> const &sp_compositions) {
>   if (sp_compositions.size() == 1) {
>     return sp_compositions[0];
> ```





_Suggestion:_
```cpp
    return sp_compositions.at(0);
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0Xir-nqGlGy3eRLQ:-O1P0Xir-nqGlGy3eRLR:b-rurzuc) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L15)):*
> ```cpp
> bool is_sp_compliant(DiGraphView const &g) {
>   return (is_acyclic(g) && has_single_source(g) && has_single_sink(g));
> }
> ```

Could we get a better name for this? Serial-parallel graphs in general can have multiple sources and sinks, so "sp_compliant" doesn't feel like quite the right description



_Code quote:_
```cpp
bool is_sp_compliant(DiGraphView const &g) {
  return (is_acyclic(g) && has_single_source(g) && has_single_sink(g));
}
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3fvJC8JY-e_Jnbn-:-O1P3fvKBdS3Jt5evbSE:b4i2mqp) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L20)):*
> ```cpp
>     barrier_sync_sp_ization_unchecked(DiGraphView const &g) {
> 
>   std::unordered_map<Node, int> layer_map = get_longest_path_lengths(g);
> ```

`layer_map` is really unclear. Something like `node_to_sp_layer`? (if that's what this is)



_Code quote:_
```cpp
  std::unordered_map<Node, int> layer_map 
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 21 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6EtV815sCUe6aZoP:-O1P6EtV815sCUe6aZoQ:b-loikjf) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L21)):*
> ```cpp
> 
>   std::unordered_map<Node, int> layer_map = get_longest_path_lengths(g);
>   std::map<int, std::unordered_set<Node>> layers;
> ```

Why is this not just a `vector`?
___
*[`lib/utils/src/graph/sp_ization.cc` line 24 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P5r-kDrbbt8jkgpav:-O1P5r-kDrbbt8jkgpaw:bjsl2x1) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L24)):*
> ```cpp
>   for (Node const &node : get_nodes(g)) {
>     int layer_num = layer_map[node];
>     layers[layer_num].insert(node);
> ```

Replace this with an `invert_map` function defined in, e.g., `utils/containers/invert_map.h`, as this is a rather generic function but having it all inline here makes things seem more complicated than they are 
___
*[`lib/utils/src/graph/sp_ization.cc` line 33 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3vv56QZO8MVtSsZn:-O1P3vv56QZO8MVtSsZo:bom05n3) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L33)):*
> ```cpp
>     for (Node const &node : nodes) {
>       layer.children.push_back({node});
>     }
> ```

When possible, use functions from `utils/containers.h`, as they're clearer to read than random for loops



_Suggestion:_
```cpp
    Parallel layer = Parallel(transform(nodes, [](Node const &n) { return Serial{n}; }));
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 44 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3MXB2tQbfz1wy80-:-O1P3MXB2tQbfz1wy800:bbgijp2) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L44)):*
> ```cpp
> }
> 
> // Original Recursive implementation, the current one is bottom up
> ```

Delete if unused?
___
*[`lib/utils/src/graph/sp_ization.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P4EDwBMiTroljrpIx:-O1P4EDwBMiTroljrpIy:brghr77) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L68)):*
> ```cpp
> SerialParallelDecomposition
>     naive_dependency_invariant_sp_ization_unchecked(DiGraphView const &g) {
>   std::vector<Node> topo_sorted_nodes = get_topological_ordering(g);
> ```

Avoid unnecessary declarations
___
*[`lib/utils/src/graph/sp_ization.cc` line 74 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3RkmCgIBOfhUlL-V:-O1P3RkmCgIBOfhUlL-W:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L74)):*
> ```cpp
>   node_to_sp[source] = source; // base-case
> 
>   for (Node const &node : topo_sorted_nodes) {
> ```





_Suggestion:_
```cpp
  for (Node const &node : get_topological_ordering(g)) {
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 81 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P4Luk90dS91I6Z_hj:-O1P4Luk90dS91I6Z_hk:b-og28ke) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L81)):*
> ```cpp
>     for (Node const &p : get_predecessors(g, node)) {
>       sp_predecessors.push_back(node_to_sp[p]);
>     }
> ```

Use `transform` from `utils/containers.h`



_Code quote:_
```cpp
    std::vector<SerialParallelDecomposition> sp_predecessors; // change to set
    for (Node const &p : get_predecessors(g, node)) {
      sp_predecessors.push_back(node_to_sp[p]);
    }
```
___
*[`lib/utils/src/graph/sp_ization.cc` line 86 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P [...]

2024-07-16 00:17 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: 4 of 11 files reviewed, 25 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/algorithms.h` line 320 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6QwDCiCiXTLYEsFZ:-O1cWZQj2K04Qm3eNUVZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/include/utils/graph/algorithms.h#L320)):*
> ```objc
>                                       DiGraphView const &);
> 
> std::unordered_map<Node, int> get_longest_path_lengths(DiGraphView const &g);
> ```

Done.
___
*[`lib/utils/src/graph/algorithms.cc` line 674 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6YkJDtP9xmAx_Xg_:-O1cYsre1-KVFjfKC8yx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/algorithms.cc#L674)):*
> ```cpp
>           std::max(longest_path_lengths[n], longest_path_lengths[pred] + 1);
>     }
>   }
> ```

Done.
___
*[`lib/utils/src/graph/serialparallel.cc` line 291 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P064e13aPnWRuRJiP:-O1cZ6AJ2mKyBUS6DmQW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/serialparallel.cc#L291)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer bounds checking
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/serialparallel.cc` line 315 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0PwB0Jy4FjDpLtoJ:-O1cZ5loE13cVc2ossCb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/serialparallel.cc#L315)):*
> ```cpp
>     std::vector<SerialParallelDecomposition> const &sp_compositions) {
>   if (sp_compositions.size() == 1) {
>     return sp_compositions[0];
> ```

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0Xir-nqGlGy3eRLQ:-O1caKSdC2N1pcCE6l5R:b-p6xn9i) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Could we get a better name for this? Serial-parallel graphs in general can have multiple sources and sinks, so "sp_compliant" doesn't feel like quite the right description
</blockquote></details>

changed to `is_2_terminal_sp_compliant`
___
*[`lib/utils/src/graph/sp_ization.cc` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3fvJC8JY-e_Jnbn-:-O1caxdzBK-VPfiND0aL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`layer_map` is really unclear. Something like `node_to_sp_layer`? (if that's what this is)
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 21 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P6EtV815sCUe6aZoP:-O1caz2h76SsKVG77t-u:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this not just a `vector`?
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 24 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P5r-kDrbbt8jkgpav:-O1coZ1W6rt5_hHFEWG4:b-r1b5la) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace this with an `invert_map` function defined in, e.g., `utils/containers/invert_map.h`, as this is a rather generic function but having it all inline here makes things seem more complicated than they are
</blockquote></details>

Added `invert_map`
___
*[`lib/utils/src/graph/sp_ization.cc` line 33 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3vv56QZO8MVtSsZn:-O1cr2k71jGzU-K9Gr5r:b-10uue9) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

When possible, use functions from `utils/containers.h`, as they're clearer to read than random for loops
</blockquote></details>

subbed with `Parallel layer{std::vector<std::variant<Serial, Node\>>{nodes.begin(), nodes.end()}};` (since it doesn't support direct initialization with a container).
___
*[`lib/utils/src/graph/sp_ization.cc` line 44 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3MXB2tQbfz1wy80-:-O1cbIDtAy4oTRaMvTtG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete if unused?
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P4EDwBMiTroljrpIx:-O1ctaEwA06JKfGsxqjg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L68)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Avoid unnecessary declarations
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 74 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P3RkmCgIBOfhUlL-V:-O1ctz1pDd1UfRB4H_0c:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L74)):*
> ```cpp
>   node_to_sp[source] = source; // base-case
> 
>   for (Node const &node : topo_sorted_nodes) {
> ```

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 81 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P4Luk90dS91I6Z_hj:-O1so7KLCK65CnLjEYn4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L81)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `transform` from `utils/containers.h`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 86 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P586VBormhhuH6Kza:-O1cveG29ALMGvD9DKnX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L86)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Too many declarations make the code hard to read
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/sp_ization.cc` line 91 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P4yIr18TFjN5uL-uT:-O1cvWkp1hNQG9mIsp-T:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer bounds-checked versions
</blockquote></details>

Done.
___
*[`lib/utils/test/src/test_algorithms.cc` line 249 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P10dF0i4xv8WJtBFv:-O1cvfJT7fPIaOep99l2:bd4eii0) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/test/src/test_algorithms.cc#L249)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You're a [...]

2024-07-17 02:49 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: 1 of 12 files reviewed, 26 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/serialparallel.cc` line 415 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1ya2uZ2uzIkcX5LUaJ:-O1ya2uZ2uzIkcX5LUaK:b-pus1iy) ([raw file](https://github.com/flexflow/FlexFlow/blob/fe1174a0c49e13560d34cd6f53170ce50bcfa3a2/lib/utils/src/graph/serialparallel.cc#L415)):*
> ```cpp
> std::vector<std::variant<Serial, Node>> filter_empty(Parallel const &parallel) {
>   // return filter(parallel.children, [](auto const &child) {return
>   // !isempty(to_sp_decomp(child));});
> ```

Cannot figure out why the commented out part behaves differently from the function itself.


<!-- Sent from Reviewable.io -->

2024-07-27 05:50 UTC, lockshaw requested changes
Update to include #1449 and then re-request review

> Reviewed 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-:-O2mjG4p1FlwnIKkn6aP:b-3rwptj)* status: 1 of 12 files reviewed, 22 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/src/graph/sp_ization.cc` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0Xir-nqGlGy3eRLQ:-O27R0oJC4D3snvT02jR:bw8edgo) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L15)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

changed to `is_2_terminal_sp_compliant`
</blockquote></details>

How about `is_two_terminal_dag`, since none of these properties actually have to do with SP


<!-- Sent from Reviewable.io -->

2024-08-06 05:24 UTC, Marsella8 reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-:-O3a8NPzEeVuP5arCWK1:bb6un1j)* status: 1 of 54 files reviewed, 22 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/sp_ization.cc` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O1P0Xir-nqGlGy3eRLQ:-O39q1qu4_LEJKcBL4ZY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2361d3c1f9e378c925681f328a409272c1054d0f/lib/utils/src/graph/sp_ization.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How about `is_two_terminal_dag`, since none of these properties actually have to do with SP
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-06 23:41 UTC, lockshaw requested changes
> Reviewed 52 of 53 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: all files reviewed, 58 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/include/utils/containers.h` line 26 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3a8OIH4aSZeokjUxwR:-O3a8OIH4aSZeokjUxwS:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/containers.h#L26)):*
> ```objc
> #include <map>
> #include <numeric>
> #include <set>
> ```

Why?
___
*[`lib/utils/include/utils/containers/as_unordered_set.h` line 9 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aA2lP2w_45GsJ_5w9:-O3aA2lP2w_45GsJ_5wA:b-upkmm3) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/containers/as_unordered_set.h#L9)):*
> ```objc
> 
> template <typename C, typename T = typename C::value_type>
> std::unordered_set<T> as_unordered_set(C const &c) {
> ```

Use `unordered_set_of` (yes the naming is a bit irregular, but let's not try to fix that in this PR)
___
*[`lib/utils/include/utils/containers/invert_map.h` line 19 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aAZEI-ao5VhauXpto:-O3aAZEI-ao5VhauXptp:b11g6ts) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/containers/invert_map.h#L19)):*
> ```objc
>   }
>   return m_inv;
> }
> ```

Unless there's a need for the extra polymorphism it's probably simpler to just have it defined for `unordered_map`



_Suggestion:_
```objc
template <typename K, typename V>
auto invert_map(std::unordered_map<K, V> const &m) {
  std::unordered_map<V, std::unordered_set<K>> result;
  for (auto const &[key, value] : m) {
    result[value].insert(key);
  }
  return result;
}
```
___
*[`lib/utils/include/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.h` line 9 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aBY5ED1F8xr4O79ra:-O3aBY5ED1F8xr4O79rb:b-3hh6r1) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> std::unordered_map<Node, float> get_weighted_longest_path_lengths_from_root(
> ```

Maybe add a quick doxygen comment to explain what these functions do? Up to you, only do it if you can come up with a good prose explanation/docstring
___
*[`lib/utils/include/utils/graph/digraph/algorithms/get_topological_ordering.h` line 11 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aBsJ67hNZpLCnR72n:-O3aBsJ67hNZpLCnR72o:btdme3m) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/digraph/algorithms/get_topological_ordering.h#L11)):*
> ```objc
> 
> std::vector<Node>
>     get_topological_ordering_from_starting_node(DiGraphView const &g,
> ```

Move to its own header file
___
*[`lib/utils/include/utils/graph/serial_parallel/graph_generation.h` line 19 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aBwib6tq4FErYMYTp:-O3aBwib6tq4FErYMYTq:bt9h7j2) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/graph_generation.h#L19)):*
> ```objc
>                                    DataflowGraphView const &g2);
> 
> std::unordered_map<Node, Node> parallel_extend(DiGraph &g,
> ```

Why were these added?
___
*[`lib/utils/include/utils/graph/serial_parallel/parallel_composition.h` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aC6xn1VWf_o_TeuSv:-O3aC6xn1VWf_o_TeuSw:b-yyj9n0) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/parallel_composition.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> SerialParallelDecomposition parallel_composition(
> ```

Probably can just be part of `serial_parallel_decomposition.h` as it feels more like a primitive operation
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_composition.h` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aCqAm6sL-Tm3xJu6M:-O3aCqAm6sL-Tm3xJu6N:bz52osv) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_composition.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> SerialParallelDecomposition serial_composition(
> ```

Probably should just be part of `serial_parallel_decomposition.h` as this feels like a rather primitive operation
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_decomposition.variant.toml` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aCxhO2XqWhxMgvJPE:-O3aCxhO2XqWhxMgvJPF:b-vgx0jj) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_decomposition.variant.toml#L8)):*
> ```TOML
>   "fmt",
> ]
> explicit_constructors = false
> ```

Use `explicit_constructors` unless you have a strong reason--it's a bit more verbose but the code is usually a lot clearer and less bug prone
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_isempty.h` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aD4wkBi3UUi6GYa8-:-O3aD4wkBi3UUi6GYa80:b-xbtb6p) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_isempty.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> bool isempty(SerialParallelDecomposition const &sp);
> ```

Should probably be moved to `serial_parallel_decomposition.h`, this feels like a rather primitive operation



_Suggestion:_
```objc
bool is_empty(SerialParallelDecomposition const &sp);
```
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h` line 11 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aDPYF-wEhRK-pEZYM:-O3aDPYF-wEhRK-pEZYN:b-3j6izq) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h#L11)):*
> ```objc
> 
> std::unordered_map<Node, size_t>
>     node_frequency_counter(SerialParallelDecomposition const &sp);
> ```

Might be more clear if named `get_node_num_occurences_map`, or `get_node_frequency_map`?
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h` line 13 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aDblBEm2SqZmNH0LH:-O3aDblBEm2SqZmNH0LI:b-auo86p) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h#L13)):*
> ```objc
>     node_frequency_counter(SerialParallelDecomposition const &sp);
> 
> size_t num_nodes(SerialParallelDecomposition const &sp);
> ```

Move to `serial_parallel_decomposition.h`
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_normalize.h` line 0 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aFqi76peCaR90GL4G:-O3aFqi76peCaR90GL4H:bhxp5lh) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_normalize.h#L0)):*
Rename to `normalize_sp_decomposition.h`
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_normalize.h` line 13 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aFE7jA7JjSWw_eOQ3:-O3aFE7jA7JjSWw_eOQ4:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/se [...]

2024-08-09 02:07 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1423)* status: 16 of 68 files reviewed, 58 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/containers/invert_map.h` line 19 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aAZEI-ao5VhauXpto:-O3jPMGT9R5uAwW775jC:b-n9tkhd) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/containers/invert_map.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Unless there's a need for the extra polymorphism it's probably simpler to just have it defined for `unordered_map`
</blockquote></details>

changed
___
*[`lib/utils/include/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.h` line 9 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aBY5ED1F8xr4O79ra:-O3jUNcI0SPd4Q7-xJ5a:bb7f2mf) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe add a quick doxygen comment to explain what these functions do? Up to you, only do it if you can come up with a good prose explanation/docstring
</blockquote></details>

done
___
*[`lib/utils/include/utils/graph/serial_parallel/graph_generation.h` line 19 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aBwib6tq4FErYMYTp:-O3jX0YrEq2999IFzax4:bttv1hy) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/graph_generation.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why were these added?
</blockquote></details>

Needed them for building the sample graphs for the benchmarking
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h` line 11 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aDPYF-wEhRK-pEZYM:-O3jm8j5C-yvIHbiO7Mk:b-nqawiz) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be more clear if named `get_node_num_occurences_map`, or `get_node_frequency_map`?
</blockquote></details>

changed to get_node_frequency_map.
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h` line 13 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aDblBEm2SqZmNH0LH:-O3jnws17jUSF8Hh0N8k:bi5si3k) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/serial_parallel_metrics.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `serial_parallel_decomposition.h`
</blockquote></details>

Done. for `get_nodes` is it relevant that duplicate nodes are not considered? I use duplicate nodes fairly extensively within Sp-ization to track which nodes are duplicate of each other
___
*[`lib/utils/include/utils/graph/serial_parallel/serial_parallel_splits.h` line 15 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3a9myVCcNBAul-mcf9:-O3fI5XX2ZKeXUuxmfyZ:br3mbkc) ([raw file](https://github.com/flexflow/FlexFlow/blob/8f9082f1adec483c7b46626e2ecdcdb36eaa54a7/lib/utils/include/utils/graph/serial_parallel/serial_parallel_splits.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not a big fan of default-constructibility, why should this have a default constructor?
</blockquote></details>

Makes it less annoying to deal with `unordered_map`s (see https://stackoverflow.com/questions/695645/why-does-the-c-map-type-argument-require-an-empty-constructor-when-using?noredirect=1&lq=1), prefer the `[]` syntax over things like `emplace` and `find`. Semantically, I'd say for SerialSplit and ParallelSplit it makes sense.
___
*[`lib/utils/include/utils/graph/serial_parallel/sp_ization/critical_path_preserving_sp_ization.h` line 10 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aG8zg-B2NOyy2SKJp:-O3kRnEX71GyTNnF_TpZ:bv4ye2x) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/include/utils/graph/serial_parallel/sp_ization/critical_path_preserving_sp_ization.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

A couple brief doxygen comments would be rather nice here if you can come up with some
</blockquote></details>

I've added probably too much information and not enough at the same time, let me know how deep I should go into explaining it (general principle behind it, just what it outputs, how it differs from the others, do I need to explain what SPization is etc...)
___
*[`lib/utils/src/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.cc` line 53 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3aGdAk9KMNFL3AEqwz:-O3jozbI0T6V_3rxADu1:b-7rl0jd) ([raw file](https://github.com/flexflow/FlexFlow/blob/f77cdbb4d6b5595e99fc42cd19bbdbb6054ed7e6/lib/utils/src/utils/graph/digraph/algorithms/get_longest_path_lengths_from_root.cc#L53)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to just merge the `checked` and `unchecked` versions here, unless you have a strong counterargument
</blockquote></details>

done.
___
*[`lib/utils/src/utils/graph/digraph/algorithms/is_acyclic.cc` line 33 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3dsq-7DBPJ-2m5EpeC:-O3kgnfOCpaikcneyTdE:b2hyclp) ([raw file](https://github.com/flexflow/FlexFlow/blob/06706e9030ea01569d5b0aaaa292d257d4d29c65/lib/utils/src/utils/graph/digraph/algorithms/is_acyclic.cc#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should either be simplified or additional explanation added. Why are there three states? What invariants are expected to hold? Collapsing `dfs_is_acyclic` down to a lambda could also help. Also a better/clearer name for `dfs_is_acylic` would likely help.
</blockquote></details>

cleaned up and added some comments / correction. I can also change the implementation to be simpler but with quadratic runtime (current one is something like O(E+V) )
___
*[`lib/utils/src/utils/graph/serial_parallel/serial_parallel_metrics.cc` line 14 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3e2rSWAEQsRIgQpzds:-O3jKFqxB9_DKRqP8Pze:b-5zeqf6) ([raw file](https://github.com/flexflow/FlexFlow/blob/06706e9030ea01569d5b0aaaa292d257d4d29c65/lib/utils/src/utils/graph/serial_parallel/serial_parallel_metrics.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This function needs simplifying
</blockquote></details>

broken up with overloads
___
*[`lib/utils/src/utils/graph/serial_parallel/serial_parallel_metrics.cc` line 67 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3e2mml8V4jbLUlYf4p:-O3jt1X6Bz9GYfA3RdzK:bq94g3) ([raw file](https://github.com/flexflow/FlexFlow/blob/06706e9030ea01569d5b0aaaa292d257d4d29c65/lib/utils/src/utils/graph/serial_parallel/serial_parallel_metrics.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`overload` and `visit` would probably clean up this code
</blockquote></details>

cleanup by overloading, let me know if you want me to do it with directly with`overload`.
___
*[`lib/utils/src/utils/graph/serial_parallel/serial_parallel_metrics.cc` line 81 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1423#-O3e2fyqDpYX1NjmhKdS:-O3jtVIo7Hxinke4Xixz:bq77iii) ([raw file](https://github.com/ [...]

2024-12-19 17:08 UTC, closed without merging