CPU Kernel Tests
flexflow/flexflow-train pull request #1439
Opened 2024-07-11 21:35 UTC by oOTigger

CPU Kernel Tests for:
- cast_kernels
- reverse_kernels
- combine_kernels
- replicate_kernels

As well as minor changes to kernels/test_utils and addition of local_cpu_allocator

2024-07-19 03:33 UTC, lockshaw requested changes
> Reviewed 1 of 23 files at r1, 21 of 29 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: all files reviewed, 18 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/cast_kernels_cpu.h` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27hIBYETjDn5G8l6sc:-O27hIBYETjDn5G8l6sd:byni4ga) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/include/kernels/cast_kernels_cpu.h#L15)):*
> ```objc
>                     GenericTensorAccessorW const &output,
>                     DataType input_type,
>                     DataType output_type);
> ```

Prefer function names over extra namespaces, the namespaces in `kernels` are more of a legacy holdover than something that should be used more



_Suggestion:_
```objc
void cpu_forward_kernel(GenericTensorAccessorR const &input,
                    GenericTensorAccessorW const &output,
                    DataType input_type,
                    DataType output_type);
```
___
*[`lib/kernels/src/local_cpu_allocator.cc` line 6 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O281cPwAZMcEmvaGcww:-O281cPwAZMcEmvaGcwx:bt78s5s) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cpu_allocator.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> void *LocalCPUAllocator::allocate(size_t requested_memory_size) {
>   void *ptr = calloc(1, requested_memory_size);
> ```

Just use malloc



_Code quote:_
```cpp
calloc(
```
___
*[`lib/kernels/src/local_cpu_allocator.cc` line 28 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O281kYY5U7cN-V0rbjq:-O281kYY5U7cN-V0rbjr:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cpu_allocator.cc#L28)):*
> ```cpp
> 
> LocalCPUAllocator::~LocalCPUAllocator() {
>   for (auto ptr : ptrs) {
> ```





_Suggestion:_
```cpp
  for (void *ptr : this->ptrs) {
```
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-VcWBhmDYk2Q_FGv:-O28-VcWBhmDYk2Q_FGw:b-riys91) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cuda_allocator.cc#L8)):*
> ```cpp
>   void *ptr;
>   checkCUDA(cudaMalloc(&ptr, requested_memory_size));
>   checkCUDA(cudaMemset(ptr, 0, requested_memory_size));
> ```

I don't think code should assume that the allocated memory has been zero'd, unless there's some reason I'm not thinking of?
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27hwl524nsHT8h0Vfs:-O27hwl524nsHT8h0Vft:bcyhoum) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/cpu/reverse_kernels.cc#L14)):*
> ```cpp
>                             coord_t in_blk_size) {
>   coord_t total_elements = num_out_blks * reverse_dim_size * in_blk_size;
>   for (coord_t i = 0; i < total_elements; ++i) {
> ```

This is really hard to read right now, make more readable (maybe pull out some helper functions or something?)
___
*[`lib/kernels/src/cuda/ops/reverse_kernels.cu` line 41 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-neg5PtQ_rT23Gsd:-O28-neg5PtQ_rT23Gse:b5d5k8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/cuda/ops/reverse_kernels.cu#L41)):*
> ```Cuda
> // }
> 
> /* I mentioned this earlier, but I still think the reverse_forward_kernel code
> ```

See my message in slack
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-zzK748aeyalXn80:-O28-zzK748aeyalXn81:bvfzqq) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_batch_norm_kernel.cc#L91)):*
> ```cpp
>       std::vector<float> host_bias_grad_data =
>           load_accessor_data<DataType::FLOAT>(
>               read_only_accessor_from_write_accessor(bias_grad_accessor));
> ```

Why is `read_only_accessor_from_write_accessor` necessary here? Aren't `GenericTensorW`s assumed to be `RW` @reyna-abhyankar ? If so, add an overload to `load_accessor_data`
___
*[`lib/kernels/test/src/test_combine_kernel.cc` line 64 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O2813Ow1SiCfXayl4FJ:-O2813Ow1SiCfXayl4FK:bfek1hu) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_combine_kernel.cc#L64)):*
> ```cpp
>       GenericTensorAccessorR input_accessor_gpu =
>           read_only_accessor_from_write_accessor(
>               create_random_filled_accessor_w(input_shape, gpu_allocator));
> ```

Why not also define a `create_random_filled_accessor_r`?



_Code quote:_
```cpp
create_random_filled_accessor_w
```
___
*[`lib/kernels/test/src/test_utils.h` line 11 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27zEeL1qe55786fAiQ:-O27zEeL1qe55786fAiR:b50hupp) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L11)):*
> ```objc
> #include <random>
> 
> enum class GpuDirection {
> ```

If we're going to have `GenericTensorAccessor`s allocated on different devices it would probably be good to have a field on `GenericTensorAccessor` that tracks that, so it can at least be checked at runtime if you try to access it incorrectly, etc.?

This would also allow you to infer a lot of locations (CPU vs GPU) rather than having to pass additional arguments to the transfer functions
___
*[`lib/kernels/test/src/test_utils.h` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27yK0C7WfaM6kspJQL:-O27yK0C7WfaM6kspJQM:b-5s92v6) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L12)):*
> ```objc
> 
> enum class GpuDirection {
>   HostToDevice = 0,
> ```

Why are concrete values needed?
___
*[`lib/kernels/test/src/test_utils.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27xMO-8SvKBfd4uDSH:-O27xMO-8SvKBfd4uDSI:bg508ld) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L65)):*
> ```objc
> 
> template <typename IDT, typename ODT, typename F>
> GenericTensorAccessorW create_transformed_accessor_w(TensorShape const &shape,
> ```

It seems like this is just being used to create a random tensor, seems like that might be a better behavior?
___
*[`lib/kernels/test/src/test_utils.h` line 86 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27y-EhE6jy8XFo9haU:-O27y-EhE6jy8XFo9haV:bm4tjg) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L86)):*
> ```objc
> }
> 
> template <DataType DT>
> ```

Where possible, probably best to add a dynamically-dispatched function as well as one that takes the argument by template. This isn't possible for some functions (such as those that return a type based on the template type), but for some of these in this function it seems possible.
___
*[`lib/kernels/test/src/test_utils.h` line 88 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27x05-E5bxZG1jr5LG:-O27x05-E5bxZG1jr5LH:b-qy7uf1) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L88)):*
> ```objc
> template <DataType DT>
> GenericTensorAccessorW
>     copy_tensor_between_memories(GenericTensorAccessorR accessor,
> ```

The behavior of this method seems rather confusing, I'd stick to explicitly stating the direction you'd like to transfer (either from Host to Dev [...]

2024-07-31 11:53 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: 2 of 50 files reviewed, 18 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/cast_kernels_cpu.h` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27hIBYETjDn5G8l6sc:-O34mjPeBWV2o59mF3dF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/include/kernels/cast_kernels_cpu.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer function names over extra namespaces, the namespaces in `kernels` are more of a legacy holdover than something that should be used more
</blockquote></details>

Done.
___
*[`lib/kernels/src/local_cpu_allocator.cc` line 6 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O281cPwAZMcEmvaGcww:-O34nqPMBroTx7XaIrcY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cpu_allocator.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just use malloc
</blockquote></details>

Done.
___
*[`lib/kernels/src/local_cpu_allocator.cc` line 28 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O281kYY5U7cN-V0rbjq:-O34nvRt7VlgF7Mh6fMF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cpu_allocator.cc#L28)):*
> ```cpp
> 
> LocalCPUAllocator::~LocalCPUAllocator() {
>   for (auto ptr : ptrs) {
> ```

Done.
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-VcWBhmDYk2Q_FGv:-O34nwMY6Cz9CNwcO0E6:bw8pgew) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/local_cuda_allocator.cc#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think code should assume that the allocated memory has been zero'd, unless there's some reason I'm not thinking of?
</blockquote></details>

Ended up adding an allocate_and_zero function to the Allocator class, not sure if this is too big of a change though? 
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27hwl524nsHT8h0Vfs:-O37ZbRV7OXq2tz68stp:b-bv471v) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/cpu/reverse_kernels.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This is really hard to read right now, make more readable (maybe pull out some helper functions or something?)
</blockquote></details>

Is this "too" broken down? 
___
*[`lib/kernels/src/cuda/ops/reverse_kernels.cu` line 41 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-neg5PtQ_rT23Gsd:-O36Zpr1C4vXr3MeAzsg:b6wnq8b) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/cuda/ops/reverse_kernels.cu#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See my message in slack
</blockquote></details>

Currently talking to Xinhao 
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O28-zzK748aeyalXn80:-O35y5Qe4NhcH1-97dWY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_batch_norm_kernel.cc#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is `read_only_accessor_from_write_accessor` necessary here? Aren't `GenericTensorW`s assumed to be `RW` @reyna-abhyankar ? If so, add an overload to `load_accessor_data`
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_combine_kernel.cc` line 64 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O2813Ow1SiCfXayl4FJ:-O36CV8E6xo6k4BU0jCs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_combine_kernel.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not also define a `create_random_filled_accessor_r`?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.h` line 11 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27zEeL1qe55786fAiQ:-O37Pdf05BdcXj5-5Ekw:b-npbzxg) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If we're going to have `GenericTensorAccessor`s allocated on different devices it would probably be good to have a field on `GenericTensorAccessor` that tracks that, so it can at least be checked at runtime if you try to access it incorrectly, etc.?

This would also allow you to infer a lot of locations (CPU vs GPU) rather than having to pass additional arguments to the transfer functions
</blockquote></details>

Ideally, this is using the same enum class as in allocation.h, but for some reason, whenever I define that class in accessor.h and try and include it as part of the class I get a bunch of compile errors? I think IT has to do with FF\_VISITABLE\_STRUCT\_NONSTANDARD\_CONSTRUCTION? Is there some rule that I'm not aware of of what can and can't be passed in? 

I also defined an initializer list as a lot of places in the code base reference GenericTensorAccessors and they initialize it using a three parameter constructor (ie. {datatype, shape, pointer}) so needed to add a way to default tensor location. Is it safe to say that previous references are on GPU or do I need to sift through this manually? 

In addition, allocator's also now store additional state as well on if they allocate things on CPU or GPU so we can initialize the values for GenericTensorAccessors. 
___
*[`lib/kernels/test/src/test_utils.h` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27yK0C7WfaM6kspJQL:-O36FG_iDmXGso8MsPQW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are concrete values needed?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27xMO-8SvKBfd4uDSH:-O36Ztfc6EIhqBnicKqV:b-tuuu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It seems like this is just being used to create a random tensor, seems like that might be a better behavior?
</blockquote></details>

This is mainly for debugging purposes, so can create like an iota filled accessor or etc. 
___
*[`lib/kernels/test/src/test_utils.h` line 88 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27x05-E5bxZG1jr5LG:-O37R0e14tv4tXL3R8sI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/test/src/test_utils.h#L88)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The behavior of this method seems rather confusing, I'd stick to explicitly stating the direction you'd like to transfer (either from Host to Device, or reversed)/
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.h` line 89 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27yiCB9G4rcu_7P3Tf:-O36gFxF9i5aaWQfxlBR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb1 [...]

2024-08-07 03:52 UTC, lockshaw requested changes
> Reviewed 48 of 48 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: all files reviewed, 35 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 31 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enN4_C4IRH6d6MLB8:-O3enN4_C4IRH6d6MLB9:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L31)):*
> ```objc
>   double *get_double_ptr() const;
>   half *get_half_ptr() const;
> ```





_Code snippet:_
```objc
GenericTensorAccessorW() = delete;
```
___
*[`lib/kernels/include/kernels/accessor.h` line 33 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emqjJCNgyvQfZX-ST:-O3emqjJCNgyvQfZX-SU:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L33)):*
> ```objc
> 
>   GenericTensorAccessorW(DataType dt,
>                          ArrayShape sh,
> ```





_Suggestion:_
```objc
                         ArrayShape const &sh,
```
___
*[`lib/kernels/include/kernels/accessor.h` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emnAe-Rvy7T4tqKDI:-O3emnAf1s2xL30lyK_C:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L34)):*
> ```objc
>   GenericTensorAccessorW(DataType dt,
>                          ArrayShape sh,
>                          req<void *> p,
> ```





_Suggestion:_
```objc
                         void *p,
```
___
*[`lib/kernels/include/kernels/accessor.h` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emwGH9uSAONrtikUW:-O3emwGH9uSAONrtikUX:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L35)):*
> ```objc
>                          ArrayShape sh,
>                          req<void *> p,
>                          bool on_dev = true)
> ```





_Suggestion:_
```objc
  GenericTensorAccessorW(DataType data_type,
                         ArrayShape shape,
                         req<void *> ptr,
                         bool on_dev = true)
```
___
*[`lib/kernels/include/kernels/accessor.h` line 36 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emfgU1hMG2IQ6vgAh:-O3emfgU1hMG2IQ6vgAi:ble6w3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L36)):*
> ```objc
>                          req<void *> p,
>                          bool on_dev = true)
>       : data_type(dt), shape(sh), ptr(p), on_device(on_dev) {}
> ```

Move to `.cc` file
___
*[`lib/kernels/include/kernels/accessor.h` line 41 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emir-5A0SqkuCLIAf:-O3emir-5A0SqkuCLIAg:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L41)):*
> ```objc
>   DataType data_type;
>   ArrayShape shape;
>   req<void *> ptr;
> ```





_Suggestion:_
```objc
  void * ptr;
```
___
*[`lib/kernels/include/kernels/accessor.h` line 42 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3en1jIDOqjFEB1JARy:-O3en1jIDOqjFEB1JARz:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L42)):*
> ```objc
>   ArrayShape shape;
>   req<void *> ptr;
>   bool on_device;
> ```





_Suggestion:_
```objc
  DeviceType device_type;
```
___
*[`lib/kernels/include/kernels/accessor.h` line 43 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enX7XE6Vf7lH72e0Q:-O3enX7XE6Vf7lH72e0R:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L43)):*
> ```objc
>   req<void *> ptr;
>   bool on_device;
> };
> ```





_Suggestion:_
```objc
  bool operator==(GenericTensorAccessorW const &) const;
  bool operator!=(GenericTensorAccessorW const &) const;

public:
  DataType data_type;
  ArrayShape shape;
  req<void *> ptr;
  bool on_device;
private:
  std::tuple<decltype(data_type) const &,
             decltype(shape) const &,
             decltype(ptr) const &,
             decltype(on_device) const &>
    tie() const;
};

// in .cc file
std::tuple<DataType const &,
           ArrayShape const &,
           void *,
           DeviceType const &>
    GenericTensorAccessorW::tie() const {
  return std::tie(this->data_type, this->shape, this->ptr, this->on_device);     
}

bool GenericTensorAccessorW::operator==(GenericTensorAccessorW const &other) const {
  return this->tie() == other.tie();
}

bool GenericTensorAccessorW::operator!=(GenericTensorAccessorW const &other) const {
  return this->tie() != other.tie(); 
}
```
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enDFn83mq5rhOvjdY:-O3enDFn83mq5rhOvjdZ:bg1pecf) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L45)):*
> ```objc
> };
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(
>     GenericTensorAccessorW, data_type, shape, ptr, on_device);
> ```

`visitable` is deprecated
___
*[`lib/kernels/include/kernels/accessor.h` line 64 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqbco1URsXtNPddP2:-O3eqbco1URsXtNPddP3:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L64)):*
> ```objc
>   double const *get_double_ptr() const;
>   half const *get_half_ptr() const;
> ```





_Code snippet:_
```objc
GenericTensorAccessorR() = delete;
```
___
*[`lib/kernels/include/kernels/accessor.h` line 65 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqRqI1YXdjtMhTywm:-O3eqRqI1YXdjtMhTywn:ble6w3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L65)):*
> ```objc
>   half const *get_half_ptr() const;
> 
>   GenericTensorAccessorR(DataType dt,
> ```

Move to `.cc` file
___
*[`lib/kernels/include/kernels/accessor.h` line 77 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqTWa3lg60czieLWS:-O3eqTWb5AjEwlHqHMkr:b-t0pcjm) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L77)):*
> ```objc
>   bool on_device;
> };
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(
> ```

Make same `tie` changes as above to add `==`, `!=`, `hash` back in (they're currently added by `visitable`)
___
*[`lib/kernels/include/kernels/allocation.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqilP3BGbxUetiN61:-O3eqilP3BGbxUetiN62:bdi4t6k) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L14)):*
> ```objc
> struct IAllocator {
>   virtual void *allocate(size_t) = 0;
>   virtual void *allocate_and_zero(size_t) = 0;
> ```

Delete, if you want to zero the allocation you can zero it with some other function, don't make it part of the allocator interface
___
*[`lib/kernels/include/kernels/allocation.h` line 16 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqv2wB_1XUliRF_OI:-O3eqv2wB_1XUliRF_OJ:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L16)):*
> ```objc
>   virtual void *allocate_and_zero(size_t) = 0;
>   virtual void deallocate(void *) = 0;
> ```





_Code snippet:_
```objc
virtual DeviceType get_allocation_device_type() = 0;
```
___
*[`lib/kernels/incl [...]

2024-10-08 07:22 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: 8 of 83 files reviewed, 35 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 31 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enN4_C4IRH6d6MLB8:-O3o5BcjACsVISUHvtpV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L31)):*
> ```objc
>   double *get_double_ptr() const;
>   half *get_half_ptr() const;
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 33 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emqjJCNgyvQfZX-ST:-O3o5E2D2cmYccHhYXSm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L33)):*
> ```objc
> 
>   GenericTensorAccessorW(DataType dt,
>                          ArrayShape sh,
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emnAe-Rvy7T4tqKDI:-O3o5OWC2rU50lQU2chd:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L34)):*
> ```objc
>   GenericTensorAccessorW(DataType dt,
>                          ArrayShape sh,
>                          req<void *> p,
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emwGH9uSAONrtikUW:-O3o5Xdl8e7wxuU3MNnN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L35)):*
> ```objc
>                          ArrayShape sh,
>                          req<void *> p,
>                          bool on_dev = true)
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 36 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emfgU1hMG2IQ6vgAh:-O3o5gdDAi1jjKZ-Ih9O:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 41 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3emir-5A0SqkuCLIAf:-O3o5iki3w8fhbK4_TM9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L41)):*
> ```objc
>   DataType data_type;
>   ArrayShape shape;
>   req<void *> ptr;
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 42 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3en1jIDOqjFEB1JARy:-O7bFwjx0QxI6s0J3q4c:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L42)):*
> ```objc
>   ArrayShape shape;
>   req<void *> ptr;
>   bool on_device;
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 43 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enX7XE6Vf7lH72e0Q:-O7BqmC209vjVYHjcON2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L43)):*
> ```objc
>   req<void *> ptr;
>   bool on_device;
> };
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3enDFn83mq5rhOvjdY:-O7BqmUc2WeEonfz9mOm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`visitable` is deprecated
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 64 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqbco1URsXtNPddP2:-O3yxH8g70iEf4ohQj1d:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L64)):*
> ```objc
>   double const *get_double_ptr() const;
>   half const *get_half_ptr() const;
> ```

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 65 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqRqI1YXdjtMhTywm:-O7Bqo2Y5eE13BhZg94O:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 77 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqTWa3lg60czieLWS:-O7BqoZI48jUp6I8f3ts:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/accessor.h#L77)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Make same `tie` changes as above to add `==`, `!=`, `hash` back in (they're currently added by `visitable`)
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/allocation.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqilP3BGbxUetiN61:-O7BrVxB9Ok0Zl1MZNB9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete, if you want to zero the allocation you can zero it with some other function, don't make it part of the allocator interface
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/allocation.h` line 16 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqv2wB_1XUliRF_OI:-O7Brdl92RdQ10zbxjZa:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L16)):*
> ```objc
>   virtual void *allocate_and_zero(size_t) = 0;
>   virtual void deallocate(void *) = 0;
> ```

Done.
___
*[`lib/kernels/include/kernels/allocation.h` line 25 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqp471CBhyfSqCFLg:-O7Brebd0nSByNfJ3XSz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/allocation.h` line 28 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqqDKBqXXt8-DV79X:-O7BrjSa9X5UofrjTWSK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/allocation.h` line 40 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3eqrm7C8rXVtewfnxw:-O7BroKV2P9ZsoXPC-iq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels/allocation.h#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/local_cpu_allocator.h` line 13 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3er6UI3sj4kBseUNn8:-O7Brum86MyGoTkUjVPv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/include/kernels [...]

2024-10-09 03:01 UTC, lockshaw requested changes
> Reviewed 72 of 75 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: all files reviewed, 33 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/CMakeLists.txt` line 33 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j-nIA2gAOCTFXVStk:-O8j-nIA2gAOCTFXVStl:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/CMakeLists.txt#L33)):*
> ```CMake
>   nccl
>   utils
>   pcg
> ```

Why?
___
*[`lib/kernels/include/kernels/accessor.h` line 15 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j4QS4D3MimnHcyBAl:-O8j4QS4D3MimnHcyBAm:b-vflnc1) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/accessor.h#L15)):*
> ```objc
> namespace FlexFlow {
> 
> class GenericTensorAccessorW {
> ```

@reyna-abhyankar Is there a reason we have both `GenericTensorAccessorW` and `GenericTensorAccessorR` over just having one `GenericTensorAccessor` and passing it as either `const &` or mutable `&`?
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j2lge4Ty6ttR636xN:-O8j2lge4Ty6ttR636xO:b-hs5ci6) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/accessor.h#L45)):*
> ```objc
>   template <DataType DT, typename... Indices>
>   real_type_t<DT> &at(Indices... indices) {
>     if (this->device_type != DeviceType::CPU) {
> ```

Any reason for this over the simpler `at(std::vector<int> const &)`?



_Code quote:_
```objc
  template <DataType DT, typename... Indices>
  real_type_t<DT> &at(Indices... indices) {
    if (this->device_type != DeviceType::CPU) {
```
___
*[`lib/kernels/include/kernels/reverse_kernels_cpu.h` line 5 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j0ZjoD_4_kN71QKdf:-O8j0ZjoD_4_kN71QKdg:b-e08q1c) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/reverse_kernels_cpu.h#L5)):*
> ```objc
> 
> #include "accessor.h"
> #include "device.h"
> ```

Prefer full include paths



_Suggestion:_
```objc
#include "kernels/accessor.h"
#include "kernels/device.h"
```
___
*[`lib/kernels/src/accessor.cc` line 30 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j3dOw4Fb5HLet-kSb:-O8j3dOw4Fb5HLet-kSc:bkhqp0v) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/accessor.cc#L30)):*
> ```cpp
>   }
> 
>   size_t offset = 0;
> ```

@Marsella8 Do you think we could reasonably add some generic `coord -> index` & index apsce concept in `utils` and then move this code and part of the 1458 over to use it? Feels like this logic is getting unnecessarily reimplemented
___
*[`lib/kernels/src/accessor.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j48JVE4gQ4XMsDizw:-O8j48JW29wJmUL2p6aC:b-q5m3b2) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/accessor.cc#L47)):*
> ```cpp
> 
>     offset += cur_idx * multiplier;
>     multiplier *= this->shape[legion_dim_t(i)];
> ```

Prefer `at` for bounds checking (`ArrayShape` may have bounds-checking for both, but other containers don't so it's a good habit)



_Suggestion:_
```cpp
    multiplier *= this->shape.at(legion_dim_t(i));
```
___
*[`lib/kernels/src/allocation.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j7OwQ7CFEuJLQmvD0:-O8j7OwQ7CFEuJLQmvD1:b-9867am) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/allocation.cc#L22)):*
> ```cpp
>   void *ptr = this->allocate(get_size_in_bytes(tensor_shape));
>   return {
>       tensor_shape.data_type, tensor_shape, ptr, get_allocation_device_type()};
> ```

Prefer explicit `this->`



_Suggestion:_
```cpp
     tensor_shape.data_type, tensor_shape, ptr, this->get_allocation_device_type()};
```
___
*[`lib/kernels/src/cpu/replicate_kernels.cc` line 7 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j4rjf23VTVUhEnIVK:-O8j4rjf23VTVUhEnIVL:b-uqed4s) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/replicate_kernels.cc#L7)):*
> ```cpp
> 
> template <typename T>
> void cpu_replicate_backward_kernel(T *input,
> ```

Move over to use the new `GenericTensorAccessor` access-by-multidimensional-index support?
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O27hwl524nsHT8h0Vfs:-O8j5K6bCVR_O58i42bi:bmhoa86) ([raw file](https://github.com/flexflow/FlexFlow/blob/723515bbdb198b97ae04fec110388b9c7edc1036/lib/kernels/src/cpu/reverse_kernels.cc#L14)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yeah this is much clearer, thanks (also it would be good to rename `blk` to `block` as it's a bit nonobvious that `blk` means `block` and not `bulk`)
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 13 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j5ek95f49gA7a-jA1:-O8j5ek95f49gA7a-jA2:b4dv5hp) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/reverse_kernels.cc#L13)):*
> ```cpp
>                   GenericTensorAccessorW &output,
>                   coord_t num_out_blks,
>                   coord_t reverse_dim_size,
> ```

Can't we just get this from the shape information contained in `input`?



_Code quote:_
```cpp
                 coord_t reverse_dim_size,
```
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 49 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j5oDI1VmQoai-fSVa:-O8j5oDI1VmQoai-fSVb:bxxiq9z) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/reverse_kernels.cc#L49)):*
> ```cpp
>   DataTypeDispatch1<CPUReverseForwardKernel>{}(input_accessor.data_type,
>                                                input_accessor,
>                                                std::ref(output_accessor),
> ```

Why is `std::ref` necessary?



_Code quote:_
```cpp
std::ref(output_accessor),
```
___
*[`lib/kernels/test/CMakeLists.txt` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j65Zp5QG-543OeLmq:-O8j65Zp5QG-543OeLmr:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/CMakeLists.txt#L17)):*
> ```CMake
>     cudart
>     cublas
>     pcg
> ```

Why?
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 36 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3etp5e8MVgjRzmr4uU:-O8jC7yI7yvAGskzP1ES:bz84j2i) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/test/src/test_batch_norm_kernel.cc#L36)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I wanted create_random_filled_accessor to just return a random accessor filled with decimal values. Initially, I had it where it would always be a float, but realized from doing the cast_kernel operator, that we could sometimes want it to be a double as well rather than float
</blockquote></details>

Sure, but the DataType is already present in the `input_shape`, so probably better to just use that than force the user to pass the `DataType` twice
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 87 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j6jpoDhVi70wfr8AP:-O8j6jpoDhVi70wfr8AQ:bn22spa) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/src/test_cast_kernel.cc#L87)):*
> ```cpp
> 
>       st [...]

2024-10-15 06:55 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: 51 of 85 files reviewed, 33 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/CMakeLists.txt` line 33 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j-nIA2gAOCTFXVStk:-O8soTHW75th5PveloTO:b-4j5u81) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/CMakeLists.txt#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I'm currently using the DeviceType enum from pcg/device_type.dtg.h
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j2lge4Ty6ttR636xN:-O8zSaDoBp8y_8-BgquG:b19ye1o) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/accessor.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any reason for this over the simpler `at(std::vector<int> const &)`?
</blockquote></details>

Mainly such that you can just use .at<DT>(1,2,3) instead of .at<DT>({1,2,3})... no need for unneeded initializer list 
___
*[`lib/kernels/include/kernels/reverse_kernels_cpu.h` line 5 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j0ZjoD_4_kN71QKdf:-O8zR0MO6YPzQfrV3Ad1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/reverse_kernels_cpu.h#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer full include paths
</blockquote></details>

Done.
___
*[`lib/kernels/src/accessor.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j48JVE4gQ4XMsDizw:-O8zS51yA8ZiUNVAbOwY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/accessor.cc#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `at` for bounds checking (`ArrayShape` may have bounds-checking for both, but other containers don't so it's a good habit)
</blockquote></details>

Done.
___
*[`lib/kernels/src/allocation.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j7OwQ7CFEuJLQmvD0:-O8zSGKn3nxuDkeOZX0Z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/allocation.cc#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit `this->`
</blockquote></details>

Done.
___
*[`lib/kernels/src/cpu/replicate_kernels.cc` line 7 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j4rjf23VTVUhEnIVK:-O8zc0roDONgFCNzElpK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/replicate_kernels.cc#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move over to use the new `GenericTensorAccessor` access-by-multidimensional-index support?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 13 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j5ek95f49gA7a-jA1:-O8zfMJC8xo-2Id3lFjv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/reverse_kernels.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can't we just get this from the shape information contained in `input`?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 49 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j5oDI1VmQoai-fSVa:-O8zfoSaA7Nw3fNDfG3h:bwkrt56) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/reverse_kernels.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is `std::ref` necessary?
</blockquote></details>

I run into lvalue, rvalue issues with output_accessor without utilizing std::ref. For some reason DataTypeDispatch1 I think is forwarding output accessor as an rvalue which is causing an error? I think it's related to output_accessor being non const, which it has to be in order for the .at method to return a non const pointer which we can assign values to. std::ref seems to fix this issue though. 

If possible, I think we can also just modify how forwarding works in DataTypeDispatch1 to fix this issue as well though? 
___
*[`lib/kernels/test/CMakeLists.txt` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j65Zp5QG-543OeLmq:-O8smk_wAkDUdIDln1Q6:b-4j5u81) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/CMakeLists.txt#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I'm currently using the DeviceType enum from pcg/device_type.dtg.h
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 36 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O3etp5e8MVgjRzmr4uU:-O99MzaO8us7TD2zG9BR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e6e216191e16af51880ba97c3e80c770664b85cd/lib/kernels/test/src/test_batch_norm_kernel.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Sure, but the DataType is already present in the `input_shape`, so probably better to just use that than force the user to pass the `DataType` twice
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 87 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j6jpoDhVi70wfr8AP:-O99N0iC2qB2HcXFsFYc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/src/test_cast_kernel.cc#L87)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just get back a `GenericTensorAccessorR` with its data on CPU? Throwing away all the information by dropping down to a `std::vector` feels unnecessary
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 91 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j70zN0pAczXZfVwAW:-O9-HjTW921oYHveiOhB:b-hk56mm) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/src/test_cast_kernel.cc#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If the data is random, why would I expect `input_accessor_cpu` to have the same data as `input_accessor_gpu`? Would it be cleaner to generate a `GenericTensorAccessor` with random data on CPU, then create a copy of that on GPU, and then run the functions?
</blockquote></details>

Didn't catch this as test was going from float between 0 and 1 to an int   lol, so it was basically just comparing if a tensor of all zeros was equal to another tensor of all zeros
___
*[`lib/kernels/test/src/test_concat_kernel.cc` line 9 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j9V6z2l9qEBVUbVnX:-O99RPRu7nM8NY8YjEPz:b8kdju5) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/test/src/test_concat_kernel.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why these changes?
</blockquote></details>

Was printing outputs and was easier to visually compare 
___
*[`lib/kernels/test/src/test_replicate_kernel.cc` line 78 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j9sJj1LdSGTdCoUZ_:-O8zyKEJ3tkZRW66ZeNk:bs9zay7) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b [...]

2024-11-05 07:12 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: 57 of 95 files reviewed, 27 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 15 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j4QS4D3MimnHcyBAl:-OAd1Vxl5jePtM6aYu5Y:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/accessor.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

At least in the meantime it seems like it would make sense to have `GenericTensorAccessorW` non-explicitly coerce to `GenericTensorAccessorR` I think to avoid all of the overloading?
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j2lge4Ty6ttR636xN:-OAR5oLt0I7xb-vvFQ1y:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/include/kernels/accessor.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Let's do the `std::vector` version unless there's some additional advantage you haven't mentioned yet. Yes the template syntax is cute and all, but it's substantially more complicated feature-wise and all it seems to do is remove the need to type two characters (also it doesn't allow for passing in coordinates of runtime-determined dimension)
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-EPmB60YFD_VlIW7:-OAQt0sPD5jiUkPp6pUr:b6ns449) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/accessor.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Better to `#include` in the header that contains `Allocator`
</blockquote></details>

I can't "#include/kernels/allocation.h" as circular dependency between allocator and accessor 
___
*[`lib/kernels/include/kernels/accessor.h` line 264 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gPQJkBocYsu1iqstr:-OAQtxDj0gnRwjB0d90V:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/accessor.h#L264)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes parameter order clear, and makes the operation a bit clearer ("transfer" sounds more like a "move" operation)
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/replicate_kernels.h` line 15 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gQOcSC-nXFJaO6wF_:-OAQuGar1KWBV10qpHZz:b-gg4tef) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/replicate_kernels.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why reorder `input` and `output`?
</blockquote></details>

Slightly unneeded, but I prefer the format of output before input as it matches the other cpu_kernels I have written so far. 

As it relates to all other kernels though, a lot of the kernels vary on whether they have input or output first... should probably standardize this? 
___
*[`lib/kernels/include/kernels/replicate_kernels_cpu.h` line 13 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gQU716S-RG9wGrouf:-OAQunec35PPCv1Hg7Rs:bnrqet0) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/replicate_kernels_cpu.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why reorder `input` and `output`?
</blockquote></details>

same as prev 
___
*[`lib/kernels/src/accessor.cc` line 32 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gZsD_6WkOkuKqiVIA:-OAQv44I9UHFWhc4jo2t:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/accessor.cc#L32)):*
> ```cpp
>                          num_bytes,
>                          cudaMemcpyDeviceToDevice));
>   }
> ```

Done.
___
*[`lib/kernels/src/managed_ff_stream.cc` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-h3YBAS1_KItbBE1:-OAuvUct8g7WrcvwC-jY:b7ezp7j) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_ff_stream.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Similar to per_device_ff_handle but I also thought it'd be safer to fully transfer ownership rather than potentially leaving dangling resources 
___
*[`lib/kernels/src/managed_per_device_ff_handle.cc` line 22 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gRGpGBXkaGTFcAQJ-:-OAd7GZC5-IlEaK3mUZ9:bauhome) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_per_device_ff_handle.cc#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why change this from `swap`?
</blockquote></details>

I thought it's good practice to invalidate the other ManagedPerDeviceFFHandle in a move constructor, so changed to exchange to set other handle's ptr now as nullptr 
___
*[`lib/kernels/src/managed_per_device_ff_handle.cc` line 40 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gRKYf4w18Jp5l3Zet:-OAd7C5m4dI12uP4S1I9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_per_device_ff_handle.cc#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why explicitly assign the `handle` to `nullptr`?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 49 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O8j5oDI1VmQoai-fSVa:-OARC-6-AK6oP8V7l6mG:b-872myh) ([raw file](https://github.com/flexflow/FlexFlow/blob/a7422f776a02ce29127730b8920234f696e8668f/lib/kernels/src/cpu/reverse_kernels.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm tentatively guessing that might be due to `DataTypeDispatch1` and `DataTypeDispatch2` taking their arguments as `Args ...` rather than as `Args &&...`--can you try making that change and seeing if it fixes the problem?
</blockquote></details>

Fixed the issue 
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 138 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gVwUh6rPzy5Pwv03N:-OAuyiVJ8aiENXItfEQk:ba5ta4n) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/cuda/ops/linear_kernels.cu#L138)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Avoid c-style casts
</blockquote></details>

reinterpret cast okay here? 
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 83 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gWistArgYPTutZK6i:-OAQyE932fg8HY-Ygy3i:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/test/src/test_cast_kernel.cc#L83)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any reason not to just get these `DataType`s from the accessors' shape fields?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 85 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gWUi71jYi8cK59Clb:-OAQziG71a2tNHe0KjtY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/tes [...]

2024-11-11 02:30 UTC, lockshaw requested changes
> Reviewed 38 of 38 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: all files reviewed, 72 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-EPmB60YFD_VlIW7:-OAyXbTV900XKQfIClSK:bvxtfsb) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/accessor.h#L14)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I can't "#include/kernels/allocation.h" as circular dependency between allocator and accessor
</blockquote></details>

Fair enough. In that case I'd recommend pulling `copy_tensor_accessor_r` and `copy_tensor_accessor_w` (I believe these are the only two usages of `Allocator` in this file) into a separate header file--this header file is getting rather large already anyway
___
*[`lib/kernels/include/kernels/replicate_kernels.h` line 15 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gQOcSC-nXFJaO6wF_:-OBO1q_D3WUPD6Qf-wwo:b-uezhqe) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/replicate_kernels.h#L15)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Slightly unneeded, but I prefer the format of output before input as it matches the other cpu_kernels I have written so far. 

As it relates to all other kernels though, a lot of the kernels vary on whether they have input or output first... should probably standardize this?
</blockquote></details>

Sure, feel free to standardize the kernel functions in a future PR (that would be great actually), though we should make sure we actually have tests up and running for all of the kernels to make sure we don't accidentally break anything. I've created an issue to track this and assigned it to you: https://github.com/flexflow/FlexFlow/issues/1540
___
*[`lib/kernels/src/managed_ff_stream.cc` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-h3YBAS1_KItbBE1:-OBO2WmV5zwdvQPaie09:bmaltog) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_ff_stream.cc#L14)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Similar to per_device_ff_handle but I also thought it'd be safer to fully transfer ownership rather than potentially leaving dangling resources
</blockquote></details>

Makes sense, my only concern is the degree of code duplication. Is there anything reasonable we can do to reduce it to minimize bugs when this file is edited?
___
*[`lib/kernels/src/managed_per_device_ff_handle.cc` line 22 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gRGpGBXkaGTFcAQJ-:-OBO-IGc-zuxNnMcWwiH:bbx5lca) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_per_device_ff_handle.cc#L22)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I thought it's good practice to invalidate the other ManagedPerDeviceFFHandle in a move constructor, so changed to exchange to set other handle's ptr now as nullptr
</blockquote></details>

That's fine (and not a bad practice), it's just currently leading to a lot of duplicated code between this function and the destructor. With the previous solution you implicitly get the destructor call when the moved-from value is deallocated. Is there a way the duplicated code in this solution could be reduced? The current structure makes editing this file a bit bugprone
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 138 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gVwUh6rPzy5Pwv03N:-OBNte82EEJmyeiw6ZXe:b-zcy3qw) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/cuda/ops/linear_kernels.cu#L138)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

reinterpret cast okay here?
</blockquote></details>

Generally you want to use the weakest/most-restrictive cast construction that you can, and `static_cast<void const *>` works fine here so you should use that throughout this file.
___
*[`lib/local-execution/src/ops/linear.cc` line 152 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S0szhEoNHrevO2UUx:-OBO1k5oBw9RXcqkJDB4:b-6cner7) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/local-execution/src/ops/linear.cc#L152)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Needed to make some changes to permissions of accessors to enable this, due to const types with bias_ptr and output_grad ptr
</blockquote></details>

What do you mean--I'm not seeing any changes to this in `accessors.h`? Am I missing something?
___
*[`lib/kernels/include/kernels/accessor.h` line 166 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyX9yI1k1hR-zyIjQJ:-OAyX9yI1k1hR-zyIjQK:biy64f8) ([raw file](https://github.com/flexflow/FlexFlow/blob/e869ace02b8aaf00feae775023dae755b14e43aa/lib/kernels/include/kernels/accessor.h#L166)):*
> ```objc
> std::ostream &operator<<(std::ostream &, GenericTensorAccessorR const &);
> 
> int32_t *get_int32_ptr(GenericTensorAccessorW const &);
> ```

Why were these removed? Not necessarily objecting, just curious
___
*[`lib/kernels/src/accessor.cc` line 29 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNlb3B9_ObzhavSxw6:-OBNlb3B9_ObzhavSxw7:b-8n1vi4) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L29)):*
> ```cpp
>   } else {
>     assert(src_device_type == DeviceType::GPU);
>     assert(src_device_type == DeviceType::CPU);
> ```

I don't think this is possible as `src_device_type` can't have two values at once



_Code quote:_
```cpp
    assert(src_device_type == DeviceType::GPU);
    assert(src_device_type == DeviceType::CPU);
```
___
*[`lib/kernels/src/accessor.cc` line 70 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNlhSU-bA--DZyKkZJ:-OBNlhSU-bA--DZyKkZK:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L70)):*
> ```cpp
> 
>   for (size_t i = 0; i < this->shape.num_dims(); i++) {
>     if (indices[i] >= this->shape.at(legion_dim_t(i))) {
> ```





_Suggestion:_
```cpp
indices.at(i) 
```
___
*[`lib/kernels/src/accessor.cc` line 75 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNljp60wbys1u66wA6:-OBNljp60wbys1u66wA7:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L75)):*
> ```cpp
>                       "when only {} indexes exist",
>                       i,
>                       indices[i],
> ```





_Suggestion:_
```cpp
indices.at(i),
```
___
*[`lib/kernels/src/accessor.cc` line 79 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNllbg9g29Pyg-wQFb:-OBNllbg9g29Pyg-wQFc:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L79)):*
> ```cpp
>     }
> 
>     offset += indices[i] * multiplier;
> ```





_Suggestion:_
```cpp
indices.at(i)
```
___
*[`lib/kernels/src/accessor.cc` line 145 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyY8683xIrdnd1fNWS:-OAyY8683xIrdnd1fNWT:bxrb9rj) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L145)):*
> ```cpp
>     std::vector<size_t> const &indices) const {
> 
>   if (indices.size() != this->shape.num_dims()) {
> ```

Pull out into a separate helper function to avoid the duplicati [...]

2024-11-16 01:10 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1439)* status: 64 of 108 files reviewed, 72 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 166 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyX9yI1k1hR-zyIjQJ:-OBmSrtg8Mw9vf0XaC5i:b-dtvgzp) ([raw file](https://github.com/flexflow/FlexFlow/blob/e869ace02b8aaf00feae775023dae755b14e43aa/lib/kernels/include/kernels/accessor.h#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why were these removed? Not necessarily objecting, just curious
</blockquote></details>

Got sloppy, my bad ~ for some reason didn't see one of them returned const and thought were same 
___
*[`lib/kernels/include/kernels/accessor.h` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-EPmB60YFD_VlIW7:-OBUNGEKD-0fsS0VSWcJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/accessor.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Fair enough. In that case I'd recommend pulling `copy_tensor_accessor_r` and `copy_tensor_accessor_w` (I believe these are the only two usages of `Allocator` in this file) into a separate header file--this header file is getting rather large already anyway
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyWQ4g8_sZGNF0TWd4:-OBUXV0W5Lsq_OAaFjWE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/include/kernels/accessor.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` over `size_t` to make issues from using negative values at least somewhat detectable
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyWtIx24thg5pMNrdp:-OBWqr3s1wpiOb5UT7Gg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/include/kernels/accessor.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This function should probably be bound-checked.
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 112 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyX04jCkRSyiKM5Irj:-OBWqrfL06I3BD8Lv12o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/include/kernels/accessor.h#L112)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This function should probably be bounds-checked
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/replicate_kernels.h` line 15 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gQOcSC-nXFJaO6wF_:-OBmTYWg1hFIdOt2NNOQ:brxp9sc) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/include/kernels/replicate_kernels.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Sure, feel free to standardize the kernel functions in a future PR (that would be great actually), though we should make sure we actually have tests up and running for all of the kernels to make sure we don't accidentally break anything. I've created an issue to track this and assigned it to you: https://github.com/flexflow/FlexFlow/issues/1540
</blockquote></details>

Sounds good 
___
*[`lib/kernels/src/accessor.cc` line 29 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNlb3B9_ObzhavSxw6:-OBWXmbp2P7V1r-5y258:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this is possible as `src_device_type` can't have two values at once
</blockquote></details>

Done.
___
*[`lib/kernels/src/accessor.cc` line 145 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OAyY8683xIrdnd1fNWS:-OBWqp_51aO0sgCxmU3f:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L145)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull out into a separate helper function to avoid the duplication between `GenericTensorAccessorR::calculate_index_offset` and `GenericTensorAccessorW::calculuate_index_offset` (and then honestly it's probably a good idea to just remove those methods as I'm not sure they're doing much then other than just forwarding arguments to the helper function.
</blockquote></details>

Done.
___
*[`lib/kernels/src/accessor.cc` line 153 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNlsck17I-mvTZvCoC:-OBUO9h9EeJML-_3FJxp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L153)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer int
</blockquote></details>

Done.
___
*[`lib/kernels/src/accessor.cc` line 166 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNmeJPCFxTWWbqcuj_:-OBUODKz50oq4Hd98SAb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/accessor.cc#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `{}` initialization
</blockquote></details>

Done.
___
*[`lib/kernels/src/managed_ff_stream.cc` line 14 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9S-h3YBAS1_KItbBE1:-OBWaUd_CE2BEwMnOVC9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_ff_stream.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes sense, my only concern is the degree of code duplication. Is there anything reasonable we can do to reduce it to minimize bugs when this file is edited?
</blockquote></details>

Done.
___
*[`lib/kernels/src/managed_per_device_ff_handle.cc` line 22 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gRGpGBXkaGTFcAQJ-:-OBWaStoEcJEyrnS0Jcz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/managed_per_device_ff_handle.cc#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

That's fine (and not a bad practice), it's just currently leading to a lot of duplicated code between this function and the destructor. With the previous solution you implicitly get the destructor call when the moved-from value is deallocated. Is there a way the duplicated code in this solution could be reduced? The current structure makes editing this file a bit bugprone
</blockquote></details>

Done.
___
*[`lib/kernels/src/cpu/reverse_kernels.cc` line 14 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-OBNnu5H94UniCH16XgB:-OBUPX7o2R1XjLteZD0s:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/src/cpu/reverse_kernels.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer int
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 138 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1439#-O9gVwUh6rPzy5Pwv03N:-OBWaWBwEVKE2JACN_2_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/kernels/src/cuda/ops/lin [...]

2024-12-24 21:56 UTC, lockshaw requested changes
> Reviewed 31 of 44 files at r11, 63 of 67 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1439)* status: 140 of 144 files reviewed, 27 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/test/src/test_managed_per_device_ff_handle.cc` line 24 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OBNnLMHDE5JfbnsG5mv:-OEuVyX2CRUvZ-cZIBNl:b-mqfsp2) ([raw file](https://github.com/flexflow/flexflow-train/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/test/src/test_managed_per_device_ff_handle.cc#L24)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing this done?
___
*[`lib/kernels/test/src/test_utils.cc` line 202 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OBO1Ogf8170vdfz_3c4:-OEuaVoqBNiEOBOg907Y:bk8upyo) ([raw file](https://github.com/flexflow/flexflow-train/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/test/src/test_utils.cc#L202)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Addressed in Slack
</blockquote></details>

I can't seem to find the explanation. Can you re-explain here or point me to where it was in slack?
___
*[`lib/local-execution/src/ops/linear.cc` line 152 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-O9S0szhEoNHrevO2UUx:-OEubMcs9mje0juoG5Qn:b-ov9o26) ([raw file](https://github.com/flexflow/flexflow-train/blob/7106dec57901c3e580ed130589fbe0965b5db3da/lib/local-execution/src/ops/linear.cc#L152)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Oh, I was referring to making: 

auto bias = acc.get_tensor<Permissions::RO>(BIAS);
auto output_grad = acc.get_tensor_grad<Permissions::RO>(OUTPUT);

to:

auto bias = acc.get_tensor<Permissions::RW>(BIAS);
auto output_grad = acc.get_tensor_grad<Permissions::RW>(OUTPUT);

as backward_kernel needs a non-const pointer to be passed
</blockquote></details>

But why? The kernel doesn't modify the bias, does it? You control the signature of `backward_kernel` so you can always change the signature if it doesn't make sense, it's not set in stone.
___
*[`lib/kernels/include/kernels/accessor.h` line 74 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEue0F9BKEQNwUVzIIa:-OEue0FA9rnPWUns034R:bno9t99) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/accessor.h#L74)):*
> ```objc
> 
>       offset += indices.at(i) * multiplier;
>       multiplier *= this->shape.at(legion_dim_t{i});
> ```

Pull offset calculation (and probably also bounds checking) out into a separate helper function



_Code quote:_
```objc
    int offset = 0;
    int multiplier = 1;
    for (int i = 0; i < this->shape.num_dims(); i++) {
      if (indices.at(i) >= this->shape.at(legion_dim_t{i})) {
        throw mk_runtime_error(
            fmt::format("In {} dimension, attempting to access index {} "
                        "when only {} indexes exist",
                        i,
                        indices.at(i),
                        this->shape.at(legion_dim_t{i})));
      }

      offset += indices.at(i) * multiplier;
      multiplier *= this->shape.at(legion_dim_t{i});
```
___
*[`lib/kernels/include/kernels/accessor.h` line 159 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEudy3bEjnCYjiDmr8_:-OEudy3bEjnCYjiDmr8a:bno9t99) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/accessor.h#L159)):*
> ```objc
> 
>       offset += indices.at(i) * multiplier;
>       multiplier *= this->shape.at(legion_dim_t{i});
> ```

Pull offset calculation (and probably also bounds checking) out into a separate helper function



_Code quote:_
```objc
    int offset = 0;
    int multiplier = 1;
    for (int i = 0; i < this->shape.num_dims(); i++) {
      if (indices.at(i) >= this->shape.at(legion_dim_t{i})) {
        throw mk_runtime_error(
            fmt::format("In {} dimension, attempting to access index {} "
                        "when only {} indexes exist",
                        i,
                        indices.at(i),
                        this->shape.at(legion_dim_t{i})));
      }

      offset += indices.at(i) * multiplier;
      multiplier *= this->shape.at(legion_dim_t{i});
```
___
*[`lib/kernels/include/kernels/accessor.h` line 185 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEueAQe5vP23F-1B7q1:-OEueAQe5vP23F-1B7q2:bno9t99) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/accessor.h#L185)):*
> ```objc
>     T const *data_ptr = static_cast<T const *>(this->ptr);
>     int offset = 0;
>     int multiplier = 1;
> ```

Pull offset calculation (and probably also bounds checking) out into a separate helper function
___
*[`lib/kernels/include/kernels/flat_kernels.h` line 13 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuRrHwAuHpkDpKw7iw:-OEuRrHx65Js0A7LhcZK:b-ucb828) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/flat_kernels.h#L13)):*
> ```objc
>                     float *output_ptr);
> 
> void backward_kernel(cudaStream_t stream,
> ```

Why change from `ffStream_t` to `cudaStream_t`?



_Code quote:_
```objc
cudaStream_t stream,
```
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 29 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuSILvEQ9Ao6HYk9IJ:-OEuSILvEQ9Ao6HYk9IK:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L29)):*
> ```objc
>   void cleanup();
> 
> private:
> ```





_Suggestion:_
```objc
private:  
  void cleanup();

private:
```
___
*[`lib/kernels/include/kernels/managed_ff_stream.h` line 25 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuSFfIEOdSN3_laVtH:-OEuSFfIEOdSN3_laVtI:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/managed_ff_stream.h#L25)):*
> ```objc
> 
> private:
>   ffStream_t *stream;
> ```





_Suggestion:_
```objc
private:  
  void cleanup();

private:
  ffStream_t *stream;
```
___
*[`lib/kernels/include/kernels/loss_function_kernels.h` line 4 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuS-HjCpZ6hi03w3o2:-OEuS-HjCpZ6hi03w3o3:b850oz4) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d5140d5e98c18e73ce576673aa34022ad6d804f/lib/kernels/include/kernels/loss_function_kernels.h#L4)):*
> ```objc
> #define _FLEXFLOW_KERNELS_INCLUDE_KERNELS_LOSS_FUNCTION_KERNELS_H
> 
> #include "kernels/device.h"
> ```

Why remove this? We generally prefer absolute includes over relative includes
___
*[`lib/kernels/include/kernels/metrics_kernels.h` line 18 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuSOZ6CtN6sSoHmhP2:-OEuSOZ6CtN6sSoHmhP3:b-cfdtn5) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/include/kernels/metrics_kernels.h#L18)):*
> ```objc
> void update_metrics_label_kernel_wrapper(float const *logit_ptr,
>                                          float const *label_ptr,
>                                          MetricsAttrs const *me,
> ```

Why take as a pointer rather than by const ref?
___
*[`lib/kernels/test/src/test_utils.cc` line 151 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuamc48PzxXDhc8sxi:-OEuamc48PzxXDhc8sxj:b-4mt4hs) ([raw file](https://github.com/flexflow/flexflow-train/blob/8f0520387bd04d436d373354f917daf3708eed1a/lib/kernels/test/src/test_utils.cc [...]

2025-01-29 01:36 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1439)* status: 94 of 150 files reviewed, 27 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 74 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEue0F9BKEQNwUVzIIa:-OHeQTBoD33IUcd7RMcB:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/accessor.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull offset calculation (and probably also bounds checking) out into a separate helper function
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 159 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEudy3bEjnCYjiDmr8_:-OHeQWlT6DLNRZtD6tP7:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/accessor.h#L159)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull offset calculation (and probably also bounds checking) out into a separate helper function
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/accessor.h` line 185 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEueAQe5vP23F-1B7q1:-OHeQXZGADYFrd9bQWrS:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/accessor.h#L185)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull offset calculation (and probably also bounds checking) out into a separate helper function
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/flat_kernels.h` line 13 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuRrHwAuHpkDpKw7iw:-OHBpBNKDNqLmK0C30FP:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/flat_kernels.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why change from `ffStream_t` to `cudaStream_t`?
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/metrics_kernels.h` line 18 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuSOZ6CtN6sSoHmhP2:-OHBoJeQBAoNCzQEkzWF:by08q7e) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/metrics_kernels.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why take as a pointer rather than by const ref?
</blockquote></details>

I was just matching the func definition in metrics_functions.cu but probably better to keep as const ref 
___
*[`lib/kernels/include/kernels/pool_2d_kernels.h` line 70 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuSf22621nwP_YTHtf:-OHBp1hR6QIEr-2gDGGt:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/include/kernels/pool_2d_kernels.h#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should stay as `ffStream_t`--these header files are intended to be stable between the hip and cuda kernels, with the `ff*` typedefs used to handle the different types used between the two. If you hardcode the type to `cudaStream_t` this fails.
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/embedding_kernels.cu` line 40 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEucoeW1rpq-sakGd_a:-OHBwIwQ2l1NfZ5wt5H5:b-xih3wy) ([raw file](https://github.com/flexflow/flexflow-train/blob/93298eda084436781c87ad9b7b506613b71526d9/lib/kernels/src/cuda/embedding_kernels.cu#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove one template parameter? No particular objection, just curious
</blockquote></details>

Removed as looks like only valid input types are INT32 or INT64, and those template specifications are already directly defined so TI not really needed 
___
*[`lib/kernels/src/cuda/embedding_kernels.cu` line 100 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuccLGDIfrL_IWvtwY:-OHBphEh-Vzz5w2cUTPt:bxwv1l6) ([raw file](https://github.com/flexflow/flexflow-train/blob/93298eda084436781c87ad9b7b506613b71526d9/lib/kernels/src/cuda/embedding_kernels.cu#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove the `optional`?
</blockquote></details>

Because if embed_forward_with_aggr is being called then we have already checked that agg has a value beforehand. 

ie.



_Code snippet:_
```Cuda
if (!aggr.has_value()) {
      embed_forward_no_aggr<half><<<GET_BLOCKS(output.shape.get_volume()),
                                    CUDA_NUM_THREADS,
                                    0,
                                    stream>>>(input.get<DataType::INT32>(),
                                              output.get<DataType::HALF>(),
                                              weight.get<DataType::HALF>(),
                                              out_dim,
                                              batch_size);
    } else {
      assert(aggr == AggregateOp::AVG || aggr == AggregateOp::SUM);
      embed_forward_with_aggr<half><<<GET_BLOCKS(output.shape.get_volume()),
                                      CUDA_NUM_THREADS,
                                      0,
                                      stream>>>(input.get<DataType::INT32>(),
                                                output.get<DataType::HALF>(),
                                                weight.get<DataType::HALF>(),
                                                out_dim,
                                                in_dim,
                                                batch_size,
                                                aggr.value());
    }
  }
```
___
*[`lib/kernels/test/src/test_managed_per_device_ff_handle.cc` line 24 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OBNnLMHDE5JfbnsG5mv:-OHeRDBD03-l0Dt-D-En:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/test/src/test_managed_per_device_ff_handle.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing this done?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.cc` line 202 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OBO1Ogf8170vdfz_3c4:-OHByFKQ7iQGZmZiktXD:b-dpm6e) ([raw file](https://github.com/flexflow/flexflow-train/blob/51c3eb7ae4f84f8bc33811b5f1842187ca81c6ce/lib/kernels/test/src/test_utils.cc#L202)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I can't seem to find the explanation. Can you re-explain here or point me to where it was in slack?
</blockquote></details>

Don't remember what I was referencing then, but it looks like there's a datatype_value.variant.toml already in op-attrs? 
___
*[`lib/kernels/test/src/test_utils.cc` line 151 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OEuamc48PzxXDhc8sxi:-OHBfm1J0gw_85oovvRb:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/8db629db4b1adccb835397c741ed11a6a2b9e8f7/lib/kernels/test/src/test_utils.cc#L151)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't we have cleaner indexing syntax now for accessors that can take something like `(i, j)` rather than doing the calculation inline?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.cc` line 153 at r12](https://reviewable.io/reviews/flexflow/f [...]

2025-02-11 00:49 UTC, lockshaw commented
*[`lib/op-attrs/test/src/op-attrs/datatype_value.cc` line 16 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1439#-OImIFNo9L2HuQev2AnA:-OImIFNo9L2HuQev2AnB:b-y5mf2q) ([raw file](https://github.com/flexflow/flexflow-train/blob/338fc8de93140f6f1b4c4880ee1a42594861b01d/lib/op-attrs/test/src/op-attrs/datatype_value.cc#L16)):*
> ```cpp
>       CHECK_FALSE(data_type_value.has<int32_t>());
>       CHECK_FALSE(data_type_value.has<int64_t>());
>       CHECK_FALSE(data_type_value.has<bool>());
> ```

You can assume that `has` works correctly :slightly_smiling_face: 



_Suggestion:_
```cpp
      CHECK(data_type_value.has<float>());
```


<!-- Sent from Reviewable.io -->

2025-05-02 10:23 UTC, lockshaw approved these changes

2025-05-02 10:47 UTC, merged