temporary weight adjust index
flexflow/flexflow-train pull request #1472
Opened 2024-08-25 17:44 UTC by reyna-abhyankar

**Description of changes:**

Implement end-to-end training loop in local execution.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-09-03 20:33 UTC, lockshaw requested changes
> Reviewed 1 of 2 files at r1, 49 of 50 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: all files reviewed, 47 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/CMakeLists.txt` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Klnft4GZwRRO1GgUo:-O5Klnft4GZwRRO1GgUp:b-7as7a0) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/CMakeLists.txt#L10)):*
> ```CMake
>      LIST_DIRECTORIES False
>      src/*.cc
>      src/cuda/cuda_helper.cu
> ```

Why is this not just `src/cuda/*.cu`?
___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Km3dF88yOXI6nT545:-O5Km3dF88yOXI6nT546:b-u6vsmj) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
> ```objc
>   std::optional<std::size_t> at_maybe(ff_dim_t) const;
> 
>   ArrayShape sub_shape(legion_dim_t start, ff_dim_t end) const;
> ```

`legion_dim_t` for start and `ff_dim_t` for end? Is this signature intended? It's not illogical, just a bit weird and wanted to check it's not a typo :slightly_smiling_face:  
___
*[`lib/kernels/src/array_shape.cc` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tNw0c5BE34XmfEQC8:-O5tNw0c5BE34XmfEQC9:bgs8ev8) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/kernels/src/array_shape.cc#L59)):*
> ```cpp
> ArrayShape ArrayShape::sub_shape(std::optional<ff_dim_t> start,
>                                  std::optional<ff_dim_t> end) const {
>   std::vector<size_t> new_shape;
> ```

Can probably be replaced by `slice(DimOrdered, ...)`: https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L9
___
*[`lib/kernels/src/device.h` line 74 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tO7HSDR2Jnhz1sTN-:-O5tO7HSDR2Jnhz1sTN0:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/kernels/src/device.h#L74)):*
> ```objc
> 
> __global__ void scale_kernel(float *ptr, size_t size, float a, float b);
> __global__ void scale_kernel(float *ptr, unsigned long size, float a, float b);
> ```

Why?
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tOZlXCFnNU2oTmOP9:-O5tOZlXCFnNU2oTmOPA:b-izso4g) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/local_training_backing.h#L18)):*
> ```objc
>                        TensorBackingMap const &,
>                        RuntimeArgConfig const &,
>                        std::optional<ModelTrainingInstance> &);
> ```

Why is this passed as mutable?
___
*[`lib/local-execution/include/local-execution/model_training_instance.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPF__E9sgILo_ph_w:-O5tPF__E9sgILo_ph_x:b-pxa37x) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/model_training_instance.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "ModelTrainingInstance"
> ```

Why isn't the model part of `ModelTrainingInstance`? The members seem to have changed non-trivially since the old version:
```
struct ModelTrainingInstance {
  ComputationGraph computation_graph;
  Optimizer optimizer;
  EnableProfiling enable_profiling;
  TrainingPCG training_pcg;
  TensorMapping tensor_map;
  LegionBacking legion_backing;
};
```
___
*[`lib/local-execution/include/local-execution/model_training_instance.struct.toml` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tP3e59eOObHjKBHcc:-O5tP3e59eOObHjKBHcd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/model_training_instance.struct.toml#L15)):*
> ```TOML
>   "pcg/tensor_guid_t.dtg.h",
>   "pcg/optimizer_attrs.dtg.h",
> ]
> ```





_Suggestion:_
```TOML
includes = [
  "op-attrs/ops/loss_attrs.dtg.h",
  "pcg/tensor_guid_t.dtg.h",
  "pcg/optimizer_attrs.dtg.h",
]
```
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 16 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPeMI82zPuwdgLYVS:-O5tPeMI82zPuwdgLYVT:bvp0y8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L16)):*
> ```objc
> TaskInvocation get_update_invocation(OptimizerAttrs const &,
>                                      tensor_guid_t const &weight,
>                                      std::vector<tensor_guid_t> const &);
> ```

Some parameter names would be helpful here



_Code quote:_
```objc
                                     std::vector<tensor_guid_t> const &);
```
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 22 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPhHn1UFI9HaX1U71:-O5tPhHo6Fy061eVrLhe:bvp0y8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L22)):*
> ```objc
> TaskInvocation sgd_update(SGDOptimizerAttrs const &,
>                           tensor_guid_t const &weight,
>                           tensor_guid_t const &);
> ```

Some parameter names would be helpful here
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 29 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tP_jC2dfiRp-_620H:-O5tP_jC2dfiRp-_620I:bvp0y8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L29)):*
> ```objc
>                            tensor_guid_t const &weight,
>                            tensor_guid_t const &,
>                            tensor_guid_t const &);
> ```

Some parameter names would be helpful here



_Code quote:_
```objc
                           tensor_guid_t const &,
                           tensor_guid_t const &);
```
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 22 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPtFGDeFJl3O4HHG8:-O5tPtFGDeFJl3O4HHG9:b-souair) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L22)):*
> ```TOML
> [[values]]
> type = "::FlexFlow::FwdBwdTaskImplFunction"
> key = "fwd_bwd_task_impl_function"
> ```

Would these be better renamed `InitOpTaskImplFunction` and `FwdBwdOpTaskImplFunction`, or do they make sense outside of a op context?



_Code quote:_
```TOML
[[values]]
type = "::FlexFlow::InitTaskImplFunction"
key = "init_task_impl_function"

[[values]]
type = "::FlexFlow::FwdBwdTaskImplFunction"
key = "fwd_bwd_task_impl_function"
```
___
*[`lib/local-execution/include/local-execution/task_invocation.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQ93M0QZ2yX7ImIQa:-O5tQ93M0QZ2yX7ImIQb:b-wmjjhq) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_invocation.h#L65)):*
> ```objc
>   task_id_t task_id;
>   TaskBinding binding;
> };
> ```

Can be moved over to `dtgen`



_Code quote:_
```objc
struct TaskInvocation {
public:
  TaskInvocation() = delete;
  TaskInvocation(task_id_t task_id, TaskBinding const &binding)
      : task_id(task_id), binding(binding) {}

public:
  task_id_t task_id;
  TaskBinding binding;
};
```
___
*[`lib/local-execution/include/local-execution/task_si [...]

2024-09-11 19:59 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: all files reviewed, 47 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/CMakeLists.txt` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Klnft4GZwRRO1GgUo:-O6WwCCuCZ5FKhMPoi2e:b-eyuygm) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/CMakeLists.txt#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this not just `src/cuda/*.cu`?
</blockquote></details>

There are a couple of files in that folder that haven't been refactored/don't build: `metrics_kernels.cu` and `embedding_kernels.cu`. I think maybe Dylan was going to tackle those?
___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Km3dF88yOXI6nT545:-O6WwecKBkrAp1015ebK:bwdgxgi) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`legion_dim_t` for start and `ff_dim_t` for end? Is this signature intended? It's not illogical, just a bit weird and wanted to check it's not a typo :slightly_smiling_face:
</blockquote></details>

It's called like this in `concat_kernels.cu`:
`blk_size = shape.sub_shape(legion_dim_t{0}, axis).num_elements();` where `axis` is an `ff_dim_t`

I've left it as not implemented for now because I thought it was weird too. 
___
*[`lib/kernels/src/device.h` line 74 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tO7HSDR2Jnhz1sTN-:-O6WyKBU1RPLZ-PxW415:bqzw9hv) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/kernels/src/device.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Was getting a linker error, but I realized it was for a different reason. This is removed and fixed in `cuda_helper.cu`
___
*[`lib/local-execution/include/local-execution/model_training_instance.struct.toml` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tP3e59eOObHjKBHcc:-O6X-QdrE9ude3CIqsBx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/model_training_instance.struct.toml#L15)):*
> ```TOML
>   "pcg/tensor_guid_t.dtg.h",
>   "pcg/optimizer_attrs.dtg.h",
> ]
> ```

Done.
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 16 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPeMI82zPuwdgLYVS:-O6X2NRe4FwPmGzyGrgV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Some parameter names would be helpful here
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 22 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPhHn1UFI9HaX1U71:-O6X2NhF1YQw-fayscHI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Some parameter names would be helpful here
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/optimizer.h` line 29 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tP_jC2dfiRp-_620H:-O6X2NvKDOhp3kMsPQ8P:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/optimizer.h#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Some parameter names would be helpful here
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 22 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPtFGDeFJl3O4HHG8:-O6X36s5Crfy4yKRkJOI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would these be better renamed `InitOpTaskImplFunction` and `FwdBwdOpTaskImplFunction`, or do they make sense outside of a op context?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature.h` line 4 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQGAN4PHQtElhuzCN:-O6X3S-iCyCSZL74672h:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature.h` line 41 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQLqe88gLBsJDXqtr:-O6X3_dvBK09dxKF3edy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.h#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change to proper doxygen docstring?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature.h` line 49 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQO8R2KBtV7r20aS-:-O6X3_wSBUEOwv89By3_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.h#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change to proper doxygen docstring?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature.struct.toml` line 5 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQarx91gFQDJBTGJa:-O6X3wSe1shFKAwyVPlE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.struct.toml#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not `"hash"`?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature.struct.toml` line 10 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQgOY7_2YEd5WKLAr:-O6X4HO7ERfcqR4r_N7J:bvhh12z) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.struct.toml#L10)):*
> ```TOML
> includes = [
>   "local-execution/tensor_guid_slot_spec.dtg.h",
>   "utils/type_index.h",
> ```

This is fine, but I have to move the deleted part to the `src_includes` since the fmt is defined in that file
___
*[`lib/local-execution/include/local-execution/task_signature.struct.toml` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQYI_2BC5NAby2gTC:-O6X5fKfAQAyEnXVhV0U:bvhh12z) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.struct.toml#L12)):*
> ```TOML
>   "utils/type_index.h",
>   "utils/optional.h"
> ]
> ```

This is fine, but I have to move the deleted part to the `src_includes` since the fmt is defined in that file
___
*[`lib/local-execution/src/local_slots_backing.cc` line 63 at r3](https://reviewable.io/r [...]

2024-09-13 17:29 UTC, lockshaw requested changes
> Reviewed 49 of 49 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: all files reviewed, 24 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/CMakeLists.txt` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Klnft4GZwRRO1GgUo:-O6gOPdFDu60FI731Zfu:bcqsjck) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/CMakeLists.txt#L10)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

There are a couple of files in that folder that haven't been refactored/don't build: `metrics_kernels.cu` and `embedding_kernels.cu`. I think maybe Dylan was going to tackle those?
</blockquote></details>

Sounds good, tracked in https://github.com/flexflow/FlexFlow/issues/1502 and hopefully will get addressed in a week or two once @oOTigger gets back
___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Km3dF88yOXI6nT545:-O6gPFz8BSdf5BJ270BG:b9hc3d) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's called like this in `concat_kernels.cu`:
`blk_size = shape.sub_shape(legion_dim_t{0}, axis).num_elements();` where `axis` is an `ff_dim_t`

I've left it as not implemented for now because I thought it was weird too.
</blockquote></details>

Probably better to instead use the function that converts between an `ff_dim_t` and a `legion_dim_t` using the number of tensor dims (which iirc was defined...somewhere, maybe in kernels where the `LegionDimOrdered` alias is defined?) and then just use the `sub_shape(legion_dim_t, legion_dim_t)` overload
___
*[`lib/local-execution/include/local-execution/task_signature.struct.toml` line 10 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQgOY7_2YEd5WKLAr:-O6gLdaO3mwf7vopoMJj:b-h02nsu) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.struct.toml#L10)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

This is fine, but I have to move the deleted part to the `src_includes` since the fmt is defined in that file
</blockquote></details>

That's good, the more things we can put in `src_includes` instead of `includes` the better for build times as things in `src_includes` won't get propagated through `#include`s as they're only in the `.dtg.cc` file and not the `.dtg.h` file
___
*[`lib/local-execution/src/local_slots_backing.cc` line 132 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tUoJ95kzqmaRpQdAa:-O6gM64z29cJ5qE6wFGr:bxx8pp1) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L132)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

This is the support I had previously for getting the right weight tensor. But this will be superceded by the new weights/inputs reps PR so this will get removed.
</blockquote></details>

So is the plan to merge this and then have a separate PR with the fixed representation, or to replace this PR with a new fixed PR, or something else entirely? Just so I know the context in which to review this PR
___
*[`lib/local-execution/src/local_slots_backing.cc` line 189 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tVGce3Z-QYfDU6CJ2:-O6gNDei33iSJNT4l8I4:b-k4zzjd) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L189)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

That's right. Fixed. Didn't even know that existed.
</blockquote></details>

:slightly_smiling_face: 
___
*[`lib/local-execution/src/local_slots_backing.cc` line 157 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O6gN0Nw5QACMtapyKMi:-O6gN0Nw5QACMtapyKMj:b-xeggua) ([raw file](https://github.com/flexflow/FlexFlow/blob/103ef073a4eedd0108ac6537541d5e4d2f6a03d9/lib/local-execution/src/local_slots_backing.cc#L157)):*
> ```cpp
> ArgSlotsBacking LocalSlotsBacking::construct_arg_slots_backing(
>     OpTaskBinding const &binding, layer_guid_t const &op_guid) const {
>   return map_values(binding.get_arg_bindings(), [&](auto const &arg_binding) {
> ```

Prefer explicit type names over auto



_Suggestion:_
```cpp
  return map_values(binding.get_arg_bindings(), [&](TaskArgSpec const &task_arg_spec) {
```
___
*[`lib/local-execution/src/local_slots_backing.cc` line 171 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O6gMyv-BqqNpBRDlcrt:-O6gMyv-BqqNpBRDlcru:b-xeggua) ([raw file](https://github.com/flexflow/FlexFlow/blob/103ef073a4eedd0108ac6537541d5e4d2f6a03d9/lib/local-execution/src/local_slots_backing.cc#L171)):*
> ```cpp
> ArgSlotsBacking LocalSlotsBacking::construct_arg_slots_backing(
>     TaskBinding const &binding) const {
>   return map_values(binding.get_arg_bindings(), [&](auto const &arg_binding) {
> ```

Prefer explicit type names over auto



_Suggestion:_
```cpp
  return map_values(binding.get_arg_bindings(), [&](TaskArgSpec const &task_arg_spec) {
```
___
*[`lib/local-execution/src/loss_functions.cc` line 29 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KmOZyEHZJux1dD0xw:-O6gPkxy-98a1IGNTiRV:b-m6x0z) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/loss_functions.cc#L29)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Hmm, fair enough. Feels a bit unintuitive to allow binding to a slot twice, might be better to have a way to define that slot as taking both grad and non-grad? Or have separate slots for the grad and non-grad? Doesn't need to be fixed immediately and I'll leave proposals for an exact solution (or the absence of one) up to you as you're more familiar with the current overall state of this interface than I am, just wanted to bring this up because naively this feels a bit odd (like in a function you can't bind an argument twice--the answer could be that SLOTs aren't exactly equivalent to arguments, or maybe just a wrapper function that adds both the grad and the non-grad to the slot?). Not sure, let me know what you think (and either way probably shouldn't be fixed in this PR)
___
*[`lib/local-execution/src/optimizer.cc` line 127 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KpObN-v6trwu7oV6s:-O6gNXSEE_npmFGliAxl:blxdefb) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/optimizer.cc#L127)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks--I usually tend to reserve the `if (...) { ...; return ...; } ...; return ...;` pattern for cases like error handling etc. where the behavior is more "early termination" or (probably equivalently) where the `else` case is very large
___
*[`lib/local-execution/src/optimizer.cc` line 195 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KpsAvECvHNd-zfwPd:-O6gO0Dx-CCLWufJPyy8:b-j0263k) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/optimizer.cc#L195)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think so? https://pytorch.org/docs/stable/generated/torch.optim.SGD.html uses `momentum_buffer` though I guess buffer itself is broad. I can make  [...]

2024-09-18 00:43 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: 65 of 82 files reviewed, 24 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/CMakeLists.txt` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Klnft4GZwRRO1GgUo:-O7-xqoo5Wt24DfjummL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/CMakeLists.txt#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Sounds good, tracked in https://github.com/flexflow/FlexFlow/issues/1502 and hopefully will get addressed in a week or two once @oOTigger gets back
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Km3dF88yOXI6nT545:-O7-zYN8A_SWO2cRoUww:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to instead use the function that converts between an `ff_dim_t` and a `legion_dim_t` using the number of tensor dims (which iirc was defined...somewhere, maybe in kernels where the `LegionDimOrdered` alias is defined?) and then just use the `sub_shape(legion_dim_t, legion_dim_t)` overload
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tNw0c5BE34XmfEQC8:-O70-aD2AwxfaCqYoaQ1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/kernels/src/array_shape.cc#L59)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can probably be replaced by `slice(DimOrdered, ...)`: https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L9
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_invocation.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQ93M0QZ2yX7ImIQa:-O702Tzw-899YNizQ0gN:b-hlu7qb) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_invocation.h#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can be moved over to `dtgen`
</blockquote></details>

Done. Just added `eq` for now, created an issue for `hash` and `fmt` #1503    
___
*[`lib/local-execution/src/local_slots_backing.cc` line 100 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tRpF-3UlZ1x87MamV:-O706g-O9uhrTfg7aUt8:b-es17er) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Either use `filter` or add a `count_if` function to `containers` or something like it
</blockquote></details>

This will be superceded by pcg input/weight differentiation since then we don't need to count inputs.
___
*[`lib/local-execution/src/local_slots_backing.cc` line 132 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tUoJ95kzqmaRpQdAa:-O706oGNEjYofmTHQ6--:bpz8zsr) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L132)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

So is the plan to merge this and then have a separate PR with the fixed representation, or to replace this PR with a new fixed PR, or something else entirely? Just so I know the context in which to review this PR
</blockquote></details>

Now that PCG input/weight is merged, I can fix in this PR itself.
___
*[`lib/local-execution/src/local_slots_backing.cc` line 157 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O6gN0Nw5QACMtapyKMi:-O707DpH1lTl1DEdhowG:b-szsmwm) ([raw file](https://github.com/flexflow/FlexFlow/blob/103ef073a4eedd0108ac6537541d5e4d2f6a03d9/lib/local-execution/src/local_slots_backing.cc#L157)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit type names over auto
</blockquote></details>

Done. (It's `OpArgSpec` here btw)
___
*[`lib/local-execution/src/local_slots_backing.cc` line 171 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O6gMyv-BqqNpBRDlcrt:-O707FUV8Te1O0hkW80i:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/103ef073a4eedd0108ac6537541d5e4d2f6a03d9/lib/local-execution/src/local_slots_backing.cc#L171)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit type names over auto
</blockquote></details>

Done.
___
*[`lib/local-execution/src/loss_functions.cc` line 29 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KmOZyEHZJux1dD0xw:-O707fqM3c1tlOYykAsq:b-559asg) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/loss_functions.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Hmm, fair enough. Feels a bit unintuitive to allow binding to a slot twice, might be better to have a way to define that slot as taking both grad and non-grad? Or have separate slots for the grad and non-grad? Doesn't need to be fixed immediately and I'll leave proposals for an exact solution (or the absence of one) up to you as you're more familiar with the current overall state of this interface than I am, just wanted to bring this up because naively this feels a bit odd (like in a function you can't bind an argument twice--the answer could be that SLOTs aren't exactly equivalent to arguments, or maybe just a wrapper function that adds both the grad and the non-grad to the slot?). Not sure, let me know what you think (and either way probably shouldn't be fixed in this PR)
</blockquote></details>

Functionally, a slot = a tensor, so I think it's ok to refer to multiple slots with the same name (the name is just a concept) as long as they have different specifications (e.g. grad and non-grad). Sometimes you don't want the grad version, so I don't think the wrapper function would be too helpful. I actually think the current interface is the most clear. 
___
*[`lib/local-execution/src/loss_functions.cc` line 64 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KnWjQ0SCN8VN61j67:-O709TD57IbxDlt8jPAv:bd1hpz8) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/loss_functions.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Label shape is an `ArrayShape`, so it shouldn't have any parallel dims, right?
</blockquote></details>

I think you're right, yes. 
___
*[`lib/local-execution/include/local-execution/loss_functions.h` line 29 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tOfkp-mrVQCz5-JU8:-O70-h2vBFV62R3foByB:bb77ufg) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/loss_functions.h#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You mean `parallel_tensor_guid_t`?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2024-10-01 20:10 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: 54 of 83 files reviewed, 24 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tOZlXCFnNU2oTmOP9:-O88ZK5OCYgavcvON4-q:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/local_training_backing.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this passed as mutable?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/model_training_instance.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPF__E9sgILo_ph_w:-O88UoAP2Vi-w_j6Zhyq:b-be8ipu) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/model_training_instance.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why isn't the model part of `ModelTrainingInstance`? The members seem to have changed non-trivially since the old version:
```
struct ModelTrainingInstance {
  ComputationGraph computation_graph;
  Optimizer optimizer;
  EnableProfiling enable_profiling;
  TrainingPCG training_pcg;
  TensorMapping tensor_map;
  LegionBacking legion_backing;
};
```
</blockquote></details>

It's been kind of reversed and disaggregated. You can think of the backing itself as the driver and the training instance as just the fields necessary for training (logit, label, loss, optimizer). This makes it a lot easier to test. 
___
*[`lib/local-execution/include/local-execution/task_signature.struct.toml` line 29 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQt5iDABZCo6K0Vzi:-O88OAzODO4eDRt4fQvM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_signature.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not a map of `slot_id_t -> something`?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tR4aD7i5LFASdtM13:-O88JyxE2278tqMvBv1O:bp1ogoz) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This name seems a bit ambiguous? Maybe something clearer?
</blockquote></details>

Hm, but it is literally a specification for a tensor. Like the tensor_guid and the grad will tell you exactly which tensor to access.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 80 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tRPb87IES0BBoeERQ:-O88V_LH-aYGTIePO6Rp:b-671af1) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_cost_estimator.cc#L80)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would it make more sense to disaggregate `LocalTrainingBacking` rather than having an `optional` field for the training instance?
</blockquote></details>

I was thinking about this, but to me it makes sense to have the training backing be the driver and then the optional instance provides fields that are only necessary for training. For example, when I'm testing the local cost estimator, I don't need the loss/optimizer stuff. 
___
*[`lib/local-execution/src/local_slots_backing.cc` line 61 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tRaKs27RZNDnlUakf:-O88ErWt5WEJnlUQ42lK:b-se4q3z) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not a fan of this, come up with some new tensor id type
</blockquote></details>

Done. It's now a `non_graph_tensor_guid_t` and not handled by the computation graph
___
*[`lib/local-execution/src/local_slots_backing.cc` line 100 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tRpF-3UlZ1x87MamV:-O88B5ngBDTlxngSdgRy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L100)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

This will be superceded by pcg input/weight differentiation since then we don't need to count inputs.
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_slots_backing.cc` line 132 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tUoJ95kzqmaRpQdAa:-O88BpIcCDnYYCU2zeh4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_slots_backing.cc#L132)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Now that PCG input/weight is merged, I can fix in this PR itself.
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 165 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tWE5s-ebLqQo4M77f:-O88GAS3D7IGiISk4Z8C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_training_backing.cc#L165)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not key this by the `layer_guid_t` of the `WeightAttrs`?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 179 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tWzmPEb8K2ujCJibH:-O88ZKmZ7ReSqMet0CuU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_training_backing.cc#L179)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not convinced that the `next()` abstraction is the cleanest way to handle this? Idk, the `ModelTrainingInstance` changing during training is a bit conceptually weird. I don't have a super clear alternative idea, but I suppose it would be something along the lines of moving the mutable aspects (I think in this case some optimizer state?) into some other data structure so that `ModelTrainingInstance` stays the same
</blockquote></details>

Done.
___
*[`lib/local-execution/src/model_training_instance.cc` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Ko1Xw1OkWzl0GNyMz:-O88YG7V48Y_iDlAhDU3:b52dkyd) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/model_training_instance.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should probably get pulled out of the function at least. Also, does it make sense to actually modifying the `ModelTrainingInstance` or would we want a separate optimizer state object/field to hold these mutable values?
</blockquote></details>

Done. Now, `next` only changes the optimizer attrs.
___
*[`lib/local-execution/src/model_training_instance.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5KoITxDaEbaL6RPCXc:-O88YDSq4gAaLlqrPovi:bthl5ej) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/local-execution/src/model_training_instance.cc#L26)):*
<details><summary><i>Previously, reyna-abhyankar (Rey [...]

2024-10-09 22:48 UTC, lockshaw requested changes
> Reviewed 7 of 17 files at r5, 7 of 16 files at r6, 31 of 33 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1472)* status: all files reviewed, 14 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5Km3dF88yOXI6nT545:-O8nKAKc2U5vA9dVbja0:b-uuiyjm) ([raw file](https://github.com/flexflow/FlexFlow/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The signature (`sub_shape(legion_dim_t, ff_dim_t)`) still appears the same?
___
*[`lib/kernels/include/kernels/array_shape.h` line 20 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8nKIb62m5s1mN6xCJe:-O8nKIb62m5s1mN6xCJf:b-wscqfp) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/kernels/include/kernels/array_shape.h#L20)):*
> ```objc
>   ArrayShape(TensorShape const &shape);
>   ArrayShape(std::vector<std::size_t> const &);
>   ArrayShape(LegionTensorDims const &);
> ```

Ideally these should be `explicit`: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-explicit



_Code quote:_
```objc
  ArrayShape(size_t *dims, size_t num_dims);
  ArrayShape(TensorShape const &shape);
  ArrayShape(std::vector<std::size_t> const &);
  ArrayShape(LegionTensorDims const &);
```
___
*[`lib/kernels/src/array_shape.cc` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tNw0c5BE34XmfEQC8:-O8nKbvy5mccwqQa_tTB:b-q2c1mk) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/kernels/src/array_shape.cc#L59)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Would it make more sense to just convert `start` and `end` to `legion_dim_t`?
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 43 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8ma9DJBp9ejqaQkx_W:-O8ma9DJBp9ejqaQkx_X:bmhl5m6) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/include/local-execution/local_training_backing.h#L43)):*
> ```objc
>   LocalSlotsBacking local_slots_backing;
>   std::optional<ModelTrainingInstance> training_instance;
>   std::optional<OptimizerAttrs> optimizer_attrs;
> ```

Having so many optional parameters that affect execution semantics makes me wonder if `LocalTrainingBacking` (or related abstractions) should be broken up--you could have a user-facing interface that's still along the lines of `execute_forward`, `execute_backward`, `execute_update`, but then have each of those conditionally execute lower-level functions `execute_loss`, etc. that don't use `optional`
___
*[`lib/local-execution/include/local-execution/model_training_instance.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tPF__E9sgILo_ph_w:-O8nNqVs4YQSTKa3tWCx:b-jmmt63) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/model_training_instance.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's been kind of reversed and disaggregated. You can think of the backing itself as the driver and the training instance as just the fields necessary for training (logit, label, loss, optimizer). This makes it a lot easier to test.
</blockquote></details>

That makes sense. In that case what's the point of having `ModelTrainingInstance` at all? I'm not against having it, I'm just not sure semantically what it represents in the current code.
___
*[`lib/local-execution/include/local-execution/task_binding.h` line 13 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8nLMTY2HCzE7_PmUB9:-O8nLMTY2HCzE7_PmUBA:bx1492n) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/include/local-execution/task_binding.h#L13)):*
> ```objc
> namespace FlexFlow {
> 
> struct TaskBinding {
> ```

Add support for hashing and `fmt`ing?
___
*[`lib/local-execution/include/local-execution/task_invocation.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tQ93M0QZ2yX7ImIQa:-O88y6XpCoP2jwu-zeKG:b-y4t6i8) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/task_invocation.h#L65)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Just added `eq` for now, created an issue for `hash` and `fmt` #1503
</blockquote></details>

What's the issue with them? Isn't it as simple as just changing from `features = ["eq"]` to `features = ["eq", "hash", "fmt"]`?
___
*[`lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tR4aD7i5LFASdtM13:-O8nHbwQ3cNFiX2PeBFz:bd5rpd8) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Hm, but it is literally a specification for a tensor. Like the tensor_guid and the grad will tell you exactly which tensor to access.
</blockquote></details>

I guess the concern is "tensor" is a bit overloaded--like "tensor_guid_t" represents just a forward tensor in the computation graph, but then other uses of "tensor" elsewhere are much broader. It might be nice to come up with some naming convention for these different concepts of what a "tensor" is to reduce ambiguity
___
*[`lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml` line 18 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8nHQ_eE4v3b5YdB11X:-O8nHQ_eE4v3b5YdB11Y:byrenpo) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/include/local-execution/tensor_guid_spec.struct.toml#L18)):*
> ```TOML
> [[fields]]
> name = "tensor_guid"
> type = "::FlexFlow::UnifiedTensorGuid"
> ```

Does it make sense for `non_graph_tensor_guid_t`s to have a gradient tensor?
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 80 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O5tRPb87IES0BBoeERQ:-O8nI-_hCRZvjeHOTwJC:b-vpid65) ([raw file](https://github.com/flexflow/FlexFlow/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/src/local_cost_estimator.cc#L80)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I was thinking about this, but to me it makes sense to have the training backing be the driver and then the optional instance provides fields that are only necessary for training. For example, when I'm testing the local cost estimator, I don't need the loss/optimizer stuff.
</blockquote></details>

I'm not really arguing for making them non-`optional` fields, but potentially disaggregating `LocalTrainingBackend` (or its composite fields) so that the semantics of `LocalTrainingBackend` are clearer (note the high-level interface could be the same, but the core logic would be in separate pieces that are tested separately). Similar things were done in old-FlexFlow (e.g., tensors had a whole bunch of fields, and for most computations only a subset were really needed. The logic was that if you were testing a certain feature that you could only initialize the fields that were necessary, but that made it really hard to reason about the code as it meant that given a tensor you were never sure wha [...]

2024-12-19 06:29 UTC, lockshaw requested changes
> Reviewed 21 of 36 files at r8, 81 of 92 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1472)* status: 134 of 149 files reviewed, 36 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O5Km3dF88yOXI6nT545:-O9qDS6J9upY0ZHkNO5i:b2nhswy) ([raw file](https://github.com/flexflow/flexflow-train/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Oh, did you mean we should not have this at all and instead the calling code should call `sub_shape(legion_dim_t, legion_dim_t)`?
</blockquote></details>

Yes
___
*[`lib/local-execution/src/local_training_backing.cc` line 130 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O8nGxOQBQbphnmK4wmJ:-OES_wP52TrAMXFrct4e:b-wd9eit) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/src/local_training_backing.cc#L130)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Currently a todo #1442 . It should be uncommented but the underlying function is `NOT_IMPLEMENTED()`
</blockquote></details>

Can you add a link to that TODO in the code, just in case anyone else is unsure when they come across this?
___
*[`lib/local-execution/src/local_training_backing.cc` line 172 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O8nHBU28h4Qq_jB6jCa:-OESa6-472A4s3amFWgE:b-wd9eit) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/src/local_training_backing.cc#L172)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8nGxOQBQbphnmK4wmJ
</blockquote></details>

Can you add a link to that TODO in the code, just in case anyone else is unsure when they come across this?
___
*[`lib/local-execution/test/src/test_loss_e2e.cc` line 45 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O5tZe9t2K_AvSQBCzOY:-OESaJjLBi7sX6YcCZiV:bvbntyo) ([raw file](https://github.com/flexflow/flexflow-train/blob/dde9496ada1c18ece558d9ac1b9bb38fbc147417/lib/local-execution/test/src/test_loss_e2e.cc#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/flexflow/FlexFlow/1472#-O8ma9DJBp9ejqaQkx_W for the splitting out. For loss functions, it really is just a sanity test to make sure things run. The reason there's different subcases are because the actual loss function op code/kernel has conditional logic based on which loss attrs we're dealing with. But the backing is agnostic to this. So yes we could have just 1 test for loss functions in general but I just wanted to sanity check.
</blockquote></details>

Can you hold this as "Working" while we resolve https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUtvlCsQMPCJ492-X? 
___
*[`lib/pcg/include/pcg/optimizer_attrs.h` line 9 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O8nJnqU0giXq9WlaK_O:-O9qLDLu1MwVx79ugCVj:bxnnluj) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/pcg/include/pcg/optimizer_attrs.h#L9)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

How about `get_next_iteration_optimizer_attrs`?
</blockquote></details>

Sounds great. Could also do `get_optimizer_attrs_for_next_iteration` if you prefer, either is fine with me
___
*[`lib/kernels/include/kernels/legion_dim.h` line 13 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERa9f80mFTXkuRFAvu:-OERa9f80mFTXkuRFAvv:bua019o) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/kernels/include/kernels/legion_dim.h#L13)):*
> ```objc
> legion_dim_t legion_dim_from_ff_dim(ff_dim_t, int num_dimensions);
> 
> std::optional<legion_dim_t> legion_dim_from_ff_dim(std::optional<ff_dim_t>,
> ```

Probably should just use `transform` from containers rather than having a whole extra specialization for this.
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 25 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUtvlCsQMPCJ492-X:-OESUtvlCsQMPCJ492-Y:bx38k8) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L25)):*
> ```objc
>     std::unordered_map<reduced_tensor_t, GenericTensorAccessorW>;
> 
> struct LocalSlotsBacking {
> ```

This object is getting rather large in terms of methods, it would be nice to factor some of them out into separate functions, even if that means some explicit argument passing is necessary (might even be an advantage, because right now it's hard to tell what these methods do because they access so much)--wasn't this going to be solved by adding an explicit lowering phase so that `LocalSlotsBacking` isn't responsible for any thing `OpTask*` and thus only has to handle `Task*` objects?
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 36 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUbeiB2q4LQ13X3SW:-OESUbeiB2q4LQ13X3SX:b-l0i1c1) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L36)):*
> ```objc
>                               ComputationGraph const &,
>                               Allocator &);
>   void allocate_tensors_by_role(TensorRole const &,
> ```

Why is this new API necessary?
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 49 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUVL-8VQ6sDp973mp:-OESUVL07olYxPpm7J6O:b-is42yu) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L49)):*
> ```objc
>   TensorSlotsBacking
>       construct_tensor_slots_backing(TaskBinding const &,
>                                      std::optional<layer_guid_t> const &) const;
> ```

Why does this need a `layer_guid_t`?
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 59 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUioU-1ppr4ClgZNs:-OESUioU-1ppr4ClgZNt:b-x1vnkh) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L59)):*
> ```objc
> 
>   GenericTensorAccessorW const &
>       get_tensor_backing(TensorType const &,
> ```

Why does this function care about the `TensorType`--shouldn't the `reduced_tensor_t` by itself be unambiguous?



_Code quote:_
```objc
      get_tensor_backing(TensorType const &,
```
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 61 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUgH08NRmwS9L0BKb:-OESUgH1DR2HIExyM_mk:b-o67wye) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L61)):*
> ```objc
>       get_tensor_backing(TensorType const &,
>                          reduced_tensor_t const &,
>                          std::optional<layer_guid_t> const &) const;
> ```

Why is a `layer_guid_t` necessary here?
___
*[`lib/local-execution/include/local-execution/layer_tensor_key.struct.toml` line 2 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/147 [...]

2025-01-07 23:15 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1472)* status: 134 of 149 files reviewed, 35 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/array_shape.h` line 45 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O5Km3dF88yOXI6nT545:-OG1S56wCLEQtjtam2L-:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/1ddfadeebdcdcdabe8a84a03ec51fb5bcb02bfd4/lib/kernels/include/kernels/array_shape.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/legion_dim.h` line 13 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERa9f80mFTXkuRFAvu:-OG1USs3-Yj2lj3FquOw:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/kernels/include/kernels/legion_dim.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably should just use `transform` from containers rather than having a whole extra specialization for this.
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/arg_ref.h` line 72 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERaUS89rT_4TMYQYy-:-OG1qYVR3FtTZgRlumqD:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/cf96db6c069b812dac3537f145e68e254596fa7e/lib/local-execution/include/local-execution/arg_ref.h#L72)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove `ref_type`? That seems like an important field?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/concrete_arg.h` line 49 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERagLs5DDN71lK2Zqz:-OG1r6zY-thySMsQ0TRh:b66wt2w) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/concrete_arg.h#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does `tie` not include the `ptr`?
</blockquote></details>

In tests, I check for equality for two `ConcreteArgSpec` but they are `::create`d separately so they have different pointers for the underlying value.
___
*[`lib/local-execution/include/local-execution/concrete_arg.h` line 63 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERa_D5CY3kwclBbkOz:-OG1t8ZT1H4GOhSVJXEY:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/concrete_arg.h#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not include `ptr` in the hash?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 36 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUbeiB2q4LQ13X3SW:-OG1tC4-ARMqETc5OKQR:bpo7occ) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this new API necessary?
</blockquote></details>

It made it a lot easier to test whether different were being allocated correctly.
___
*[`lib/local-execution/include/local-execution/runtime_arg_ref.h` line 30 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERbthi8g8iKduZykME:-OG1yJnP4uSOTtF0hUGj:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/runtime_arg_ref.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_binding.h` line 10 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESTVKsB0T9DWpPiw3h:-OG1yTXG0svsHn4Nudny:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/task_binding.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file along with hash definition
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_binding.h` line 66 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESTRWU5igCzzCVZb8l:-OG1yVhSEYyAePabWVYM:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/task_binding.h#L66)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move definition to `.cc` file
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 84 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESYCqk2J9Rz6BR6Y4o:-OG1zoZw7l7IhIPe0RXB:b-sq8qil) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/src/local_cost_estimator.cc#L84)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we have a separate API for registering layers? Is there a time when we want a `LocalTrainingBacking` that doesn't have its layers registered?
</blockquote></details>

This is useful when testing. We can initialize the backing object and then register different layers in different subcases
___
*[`lib/local-execution/src/local_training_backing.cc` line 130 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O8nGxOQBQbphnmK4wmJ:-OG2-5Sg4ZSQ2zGV-Fvn:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/src/local_training_backing.cc#L130)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add a link to that TODO in the code, just in case anyone else is unsure when they come across this?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 172 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-O8nHBU28h4Qq_jB6jCa:-OG2-6SK7wsYEAKlg5cO:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/1d3cc9498fb5afe5e9f1b0aa1e50260a58e1c424/lib/local-execution/src/local_training_backing.cc#L172)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add a link to that TODO in the code, just in case anyone else is unsure when they come across this?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/attention.cc` line  at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERcKm929rsm8Fy9XuE:-OG20KyWA52U1sCp0AUK:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/src/ops/attention.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

FYI these should be moved to `lib/local-execution/src/local-execution/ops/attention.cc` to match the standard directory layout
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/operator_attrs.h` line 4 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESZpauBvDE1GIKb_U7:-OG20UbrE9a1XSei5W9K:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/op-attrs/include/op-attrs/operator_attrs.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These shouldn't be in `op-attrs`--typo?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local- [...]

2025-01-15 21:02 UTC, lockshaw reviewed
> Reviewed 5 of 56 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1472)* status: 94 of 151 files reviewed, 31 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2025-01-17 01:04 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1472)* status: 94 of 151 files reviewed, 31 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/layer_tensor_key.struct.toml` line 2 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESRcxlCaq1uHj2MERq:-OGlfCu87esK3VHIVvDS:bss4a2b) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/layer_tensor_key.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is the purpose of `LayerTensorKey`? I see that it's used in `LocalSlotsBacking`, but I'm not clear on why every it needs to be keyed by both `layer_guid_t` *and* `reduced_tensor_t` rather than just by `reduced_tensor_t`--why is the `layer_guid_t` necessary?
</blockquote></details>

Removed.
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 25 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUtvlCsQMPCJ492-X:-OGlfFJD3HAR43tb0VU7:bb7tmf0) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This object is getting rather large in terms of methods, it would be nice to factor some of them out into separate functions, even if that means some explicit argument passing is necessary (might even be an advantage, because right now it's hard to tell what these methods do because they access so much)--wasn't this going to be solved by adding an explicit lowering phase so that `LocalSlotsBacking` isn't responsible for any thing `OpTask*` and thus only has to handle `Task*` objects?
</blockquote></details>

Done. It's now only doing `Task*` and I've also split this out into `LocalArgsBacking` and `LocalTensorBacking`
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 49 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUVL-8VQ6sDp973mp:-OGlg9_R8CnPaYqO-_jF:bss4a2b) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this need a `layer_guid_t`?
</blockquote></details>

Removed.
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 59 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUioU-1ppr4ClgZNs:-OGlgArPCQUhmRUEzMmG:ba3dfob) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L59)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this function care about the `TensorType`--shouldn't the `reduced_tensor_t` by itself be unambiguous?
</blockquote></details>

Removed
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 61 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESUgH08NRmwS9L0BKb:-OGlkPSTABI6oJZFM5o2:ba3dfob) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_slots_backing.h#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is a `layer_guid_t` necessary here?
</blockquote></details>

Removed
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 26 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESVW2AC9ed7wRw3_Fo:-OGf891E7UOztrs6UEQB:bugxkcz) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I know I've mentioned this before (so sorry for bringing it up again, but I appear to have forgotten the previous response) but why have a slot represent any of a number of tensors (forward, gradient, optimizer, etc.) rather than just having a slot represent a single tensor? Is it that it makes backward inference more difficult? Conceptually feels weird, as it makes it a bit confusing who actually determines what gets communicated to a task
</blockquote></details>

I'm not quite sure what you mean? The slot does represent a single tensor. 
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 37 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESX-R-9dhy7vM50Qni:-OGlkm6n-pYVlGxNDhJl:b-845sd3) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/local_training_backing.h#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are these on `LocalTrainingBacking` instead of `LocalSlotsBacking`? They feel lower-level than the other methods present here (i.e., `execute_init`, `execute_forward`, etc. all require arg accessors to function, so it feels odd that it's at the same level of API)
</blockquote></details>

I've split slots into tensor and args. both are owned by training backing, so I feel like getting the accessor is still fine at this level
___
*[`lib/local-execution/include/local-execution/model_training_instance.h` line 10 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERdu3b4vEbXX_DY976:-OGll-uX71f3AZfHjWLr:bsojsn4) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/model_training_instance.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be nice to eventually convert this `float` to a wrapper type with, e.g., non-negativity checks, could be named like `milliseconds_t` or whatever the unit is (also to make the unit clear) along the lines of #1533
</blockquote></details>

Now that this is merged into main, I'll integrate when i merge main into this branch
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 87 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERf0aP7vAbcFRwcjya:-OGllPpK3NoYDwk9aY7-:b-3i1606) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/op_task_invocation.h#L87)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is it necessary for `OpTaskInvocation` to deal with anything other than grad and non-grad tensors? Seems like `SlotGradId` as the more accurate datatype for here, but maybe there's a case I'm not thinking about
</blockquote></details>

Reverted. 
___
*[`lib/local-execution/include/local-execution/reduced_tensor_t.struct.toml` line 2 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERbk9A-XE_B1lpbq9Y:-OGllSEXAH2KG7uyJwci:bhpecso) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/include/local-execution/reduced_tensor_t.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does this represent? It probably needs a new name as "reduced" is a bit overloaded (i.e., the reduction operation)
</blockquote></details>

Changed to `lowered` it is the form that local slots backing will reason over
___
*[`lib/local-execution/include/local-execution/tensor_type.enum.toml` line 11 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OERc6Ax [...]

2025-02-01 03:38 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1472)* status: 68 of 180 files reviewed, 31 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/src/local_cost_estimator.cc` line 29 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESXtfP4f4bslzAf642:-OHzZMm-8Qb3dZyx5cOa:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/src/local_cost_estimator.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any way we could factor out pieces of this function? A bunch of these blocks seem conceptually self-contained and this function is getting rather large
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 51 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESZB9a1Rty9W-kfCAs:-OHzZNK42GtjsQBZq5Wy:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/local-execution/src/local_cost_estimator.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I feel like you probably just want the raw `ComputationGraph` interface (i.e., `computation_graph.h`) here, `ComputationGraphBuilder` is really intended to provide a lots-of-stuff-auto-inferred pytorch-style interface for constructing models, which you're not really using here
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 260 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OESST5CBYa86NvlFJK-:-OHzZQBe0jfU1ZTljO_c:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/pcg/include/pcg/computation_graph_builder.h#L260)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just use `add_layer` from `computation_graph.h` (https://github.com/flexflow/flexflow-train/blob/93298eda084436781c87ad9b7b506613b71526d9/lib/pcg/include/pcg/computation_graph.h#L18-L21)?  Feels unnecessary and a bit too low-level for the rest of the API to put this on `ComputationGraphBuilder`
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h` line 183 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1472#-OES_2p_7FORLEJg0fjB:-OHzZl8s-MrzbuvGDp7e:b28lcac) ([raw file](https://github.com/flexflow/flexflow-train/blob/c6fed294c5b31001f978123c43681c0db32b3e0b/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h#L183)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this changed to be non-static? If it has to be non-static it shouldn't be here (it should probably be in either `parallel_tensor_attrs.h` or `parallel_tensor_shape.h`)
</blockquote></details>

Done. (no longer static)


<!-- Sent from Reviewable.io -->

2025-07-12 23:09 UTC, merged