Graph Library
flexflow/flexflow-train pull request #1521
Opened 2024-10-10 04:25 UTC by Marsella8

**Description of changes:**

Extending testing functionality for graph library
Bug fixing
General clean up

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-12-19 19:56 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/utils/src/utils/graph/series_parallel/series_parallel_decomposition.cc` line 82 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEVUP-Q0igHGxAIU_JJ:-OEVUP-Q0igHGxAIU_JK:bgr32cp) ([raw file](https://github.com/flexflow/flexflow-train/blob/8564b8b979419ced5a67774c89777d380061e300/lib/utils/src/utils/graph/series_parallel/series_parallel_decomposition.cc#L82)):*
> ```cpp
> }
> 
> bool is_empty(Node const &node) {
> ```

borrowed from #1562, will fix them there if needed  


<!-- Sent from Reviewable.io -->

2025-01-10 03:13 UTC, lockshaw requested changes
> Reviewed 23 of 32 files at r1, 12 of 16 files at r2, 7 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: 42 of 47 files reviewed, 35 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/test/src/utils/graph/undirected/algorithms/get_connected_components.cc` line 10 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEcd9nEByqEroFX6J_o:-OEcd9nEByqEroFX6J_p:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/undirected/algorithms/get_connected_components.cc#L10)):*
> ```cpp
> using namespace FlexFlow;
> 
> TEST_CASE("get_connected_components") {
> ```





_Suggestion:_
```cpp
TEST_SUITE(FF_TEST_SUITE) {
  TEST_CASE("get_connected_components") {
```
___
*[`lib/utils/test/src/utils/graph/undirected/algorithms/get_connected_components.cc` line 41 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEcdVEk7iZmu4kCWft5:-OEcdVEk7iZmu4kCWft6:b99r5kz) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/undirected/algorithms/get_connected_components.cc#L41)):*
> ```cpp
>   }
> 
>   SUBCASE("3 components") {
> ```

Also test the case where everything is one component

Also test the case where the graph is empty
___
*[`lib/utils/test/src/utils/graph/digraph/algorithms/get_dominators.cc` line 34 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD4aXK36xcK-PmQS3n:-OGD4aXK36xcK-PmQS3o:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/digraph/algorithms/get_dominators.cc#L34)):*
> ```cpp
>       std::unordered_set<Node> correct = {n.at(0)};
>       CHECK(correct == result);
>     }
> ```





_Suggestion:_
```cpp
    SUBCASE("small acyclic graph") {
      std::vector<Node> n = add_nodes(g, 4);
      std::vector<DirectedEdge> e = {
          DirectedEdge{n.at(0), n.at(3)},
          DirectedEdge{n.at(0), n.at(1)},
          DirectedEdge{n.at(0), n.at(2)},
          DirectedEdge{n.at(1), n.at(2)},
      };
      add_edges(g, e);

      SUBCASE("get_dominators(..., Node const &)") {
        Node node = n.at(2);
        std::unordered_set<Node> correct = {n.at(0), n.at(2)};
        std::unordered_set<Node> result = get_dominators(g, node);
        CHECK(correct == result);
      }
  
      SUBCASE("get_dominators(..., std::unordered_set<Node> const &)") {
        std::unordered_set<Node> nodes = {n.at(1), n.at(3)};
        std::unordered_set<Node> result = get_dominators(g, nodes);
        std::unordered_set<Node> correct = {n.at(0)};
        CHECK(correct == result);
      }
    }
```
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 20 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD7mCl0y6oka-VVpqz:-OGD7mCl0y6oka-VVpr-:b-k4p758) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L20)):*
> ```objc
> std::unordered_multiset<Node> get_nodes(Node const &);
> 
> bool is_empty(Node const &node);
> ```

How would you end up with an empty SP decomposition? That doesn't seem like it should be allowed (i.e., might be a good idea to change the container in the splits to be some wrapper type of `std::vector` that requires itself to be non-empty)
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 28 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD807R63zAOqRhCRl-:-OGD807S64epYixcTCoo:bu6z755) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L28)):*
> ```objc
> 
> SeriesParallelDecomposition delete_node(SeriesParallelDecomposition sp,
>                                         Node const &node);
> ```

How is this a well-behaved operation? Like, what are the semantics of this? Are you sure we want this function as part of the API for `SeriesParallelDecomposition`?



_Code quote:_
```objc
SeriesParallelDecomposition delete_node(SeriesParallelDecomposition sp,
                                        Node const &node);
```
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 30 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8ENb17_mzbhBIcJP:-OGD8ENb17_mzbhBIcJQ:bdg1yyg) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L30)):*
> ```objc
>                                         Node const &node);
> 
> // duplicate nodes within `sp` are counted multiple times
> ```

Doxygen style please :slightly_smiling_face: 



_Code quote:_
```objc
// duplicate nodes within `sp` are counted multiple times
```
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 33 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8I5Y61semqBZWvd1:-OGD8I5Y61semqBZWvd2:b-gw0qb0) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L33)):*
> ```objc
> size_t num_nodes(SeriesParallelDecomposition const &sp);
> 
> SeriesParallelDecomposition serial_composition(
> ```

For consistency, never use "serial" in the FF codebase, always use "series"



_Suggestion:_
```objc
SeriesParallelDecomposition series_composition(
```
___
*[`lib/utils/include/utils/graph/series_parallel/series_reduction.h` line 19 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8WYO1U5yR9I8outW:-OGD8WYO1U5yR9I8outX:bf50j7a) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_reduction.h#L19)):*
> ```objc
> 
> std::unordered_set<std::vector<MultiDiEdge>>
>     find_all_extended_series_reductions(MultiDiGraphView const &g);
> ```

What is an "extended series reduction"?  Correct me if I'm wrong here but I don't think this is standard terminology(?) in which case it would be good to have a doxygen docstring here with some explanation

Also, it might be nice to create an actual datatype (e.g., `ExtendedSeriesReduction`) that is a wrapper type around `std::vector<MultiDiEdge>` rather than just using a raw vector. 



_Code quote:_
```objc
    find_all_extended_series_reductions(MultiDiGraphView const &g);
```
___
*[`lib/utils/test/src/utils/graph/undirected/undirected.cc` line 15 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD68134GNCoXjHgL7f:-OGD68145WCAG4eSoC1A:b-8fddex) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/undirected/undirected.cc#L15)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE_TEMPLATE(
> ```

Why are there two tests here?
___
*[`lib/utils/test/src/utils/graph/undirected/undirected.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD6HVV0LfDCxBRJYYx:-OGD6HVV0LfDCxBRJYYy:b-ck8kya) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/undirected/undirected.cc#L18)):*
> ```cpp
>       "UndirectedGraph implementations", T, HashmapUndirectedGraph) {
> 
>     RC_SUBCASE("Full", [&]() {
> ```

Why is this using rapidcheck?
___
*[`lib/utils/src/utils/graph/views/views.cc` line 2 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEccQqg4VyTdUxlG_1_:-OEccQqg4VyTdUxlG_1a:b-uebs2j) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa8 [...]

2025-01-11 23:32 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: 42 of 47 files reviewed, 35 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/node/node.struct.toml` line 9 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD791k-RcBpGC9wF5F:-OGIl9JSAdgPTtw5tMXn:b518mmg) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/node/node.struct.toml#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How are you using a default Arbitrary instance for `Node`? I have no issue adding generators for `Node`, but the default instance seems unlikely to be helpful as `Node` is only meaningful in the context of a graph?
</blockquote></details>

removed, had accidentally added rapidcheck to `UndirectedEdge`
___
*[`lib/utils/include/utils/graph/series_parallel/parallel_reduction.h` line 15 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD9CnD0OZQFYdtpZlL:-OGJ30MW9D7AQKpz2h6k:by5lfus) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/parallel_reduction.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is an "extended parallel reduction"?  Correct me if I'm wrong here but I don't think this is standard terminology(?) in which case it would be good to have a doxygen docstring here with some explanation

Also, it might be nice to create an actual datatype (e.g., `ExtendedParallelReduction`) that is a wrapper type around `std::unordered_set<MultiDiEdge>` rather than just using a raw unordered set

If this is just for accelerating the SP decomposition algorithm's rewriting step, it might be better to put these functions (and the corresponding ones for "extended series reductions" in that file rather than in the general "parallel_reduction.h" header)
</blockquote></details>

Have added docstrings and datatypes. (It's for accelerating the algo by batching multiple reduction steps together).
I've kept the extended reductions there, given that already series and parallel reduction were used solely for the SP decomp algorithm (So now they are not really used anymore, but still probably worth keeping around since they are pretty general functions).
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 20 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD7mCl0y6oka-VVpqz:-OGLipWx3I6-_v8u3lIP:b-2jz8i3) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How would you end up with an empty SP decomposition? That doesn't seem like it should be allowed (i.e., might be a good idea to change the container in the splits to be some wrapper type of `std::vector` that requires itself to be non-empty)
</blockquote></details>

it can emerge in some of the SP-ization algorithms as a temporary artifact, though the final SP decompositions are always normalized (see normalize_sp_decomposition in #1562 ) so it doesn't show up "externally".
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 28 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD807R63zAOqRhCRl-:-OGLjOZt5Q4MQJB9i-lg:bggh2s0) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How is this a well-behaved operation? Like, what are the semantics of this? Are you sure we want this function as part of the API for `SeriesParallelDecomposition`?
</blockquote></details>

I've deleted it (in #1562), it was originally used for making a 2 terminal SP graph into an all-to-all SP graph, by deleting the synchronization nodes.
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 30 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8ENb17_mzbhBIcJP:-OGLjnKo75yxJc-3DbYR:b-oj6cjd) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Doxygen style please :slightly_smiling_face:
</blockquote></details>

fixed in #1562 
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 33 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8I5Y61semqBZWvd1:-OGJAM1M9EZF0dvt_OnO:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For consistency, never use "serial" in the FF codebase, always use "series"
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/series_parallel/series_reduction.h` line 19 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD8WYO1U5yR9I8outW:-OGJAOFM1TnVBxR9-fyQ:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_reduction.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is an "extended series reduction"?  Correct me if I'm wrong here but I don't think this is standard terminology(?) in which case it would be good to have a doxygen docstring here with some explanation

Also, it might be nice to create an actual datatype (e.g., `ExtendedSeriesReduction`) that is a wrapper type around `std::vector<MultiDiEdge>` rather than just using a raw vector.
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/graph/series_parallel/series_reduction.cc` line 79 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGDBlIB6wjfH_gH3AKm:-OGLmI1x2C_Qdc_U52--:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/src/utils/graph/series_parallel/series_reduction.cc#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Newlines please--this is really hard to read
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/graph/views/views.cc` line 2 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEccQqg4VyTdUxlG_1_:-OGJBIzv4zy-jktQ6JAP:brpmqc3) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/src/utils/graph/views/views.cc#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not seeing `right_entries used anywhere here in new code. Was this already necessary and just missing, or can this be removed?
</blockquote></details>

removed.
___
*[`lib/utils/src/utils/graph/views/views.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEcbnnx5wacvdV1VCc6:-OGJC3WlDNbvHvwQbd89:braj87) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/src/utils/graph/views/views.cc#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Does `commutative_pair` not have an `explicit` constructor?
</blockquote></details>

No, I can add it, though note that it would make writing test cases for `UndirectedGraph` pretty verbose, since you n [...]

2025-01-21 00:44 UTC, lockshaw requested changes
> Reviewed 1 of 32 files at r1, 1 of 9 files at r3, 38 of 38 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: all files reviewed, 25 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/utils/include/utils/graph/series_parallel/parallel_reduction.h` line 15 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD9CnD0OZQFYdtpZlL:-OH0fQVDEbuJ6ydLT-nI:b-uica5m) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/parallel_reduction.h#L15)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Have added docstrings and datatypes. (It's for accelerating the algo by batching multiple reduction steps together).
I've kept the extended reductions there, given that already series and parallel reduction were used solely for the SP decomp algorithm (So now they are not really used anymore, but still probably worth keeping around since they are pretty general functions).
</blockquote></details>

Can you move the docstrings over to the dtgen files themselves using #1581?
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 20 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD7mCl0y6oka-VVpqz:-OH0fg45Aih8Gxq4bObO:b-4b71y0) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L20)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

it can emerge in some of the SP-ization algorithms as a temporary artifact, though the final SP decompositions are always normalized (see normalize_sp_decomposition in #1562 ) so it doesn't show up "externally".
</blockquote></details>

In that case I'd kinda like to have a separate data structure for those two, but this of course will require a `nonempty_vector` type. I've added an issue to get one added in #1582, so we can keep these for now but once that's implemented I'd like to have a type that makes this structurally impossible
___
*[`lib/utils/src/utils/graph/views/views.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OEcbnnx5wacvdV1VCc6:-OH0h_Xf1N28eswe_V33:bhuazqj) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/src/utils/graph/views/views.cc#L70)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

No, I can add it, though note that it would make writing test cases for `UndirectedGraph` pretty verbose, since you now have to do `UndirectedEdge{commutative_pair{x,y}}`
</blockquote></details>

I would say make it `explicit` and then we can fix the verbosity through other means (e.g., helper functions, dtgen extensions) where necessary
___
*[`lib/utils/test/src/utils/graph/undirected/undirected.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD6HVV0LfDCxBRJYYx:-OH5E7td3mstUNEKgo24:bbdt18r) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/undirected/undirected.cc#L18)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

is this not ok for basic sanity checks? iirc, it was already present, I mostly cleaned it up.
</blockquote></details>

Looking at master I'm not seeing it, so I'm assuming you added this :joy:. It's not an issue to use rapidcheck, just since it's more (arguably) more conceptually complex than standard unit testing I'd like to double check that this test actually benefits from it, and at least from the code here I'm not super convinced it's really improving coverage over standard testing
___
*[`lib/utils/test/src/utils/graph/views/views.cc` line 49 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD6Ufw2WOT-N7tI2Fo:-OH5ElxjAzPfY91MTGx1:bm6k8b6) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/test/src/utils/graph/views/views.cc#L49)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Sorry, I'm not super clear on this. The idea would be to:
- Have a set graph (which is not RC generated)
- Use RC to generate a bunch of random edge, node queries and apply them to both the normal graph and the view equivalent.
- Have some equality checker that checks that the resulting nodes / edges match between the real graph and the view (e.g. for `ViewDirectedAsUndirected`, ensure that every DiEdge has a corresponding UndirectedEdge and viceversa (1 or 2 DiEdge, more precisely).

I don't see how to make the equivalence testing code to be generic, wouldn't you need to make some assumptions about what specific view you are using?
</blockquote></details>

Per our discussion, let's not prioritize view testing under the assumption that we'll eventually move over to a more simplified design of the graph library
___
*[`lib/utils/include/utils/graph/README.md` line 81 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0klfG0bU3LFch-nbn:-OH0klfG0bU3LFch-nbo:b-y9z4xa) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L81)):*
> ```Markdown
> ```
> 
> Note that the node names are just nameless things: they have no apparent ordering or other meaning besides representing the topology of the graph.
> ```

arbitrary?



_Code quote:_
```Markdown
just nameless things
```
___
*[`lib/utils/include/utils/graph/README.md` line 131 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0lATf0r3KhHBx3fFG:-OH0lATf0r3KhHBx3fFH:b-96i2xq) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L131)):*
> ```Markdown
> `DataflowGraph` is similar to `MultiDiGraph`, but with the following important differences:
>   - The edges entering, exiting a given nodes have a well-defined order. 
>   - `DataflowGraph`s are directed acyclic graphs. This is enforced by the interface used to construct them, since a node can only be added to the graph after all of its predecessor nodes have already been added.
> ```

The outputs are also ordered



_Code quote:_
```Markdown
`DataflowGraph` is similar to `MultiDiGraph`, but with the following important differences:
  - The edges entering, exiting a given nodes have a well-defined order.
  - `DataflowGraph`s are directed acyclic graphs. This is enforced by the interface used to construct them, since a node can only be added to the graph after all of its predecessor nodes have already been added.
```
___
*[`lib/utils/include/utils/graph/README.md` line 134 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0lGsG3HLBbOg1t5h0:-OH0lGsH1Qg8KjT8O3CA:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L134)):*
> ```Markdown
> 
> The main components of `DataflowGraph` are as follows:
> - `DataflowInput`: used to represent the ordered sequence of incoming dependencies (arguments) of a given node (operator). 
> ```





_Suggestion:_
```Markdown
- `DataflowInput`: used to denote an entry in the ordered sequence of incoming dependencies (arguments) of a given node (operator).
```
___
*[`lib/utils/include/utils/graph/README.md` line 135 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0lL_74hNo_Q_Lrr02:-OH0lL_74hNo_Q_Lrr03:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L135)):*
> ```Markdown
> The main components of `DataflowGraph` are as follows:
> - `DataflowInput`: used to represent the ordered sequence [...]

2025-01-21 00:45 UTC, lockshaw commented
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 24 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH5JK0m9Ozt3fdOf0ok:-OH5JK0m9Ozt3fdOf0ol:b-u1fv5l) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L24)):*
> ```cpp
> 
> std::optional<SeriesParallelDecomposition>
>     get_series_parallel_decomposition(DiGraphView const &g) {
> ```

Might be nice to also keep the old rewriting code, as doing equivalence testing between the two would be a great way to get good test coverage without too much manual effort


<!-- Sent from Reviewable.io -->

2025-01-22 03:22 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: all files reviewed, 25 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/containers/zip.h` line 14 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0bwna47zj_DdrM_-N:-OHAIbc--n7WZpu6gWOf:bbtpflo) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/containers/zip.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this instead of just having a separate `strict_zip` function? Do we ever need to determine `strict` dynamically?
</blockquote></details>

was mostly to mimick python's interface, can make it separate if needed.
___
*[`lib/utils/include/utils/graph/algorithms.h` line 141 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0fClV0ki4LcSNDK9N:-OHAJ8m80fJPm_kfLP6c:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/algorithms.h#L141)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Doxygen syntax
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/algorithms.h` line 144 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0fDiE7bWMrVr4ttQz:-OHAJ90o6f2a0BxUgSDP:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/algorithms.h#L144)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Doxygen syntax
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/README.md` line 81 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0klfG0bU3LFch-nbn:-OHAJH9w9o0W8MpK1jmC:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L81)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

arbitrary?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/README.md` line 131 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0lATf0r3KhHBx3fFG:-OHAJVmYBwWpPyThQYu3:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L131)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The outputs are also ordered
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/README.md` line 221 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0lkBF5QS-GmVcxQZC:-OHALWTX1mugeL3rXiBZ:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/README.md#L221)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Important to note that the `DataflowGraphInput`s aren't ordered, unlike `DataflowInputs`
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/digraph/algorithms.h` line 9 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGpkY7TB8wP8AKGZlBz:-OHALsV7CWgQ1lFgCrCl:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/digraph/algorithms.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add brief docstring for this as this terminology, while less ambiguous, is less immediately obvious
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/digraph/algorithms.h` line 10 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGpkclB-uYNZeyZQ4Ik:-OHALsrI6P2knoBzS4Ju:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/digraph/algorithms.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add brief docstring for this as this terminology, while less ambiguous, is less immediately obvious
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/series_parallel/extended_series_reduction.struct.toml` line 21 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGplZkb0ydVI_MOKjHM:-OHAzot2AdCrgu1UgA0i:b-o3fwgk) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/series_parallel/extended_series_reduction.struct.toml#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Given the constraint that the dst of the an edge must be the src of the next edge, might be cleaner to make this a `std::vector<Node>` instead, the attributes of most of the edges are uniquely determined by the sequence of `Node`s
</blockquote></details>

with the nodes it gets a bit messy, since within get_series_parallel_decomposition I need the associated `MultiDiEdge` edges (to construct the `ttsp_edge_to_sp_tree` mapping) and I can't reconstruct them from the nodes, since the edges are just wrappers for some uid and the underlying graph does the bookkeeping, so I would need to thread both nodes and edges.
___
*[`lib/utils/include/utils/graph/series_parallel/parallel_reduction.h` line 15 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGD9CnD0OZQFYdtpZlL:-OHAResW18YgB8BhtBvy:bb7f2mf) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d262a8aa83751aa9b9b6db22db1c3a360b06738/lib/utils/include/utils/graph/series_parallel/parallel_reduction.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you move the docstrings over to the dtgen files themselves using #1581?
</blockquote></details>

done
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 24 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH5JK0m9Ozt3fdOf0ok:-OHAUOuVBGT_CkLyi3L8:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be nice to also keep the old rewriting code, as doing equivalence testing between the two would be a great way to get good test coverage without too much manual effort
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 84 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH5J0mo0rWmNuWYh0aA:-OHAWVvr0Vla4tsScuyP:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L84)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be a nice lambda
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 91 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH5IgzHC4OJUDnrb_nc:-OHAWc7c7sMTHCjkKfPD:brawcmn) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Isn't `reductions` just `parallel_reductions.size() + series_reductions.size()`? Doing this incremental computation feels unnecessarily imperative/mutable
</blockquote></details>

changed it to a bool seems more clear.
___
*[`lib/utils/src/utils/graph/series_parall [...]

2025-02-09 20:02 UTC, lockshaw approved these changes
> Reviewed 23 of 24 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: all files reviewed, 3 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/include/utils/containers/zip.h` line 14 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OH0bwna47zj_DdrM_-N:-OIgGtXI9F68gtkxx7g2:b-3bfvqi) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/containers/zip.h#L14)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

was mostly to mimick python's interface, can make it separate if needed.
</blockquote></details>

I'd separate it for clarity (also remember that C++ doesn't really have named arguments, so a `strict` call would just show up as `zip(..., ..., true)`, which isn't super clear as to what you're doing. I suppose you could create a named bool using a dtgen enum...or you could just make two functions which seems a lot simpler.
___
*[`lib/utils/include/utils/graph/series_parallel/extended_series_reduction.struct.toml` line 21 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OGplZkb0ydVI_MOKjHM:-OIgG80Q9R3mPvFVWWiO:b-fmbqvf) ([raw file](https://github.com/flexflow/flexflow-train/blob/3f64d154ab39a4dcb2e465867f174fb48b0dfe5b/lib/utils/include/utils/graph/series_parallel/extended_series_reduction.struct.toml#L21)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

with the nodes it gets a bit messy, since within get_series_parallel_decomposition I need the associated `MultiDiEdge` edges (to construct the `ttsp_edge_to_sp_tree` mapping) and I can't reconstruct them from the nodes, since the edges are just wrappers for some uid and the underlying graph does the bookkeeping, so I would need to thread both nodes and edges.
</blockquote></details>

Can't you just get the edges from the graph given the vector of nodes?
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 46 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OIgGJiFAS9ZfvyBwqdk:-OIgGJiFAS9ZfvyBwqdl:b-u2yg2) ([raw file](https://github.com/flexflow/flexflow-train/blob/d6f0aea49b863ec1175f16c5ab06fc31a5c8800b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L46)):*
> ```cpp
>           [](Node const &n) { return SeriesParallelDecomposition{n}; });
> 
>   auto handle_parallel_reduction =
> ```

"apply" or "perform" are more precise than "handle"



_Suggestion:_
```cpp
  auto apply_extended_parallel_reduction =
```
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 63 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OIgGMetCP1cOy-L7qqy:-OIgGMetCP1cOy-L7qqz:b-u2yg2) ([raw file](https://github.com/flexflow/flexflow-train/blob/d6f0aea49b863ec1175f16c5ab06fc31a5c8800b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L63)):*
> ```cpp
>       };
> 
>   auto handle_series_reduction =
> ```

"apply" or "perform" are more precise than "handle"



_Suggestion:_
```cpp
  auto apply_extended_series_reduction =
```
___
*[`lib/utils/test/src/utils/graph/undirected/undirected.cc` line 56 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OIgINHJ4X-eF6EcnAs_:-OIgINHJ4X-eF6EcnAsa:bs501jd) ([raw file](https://github.com/flexflow/flexflow-train/blob/d6f0aea49b863ec1175f16c5ab06fc31a5c8800b/lib/utils/test/src/utils/graph/undirected/undirected.cc#L56)):*
> ```cpp
>             std::unordered_set<Node>{n.at(1), n.at(2), n.at(3), n.at(4)});
> 
>       // removing a node also removes its adjacent edges
> ```

Prefer named subcases for commenting the different `CHECK`s for readability


<!-- Sent from Reviewable.io -->

2025-02-09 23:37 UTC, lockshaw reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1521)* status: 57 of 96 files reviewed, 1 unresolved discussion (waiting on @Marsella8)

___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 46 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OIgGJiFAS9ZfvyBwqdk:-OIgq0SU4EufVSolrSyc:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/d6f0aea49b863ec1175f16c5ab06fc31a5c8800b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

"apply" or "perform" are more precise than "handle"
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc` line 63 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1521#-OIgGMetCP1cOy-L7qqy:-OIgq1jU6cZiVjV2gsIU:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/d6f0aea49b863ec1175f16c5ab06fc31a5c8800b/lib/utils/src/utils/graph/series_parallel/get_series_parallel_decomposition.cc#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

"apply" or "perform" are more precise than "handle"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-10 00:32 UTC, merged