Memory optimization algorithm
flexflow/flexflow-train pull request #1523
Opened 2024-10-13 22:11 UTC by wmdi

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-10-21 00:07 UTC, lockshaw requested changes
> Reviewed 11 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1523)* status: 11 of 17 files reviewed, 10 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gMNJ15gvaB3ND_MDU:-O9gMNJ15gvaB3ND_MDV:b-f27303) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L16)):*
> ```objc
> struct ICostEstimator {
>   virtual CostMetric estimate_cost(OpCostEstimateKey const &) const = 0;
>   virtual CostMetric estimate_cost(TensorSetMovement const &) const = 0;
> ```

Why does communication cost return a memory usage?
___
*[`lib/compiler/include/compiler/machine_mapping/feasible_machine_mapping_result.struct.toml` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNnbS6wx32FdbYTrb:-O9gNnbS6wx32FdbYTrc:b-hf9w4g) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/feasible_machine_mapping_result.struct.toml#L16)):*
> ```TOML
> [[fields]]
> name = "cost"
> type = "::FlexFlow::CostMetric"
> ```

Separate out into different result type
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNL5UAbfDPsbb094J:-O9gNL5UAbfDPsbb094K:bo56jf0) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
> ```objc
>     MachineSpecification const &resources,
>     MachineMappingConstraints const &constraints,
>     MachineMemoryConstraints const &memory_constraints,
> ```

I think for now let's separate the memory optimization algorithm from the existing algorithm. There may be a bit of code duplication, but I don't think it should be too much as they can both use a lot of existing infrastructure, and it is likely to make things a lot more maintainable in the long run.
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNdNTDNOJpi0neTG3:-O9gNdNTDNOJpi0neTG4:b-8cczab) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "MachineMappingConfig"
> ```

Remove in favor of separate algorithm implementation
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h` line 27 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNrwK54VFm_2mqPB9:-O9gNrwK54VFm_2mqPBA:bhbastg) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h#L27)):*
> ```objc
>                        &parallel_split_transformation);
> [[nodiscard]] MachineMappingResult
>     parallel_combine(MachineMappingConfig const &config,
> ```

Add operations for a new result type rather than overriding these
___
*[`lib/compiler/include/compiler/machine_mapping/machine_memory_constraints/machine_memory_constraints.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gMgx07kaK0eOdTkiX:-O9gMgx07kaK0eOdTkiY:by0jxnt) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_memory_constraints/machine_memory_constraints.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "MachineMemoryConstraints"
> ```

Probably better to just make this a field on `MachineSpecification`
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gO8Kg7lmsVhf7L3X9:-O9gO8Kg7lmsVhf7L3XA:b-enrh5g) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L10)):*
> ```cpp
>       /*memory=*/0,
>   };
> }
> ```

I'm not really convinced this is all that useful of a function?
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 36 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gOER-1dTED3yURQak:-O9gOER-1dTED3yURQal:bm0uxbu) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L36)):*
> ```cpp
>   for (CostMetric const &cost : costs) {
>     result = combine_cost_metrics_intra_device_sequential(result, cost);
>   }
> ```

`foldl1` from `utils/containers`?



_Code quote:_
```cpp
  CostMetric result = zero_cost_metric();
  for (CostMetric const &cost : costs) {
    result = combine_cost_metrics_intra_device_sequential(result, cost);
  }
```
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gOPSiCfOSlCz2359y:-O9gOPSiCfOSlCz2359z:b-h7juaj) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L40)):*
> ```cpp
> }
> 
> CostMetric combine_cost_metrics_intra_device_parallel(CostMetric const &c1,
> ```

What does "intra_device" mean here? 



_Code quote:_
```cpp
intra_device
```
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gOJ9b5-DOVc3ncCmY:-O9gOJ9b5-DOVc3ncCmZ:bm0uxbu) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L51)):*
> ```cpp
>   for (CostMetric const &cost : costs) {
>     result = combine_cost_metrics_intra_device_parallel(result, cost);
>   }
> ```

`foldl1` from `utils/containers`?



_Code quote:_
```cpp
  CostMetric result = zero_cost_metric();
  for (CostMetric const &cost : costs) {
    result = combine_cost_metrics_intra_device_parallel(result, cost);
  }
```


<!-- Sent from Reviewable.io -->

2024-10-31 00:36 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1523)* status: 2 of 26 files reviewed, 10 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gMNJ15gvaB3ND_MDU:-OAUzuMn5Z_8yCstmaac:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does communication cost return a memory usage?
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNL5UAbfDPsbb094J:-OAUzv3ZBjHoWrAK1vni:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think for now let's separate the memory optimization algorithm from the existing algorithm. There may be a bit of code duplication, but I don't think it should be too much as they can both use a lot of existing infrastructure, and it is likely to make things a lot more maintainable in the long run.
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNdNTDNOJpi0neTG3:-OAUzvX498DVljfBi5v5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove in favor of separate algorithm implementation
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/machine_memory_constraints/machine_memory_constraints.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gMgx07kaK0eOdTkiX:-OAUzyfW3XqHq1yGhbjP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_memory_constraints/machine_memory_constraints.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to just make this a field on `MachineSpecification`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-07 01:53 UTC, lockshaw requested changes
The main thing is some unit testing should be added--currently the test coverage for this PR is 3.5%.

> Reviewed 2 of 17 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-:-OB3Jl_W43thgGEk0oEb:b5n104y)* status: all files reviewed, 16 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV0OqN5ZUklEBn4ifj:-OAV0OqN5ZUklEBn4ifk:b-lsj7jl) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L18)):*
> ```objc
>   virtual float estimate_cost(TensorSetMovement const &) const = 0;
>   virtual CostMetric
>       estimate_cost_with_memory(OpCostEstimateKey const &) const = 0;
> ```

I don't think we need another function here--communication shouldn't return a memory usage, but returning memory usage for an operator is fine.

it would be nice to get a more descriptive name than `CostMetric`, maybe something like `OperatorCostMetrics` to specify it's just for operators and it contains more than one "metric"?



_Suggestion:_
```objc
  virtual CostMetric estimate_cost(OpCostEstimateKey const &) const = 0;
  virtual float estimate_cost(TensorSetMovement const &) const = 0;
```
___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 31 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV0_ox-X-kY1eFkMAq:-OAV0_ox-X-kY1eFkMAr:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L31)):*
> ```objc
>   float estimate_cost(OpCostEstimateKey const &k) const;
>   float estimate_cost(TensorSetMovement const &m) const;
>   CostMetric estimate_cost_with_memory(OpCostEstimateKey const &k) const;
> ```





_Suggestion:_
```objc
  CostMetric estimate_cost(OpCostEstimateKey const &k) const;
  float estimate_cost(TensorSetMovement const &m) const;
```
___
*[`lib/compiler/include/compiler/cost_estimator/cost_metric.h` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV2ANE4BmUid37V9r8:-OAV2ANF2tjvFUZl8sNq:b-tkk5ao) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_metric.h#L7)):*
> ```objc
> #include <vector>
> 
> namespace FlexFlow {
> ```

These operations feel like something algorithm-specific rather than relevant to cost_estimator--I have no problem with them existing, but maybe the file should be somewhere else? Would the new `machine_mapping_with_memory` directory be appropriate?
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-O9gNdNTDNOJpi0neTG3:-OB3JfGF9BpikdVBTwMX:b-nee2lm) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml#L2)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This file still seems to be here? Is it still necessary?
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV3QzI6mNwA2_9q3YV:-OAV3QzI6mNwA2_9q3YW:bbh5jlr) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml#L0)):*
Rename to `machine_mapping_with_memory_cache.struct.toml`
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml` line 2 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV3NyH3k9MhB6kIpZ5:-OAV3NyH3k9MhB6kIpZ6:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "MachineMappingCacheWithMemory"
> ```





_Suggestion:_
```TOML
name = "MachineMappingWithMemoryCache"
```
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml` line 2 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV2R9PEdQ6q4I8Ikxj:-OAV2R9PEdQ6q4I8Ikxk:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "MachineMappingResultWithMemory"
> ```





_Suggestion:_
```TOML
ame = "MachineMappingWithMemoryResult"
```
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml` line 20 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV2uNM5uTwujp19rtK:-OAV2uNM5uTwujp19rtL:bmqanbj) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml#L20)):*
> ```TOML
> [[fields]]
> name = "machine_mappings"
> type = "std::unordered_set<::FlexFlow::SingleMachineMapping>"
> ```

What does this set represent? What is the meaning behind a `SingleMachineMapping`--is that a machine mapping for a single layer, or a single pareto-optimal solution, or something else entirely? `SingleMachineMapping` likely needs a clearer name.



_Code quote:_
```TOML
type = "std::unordered_set<::FlexFlow::SingleMachineMapping>"
```
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV405gCAQMnfIlTt-O:-OAV405gCAQMnfIlTt-P:b-dtdna9) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.cc#L12)):*
> ```cpp
> 
> std::optional<MachineMappingResultWithMemory>
>     machine_mapping_cache_with_memory_load(
> ```

For all the functions here



_Suggestion:_
```cpp
    machine_mapping_with_memory_cache_load(
```
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV4N808yS0C8rhJZeI:-OAV4N808yS0C8rhJZeJ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L26)):*
> ```cpp
> }
> 
> MachineMappingResultWithMemory remove_non_dominating_machine_mapping_result(
> ```





_Suggestion:_
```cpp
remove_non_pareto_optimal_machine_mapping_results
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1523#-OAV3rx_CACaLoMST6BB:-OAV3rx_CACaLoMST6BC:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h#L32)):*
> ```objc
>   CostMetric
>       estimate_cost_with_memory(OpCostEstimateKey const &) const override;
> };
> ```





_Suggestion:_
```objc
struct TestCostEstimator : public ICostEstimator {
  std::function<CostMetric(OpCostEstimateKey const &)> get_operator_cost;
  std::function<float(TensorSetMovement const &)> get_communication_cost;

  TestCostEstimator() = delete;
  TestCostEstimator(decltyp [...]

2024-12-18 05:37 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: 26 of 28 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 18 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV0OqN5ZUklEBn4ifj:-OE5dBip8Td3D0RSyp2z:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think we need another function here--communication shouldn't return a memory usage, but returning memory usage for an operator is fine.

it would be nice to get a more descriptive name than `CostMetric`, maybe something like `OperatorCostMetrics` to specify it's just for operators and it contains more than one "metric"?
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/cost_metric.h` line 7 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV2ANE4BmUid37V9r8:-OBaz1mE9AZiv_DhHCDw:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_metric.h#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These operations feel like something algorithm-specific rather than relevant to cost_estimator--I have no problem with them existing, but maybe the file should be somewhere else? Would the new `machine_mapping_with_memory` directory be appropriate?
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-O9gNdNTDNOJpi0neTG3:-OBaz9FD5-mptV7b4vwm:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/include/compiler/machine_mapping/machine_mapping_config.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This file still seems to be here? Is it still necessary?
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml` line  at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV3QzI6mNwA2_9q3YV:-OBb-7-XCN5gd1CMxVGN:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Rename to `machine_mapping_with_memory_cache.struct.toml`
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-O9gO8Kg7lmsVhf7L3X9:-OEMY2FH9cidzSKFa0Qm:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not really convinced this is all that useful of a function?
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 36 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-O9gOER-1dTED3yURQak:-OENEi6j0vYqTx1DzNjk:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`foldl1` from `utils/containers`?
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 40 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-O9gOPSiCfOSlCz2359y:-OENEis6DY1Swb89oGFr:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does "intra_device" mean here?
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/cost_metric.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-O9gOJ9b5-DOVc3ncCmY:-OENEjbSDHmYYPjT0tLZ:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/ef8c5c2f2d6eafec7fc9ec95da417879368457cf/lib/compiler/src/compiler/cost_estimator/cost_metric.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`foldl1` from `utils/containers`?
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV405gCAQMnfIlTt-O:-OBb-IH1BvoygVUgsg2M:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.cc#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For all the functions here
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/cost_estimator.h` line 31 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV0_ox-X-kY1eFkMAq:-OE5dD4e0EOE8WQWdyKy:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/cost_estimator/cost_estimator.h#L31)):*
> ```objc
>   float estimate_cost(OpCostEstimateKey const &k) const;
>   float estimate_cost(TensorSetMovement const &m) const;
>   CostMetric estimate_cost_with_memory(OpCostEstimateKey const &k) const;
> ```

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV4N808yS0C8rhJZeI:-OENGNjA4Tn3Dm45LG-R:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L26)):*
> ```cpp
> }
> 
> MachineMappingResultWithMemory remove_non_dominating_machine_mapping_result(
> ```

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h` line 32 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV3rx_CACaLoMST6BB:-OENGPT78z76qyvQ0m6l:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h#L32)):*
> ```objc
>   CostMetric
>       estimate_cost_with_memory(OpCostEstimateKey const &) const override;
> };
> ```

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h` line 54 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV3mGS4wJfLOyJo3V1:-OENGQ-D9k2VUDdKovYG:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/test/src/compiler/machine_mapping/cost_estimator_for_test.h#L54)):*
> ```objc
>     std::unordered_map<TensorSetMovement, float> const &comm_cost_map,
>     std::unordered_map<OpCostEstimateKey, CostMetric> const
>         &op_cost_with_memory_map);
> ```

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_cache_with_memory.struct.toml` line 2 at r2](https://reviewable.io/reviews/flexflow/flexflow [...]

2024-12-18 22:25 UTC, lockshaw requested changes
> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: all files reviewed, 16 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/get_optimal_machine_mapping_with_memory.cc` line 215 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqu1E80Jq8CQWiy5P:-OEQqu1F27ln05wmM6ZO:bvl7b92) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/get_optimal_machine_mapping_with_memory.cc#L215)):*
> ```cpp
>       MachineMappingWithMemoryResult correct = MachineMappingWithMemoryResult{{
>           SingleMachineMapping{
>               OpCostMetrics{1.0 + 2.0 + 0.1, 2 + 3},
> ```

Argument name comments would be nice here
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 11 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3S_2An-dgMli3zDH:-OBO3S_2An-dgMli3zDI:b-rrzqjc) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L11)):*
> ```cpp
>     MachineView machine_view_0 = MachineView{
>         /*start=*/MachineSpaceCoordinate{
>             /*node_idx=*/0,
> ```

@Marsella8 What do you think of making these `node_idx` and `device_idx` wrapper types to avoid construction errors? Would there be anything wrong with that?



_Code quote:_
```cpp
            /*node_idx=*/0,
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 57 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3c7Z6ZIi2UXraSGo:-OBO3c7Z6ZIi2UXraSGp:bsznteh) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L57)):*
> ```cpp
>         2.0,
>         2,
>     };
> ```

Argument name comments please, it's not immediately obvious what these parameters are



_Code quote:_
```cpp
    CostMetric cost1 = CostMetric{
        2.0,
        2,
    };
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 115 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3uY75sVIIoPs8Aev:-OBO3uY75sVIIoPs8Aew:bvvzzl6) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L115)):*
> ```cpp
> 
>     SUBCASE("no non-dominating") {
>       MachineMappingResultWithMemory to_remove = MachineMappingResultWithMemory{
> ```

With the name `to_remove` it makes it sounds like all of these should be removed, but instead I think they're the container of elements to be filtered?



_Suggestion:_
```cpp
      MachineMappingResultWithMemory input = MachineMappingResultWithMemory{
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 147 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqU6wE_L3Jwia-_OW:-OEQqU6wE_L3Jwia-_OX:b-6q0nre) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L147)):*
> ```cpp
>         }};
> 
>     printf("Before constructing cost_estimator\n");
> ```

Remove print
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 150 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqJWg3PtDNx8wPZqM:-OEQqJWg3PtDNx8wPZqN:bnu7ohg) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L150)):*
> ```cpp
> 
>     auto map1 = std::unordered_map<OpCostEstimateKey, OpCostMetrics>{{
>         {map_unmapped_op_cost_estimate_key(k1, mv1), OpCostMetrics(1.0, 0)},
> ```

Argument name comments here would be nice



_Code quote:_
```cpp
OpCostMetrics(1.0, 0)},
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 150 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqMCgAFdM0xnDlB9r:-OEQqMCgAFdM0xnDlB9s:b-pin6ql) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L150)):*
> ```cpp
> 
>     auto map1 = std::unordered_map<OpCostEstimateKey, OpCostMetrics>{{
>         {map_unmapped_op_cost_estimate_key(k1, mv1), OpCostMetrics(1.0, 0)},
> ```

Prefer bracket initialization



_Suggestion:_
```cpp
        {map_unmapped_op_cost_estimate_key(k1, mv1), OpCostMetrics{1.0, 0}},
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 156 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqQ9j2_g-8qA53HD_:-OEQqQ9j2_g-8qA53HDa:bgsoo7p) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L156)):*
> ```cpp
>     }};
> 
>     printf("After constructing map1\n");
> ```

Remove prints :slightly_smiling_face: 
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 172 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQq__HBiqKE00Q874N:-OEQq__HBiqKE00Q874O:bhofei7) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L172)):*
> ```cpp
>         }});
> 
>     // CostEstimator cost_estimator = make_fake_cost_estimator(
> ```

Delete?
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 193 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqVFoEbI7WwAoXcn4:-OEQqVFoEbI7WwAoXcn5:b-6q0nre) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L193)):*
> ```cpp
>     //     }});
> 
>     printf("After constructing cost_estimator\n");
> ```

Remove print
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 200 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqbhdA2em3d31B05e:-OEQqbhe8RcZdVyquBYV:b-6q0nre) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L200)):*
> ```cpp
>     };
> 
>     printf("After constructing context\n");
> ```

Remove print
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 114 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQrY3j7aZutm3Ay2S_:-OEQrY3j7aZutm3Ay2Sa:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L114)):*
> ```cpp
>     }
> 
>     SUBCASE("no non-pareto_optimal") {
> ```





_Suggestion:_
```cpp
    SUBCASE("all solutions are pareto-optimal") {
```
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 128 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQrasx3-499ZrjIWhC:-OEQrasx3-499ZrjIWhD:undefined) ([raw file](https://github.com/fle [...]

2024-12-23 23:44 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: all files reviewed, 16 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 11 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3S_2An-dgMli3zDH:-OEpskxp17wmHChkXCX8:bbgmy17) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

@Marsella8 What do you think of making these `node_idx` and `device_idx` wrapper types to avoid construction errors? Would there be anything wrong with that?
</blockquote></details>

Agree that they should be wrapped. Perhaps we should also do the same for `MachineSpecification`? (e.g. see the current tests for `machine_view`, where we have do annotate all the arguments to make it readable). 


<!-- Sent from Reviewable.io -->

2024-12-30 07:18 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: 26 of 29 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 147 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqU6wE_L3Jwia-_OW:-OFKGY2p17HA0Q-YTSlv:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L147)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove print
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 150 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqJWg3PtDNx8wPZqM:-OFL5Tcd4DjvlNzVEXnN:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L150)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Argument name comments here would be nice
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 150 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqMCgAFdM0xnDlB9r:-OFL5akr7jnMse-Mnxr9:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L150)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer bracket initialization
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 156 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqQ9j2_g-8qA53HD_:-OFL5bJ44lsHFgnCrrx5:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L156)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove prints :slightly_smiling_face:
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 172 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQq__HBiqKE00Q874N:-OFL5bcn-d5tW-NNTcHj:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L172)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 193 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqVFoEbI7WwAoXcn4:-OFL5byVBo5o2docTHFT:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L193)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove print
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 200 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqbhdA2em3d31B05e:-OFL5cF3B4KIt-pTkCuo:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L200)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove print
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/get_optimal_machine_mapping_with_memory.cc` line 215 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQqu1E80Jq8CQWiy5P:-OFL67-1781e1zjmbJNk:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/get_optimal_machine_mapping_with_memory.cc#L215)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Argument name comments would be nice here
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 57 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3c7Z6ZIi2UXraSGo:-OFL6cB_742n65blPDpy:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L57)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Argument name comments please, it's not immediately obvious what these parameters are
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 115 at r3](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OBO3uY75sVIIoPs8Aev:-OFL7_HLCopnmHj8Nr_u:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/0c0e7b042fe9bee725e4592259b62256dac17882/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L115)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

With the name `to_remove` it makes it sounds like all of these should be removed, but instead I think they're the container of elements to be filtered?
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 149 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQrQgz8LBKppohe1wn:-OFL7xlr9ZwJDECVqYnl:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L149)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would be nice to have the actual function signature here instead of just a `(memory)` suffix to make it easier to match up with the corresponding function
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 340 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQrueqAgX7GNfrgqay:-OFL7y1h1_IOQbpcmR_2:b-el3413) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L340)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would be nicer to have the actual function signature to make it easier to match up with the corresponding function
</blockquote></details>

Done.   
___
*[`lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc` line 114 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OEQrY3j7aZutm3Ay2S_:-OFL6jth0PTrnvnGQ2id:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/03151607792794f430b730a5c6605c4388f0a204/lib/compiler/test/src/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.cc#L114)):*
> ```cpp
>     }
> 
>     SUBCASE("no non-pareto_optimal") {
> ```

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/memor [...]

2025-01-09 02:06 UTC, lockshaw approved these changes
> Reviewed 1 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2025-01-09 03:09 UTC, merged

2025-02-13 02:06 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1523)* status: 28 of 29 files reviewed, all discussions resolved

___
*[`lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml` line 20 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1523#-OAV2uNM5uTwujp19rtK:-OG7giKQDdMVthDw8-9M:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/964c885c5bf667ec1285eca6c0f7746b7c2e6edc/lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_result_with_memory.struct.toml#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does this set represent? What is the meaning behind a `SingleMachineMapping`--is that a machine mapping for a single layer, or a single pareto-optimal solution, or something else entirely? `SingleMachineMapping` likely needs a clearer name.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->