Add DLRM Model Computational Graph
flexflow/flexflow-train pull request #1532
Opened 2024-10-31 00:13 UTC by easyeasydev

**Description of changes:**

This PR adds the computational graph of DLRM model.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-10-31 00:27 UTC, easyeasydev reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/src/models/dlrm/dlrm.cc` line 44 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUvmfI9gweQ8AOWtCo:-OAUvmfI9gweQ8AOWtCp:b-w1h49g) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L44)):*
> ```cpp
> }
> 
> tensor_guid_t create_dlrm_mlp(ComputationGraphBuilder &cgb,
> ```

This MLP implementation refers to the original FlexFlow implementation at https://github.com/flexflow/FlexFlow/blob/inference/examples/cpp/DLRM/dlrm.cc#L44. Not sure if there was a specific reason to do this in the past. We can decide what to do here. Torchrec doesn't have this logic to initialize the initializers.
@lockshaw 
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 145 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUwibW0-jZ9fWE2xWc:-OAUwibX3UNHoGEEH94Q:b-y0mvqr) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L145)):*
> ```cpp
>       /*mlp_layers=*/config.dense_arch_layer_sizes);
> 
>   std::vector<tensor_guid_t> emb_outputs;
> ```

As suggested, I tried this:

```
  std::vector<tensor_guid_t> emb_outputs = transform(
      zip(config.embedding_size, sparse_inputs),
      [&](std::pair<int, tensor_guid_t> &combined_pair) -> tensor_guid_t {
        return create_dlrm_sparse_embedding_network(
            /*cgb=*/cgb,
            /*config=*/config,
            /*input=*/combined_pair.second,
            /*input_dim=*/combined_pair.first,
            /*output_dim=*/config.embedding_dim);
      });
```

But I couldn't make it compile by using transform and zip...


<!-- Sent from Reviewable.io -->

2024-10-31 00:30 UTC, easyeasydev reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/src/models/dlrm/dlrm.cc` line 128 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUyBepDX4Q5mQhVaEL:-OAUyBeq39HsJ_bTSyP1:bj3qnpt) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L128)):*
> ```cpp
> 
>   // Create input tensors
>   std::vector<tensor_guid_t> sparse_inputs(
> ```

This had the following review comment before:

Quote:
I think this current implementation makes `sparse_inputs` a vector of the same `tensor_guid_t` over and over again, rather than being a vector of identically-shaped tensors. Was that intentional? If not, then maybe the below code would be better?

```
std::vector<tensor_guid_t> sparse_inputs = repeat(config.embedding_size.size(), [&]() { return create_input_tensor({config.batch_size, config.embedding_bag_size}, DataType::INT64); });
```


The intention was to create multiple tensors as the inputs. I'm not sure if this vector creation syntax will lead to having all inputs referring to a single tensor? I would think `create_input_tensor` should return a copy of tensor for each item in the vector?


<!-- Sent from Reviewable.io -->

2024-11-07 02:22 UTC, easyeasydev reviewed
Check FB, Torchrec and the paper for DLRM initializer implementation to decide whether we want to keep the special logic.
Try to generate the dot representation.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-:-OB3QNkv-p_0F4UQeC6A:bc7v7w3)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-11-09 02:50 UTC, lockshaw requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532)* status: all files reviewed, 17 unresolved discussions (waiting on @easyeasydev, @lockshaw, and @reyna-abhyankar)

___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KVBl15kpQb5vme-g:-OB3KVBl15kpQb5vme-h:b7cmtxf) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L29)):*
> ```TOML
> [[fields]]
> name = "embedding_bag_size"
> type = "size_t"
> ```

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD:-OB3KCVzBHRvW3WmKCxE:b8f52uj) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L37)):*
> ```TOML
> [[fields]]
> name = "dense_arch_layer_sizes"
> type = "std::vector<size_t>"
> ```

Prefer `int` to avoid confusing failures if negative values are used (the long-term solution is to use the `nonnegative_int` getting added in #1533, but for now this is the best solution)



_Suggestion:_
```TOML
type = "std::vector<int>
```
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KZ3sBNdQedIdpjxl:-OB3KZ3sBNdQedIdpjxm:b7cmtxf) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L41)):*
> ```TOML
> [[fields]]
> name = "over_arch_layer_sizes"
> type = "std::vector<size_t>"
> ```

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3Kl1v92e2wjIl_0uO:-OB3Kl1v92e2wjIl_0uP:bmjxsv1) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L45)):*
> ```TOML
> [[fields]]
> name = "arch_interaction_op"
> type = "std::string"
> ```

Would this make more sense as an enum? Is there a list of the allowed arch interaction ops somewhere? Based on https://github.com/facebookresearch/dlrm/blob/64063a359596c72a29c670b4fcc9450bb342e764/dlrm_s_pytorch.py#L483-L515 it seems that the only possible values are `dot` and `cat`--is that the implementation you were referring to?
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KaPj5nVGVoS-yFCX:-OB3KaPj5nVGVoS-yFCY:b7cmtxf) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L49)):*
> ```TOML
> [[fields]]
> name = "batch_size"
> type = "size_t"
> ```

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDosA8Cpl0LdtWv9jW:-OBDosA8Cpl0LdtWv9jX:b669zrc) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L10)):*
> ```cpp
> 
> /**
>  * @brief Get the default DLRM config.
> ```

Why have this in the `.cc` file rather than the `.h` file? Does it make any difference in the rendered doxygen docs? (recall that you can run `proj doxygen --browser` to see the docs)
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3LG_uCzqh_Q6VFAGH:-OB3LG_uCzqh_Q6VFAGI:b-sm5ie7) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L13)):*
> ```cpp
>  *
>  * @details The configs here refer to the example at
>  * https://github.com/flexflow/FlexFlow/blob/inference/examples/cpp/DLRM/dlrm.cc.
> ```

This link is great--always welcome to add more of these! :slightly_smiling_face: 
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3LOKD3ORzVtu_8w_O:-OB3LOKD3ORzVtu_8w_P:b-tyiqz4) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L13)):*
> ```cpp
>  *
>  * @details The configs here refer to the example at
>  * https://github.com/flexflow/FlexFlow/blob/inference/examples/cpp/DLRM/dlrm.cc.
> ```

Can you change this to a permalink? Right now if `inference` moves or deletes the `dlrm.cc` file this url is going to 404, or could also just end up going out-of-date and being confusing. For this type of thing I'd prefer permalinks wherever possible
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 44 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUvmfI9gweQ8AOWtCo:-OBDlsDRBs1MkspydUSC:b-ozm53x) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L44)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

This MLP implementation refers to the original FlexFlow implementation at https://github.com/flexflow/FlexFlow/blob/inference/examples/cpp/DLRM/dlrm.cc#L44. Not sure if there was a specific reason to do this in the past. We can decide what to do here. Torchrec doesn't have this logic to initialize the initializers.
@lockshaw
</blockquote></details>

This at least looks similar? https://github.com/facebookresearch/dlrm/blob/64063a359596c72a29c670b4fcc9450bb342e764/dlrm_s_pytorch.py#L218-L228
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDoICWEoybs5ri-oN0:-OBDoICWEoybs5ri-oN1:bts2q10) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L49)):*
> ```cpp
>                               std::vector<size_t> const &mlp_layers) {
>   tensor_guid_t t = input;
>   for (size_t i = 0; i < mlp_layers.size() - 1; i++) {
> ```

You could also just zip `mlp_layers` and `mlp_layers[1:]` if you want to avoid all the careful index calculation



_Code quote:_
```cpp
 for (size_t i = 0; i < mlp_layers.size() - 1; i++) {
```
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAV7nEA2ewMia1cv5aL:-OAV7nEA2ewMia1cv5aM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L50)):*
> ```cpp
>   tensor_guid_t t = input;
>   for (size_t i = 0; i < mlp_layers.size() - 1; i++) {
>     float std_dev = sqrt(2.0f / (mlp_layers[i + 1] + mlp_layers[i]));
> ```





_Suggestion:_
```cpp
    float std_dev = sqrt(2.0f / (mlp_layers.at(i + 1) + mlp_layers.at(i)));
```
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 58 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAV7jffDwogufshytq7:-OAV7jffDwogufshytq8:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L58)):*
> ```cpp
>         }};
> 
>     std_dev = sqrt(2.0f / mlp_layers[i + 1]);
> ```





_Suggestion:_
```cpp
    std_dev = sqrt(2.0f / mlp_layers.at(i + 1));
```
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 66 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3Mb2SBPmOT5djzRJY:-OB3Mb2T0BlosQ-jV9Fv:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L66)):*
> ```cpp
> 
>     t = cgb.dense(/*input=*/ [...]

2024-11-11 01:06 UTC, lockshaw reviewed
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532)* status: all files reviewed, 15 unresolved discussions (waiting on @easyeasydev and @reyna-abhyankar)

___
*[`lib/models/src/models/dlrm/dlrm.cc` line 135 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDmQO4BXRaRiZB6DJb:-OBNkAs-E1ElBPbYPVyk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L135)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Leaving a comment so we don't accidentally merge this PR before this gets addressed
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 168 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDomu4B6DezEZSsqRk:-OBNk4mi6QWv2P78HqsZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/pcg/src/pcg/computation_graph_builder.cc#L168)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-28 01:58 UTC, easyeasydev reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1532)* status: 4 of 7 files reviewed, 15 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KVBl15kpQb5vme-g:-OCkPHFMAhlIMdonNHvL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
</blockquote></details>

Done.
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD:-OCkPhMoAX2hCjhvMj_t:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` to avoid confusing failures if negative values are used (the long-term solution is to use the `nonnegative_int` getting added in #1533, but for now this is the best solution)
</blockquote></details>

Done.
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KZ3sBNdQedIdpjxl:-OCkPhdr8_24NeAyEE8y:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
</blockquote></details>

Done.
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3Kl1v92e2wjIl_0uO:-OCkPqZ8Ehv6pfIZlxo_:buqxb7a) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would this make more sense as an enum? Is there a list of the allowed arch interaction ops somewhere? Based on https://github.com/facebookresearch/dlrm/blob/64063a359596c72a29c670b4fcc9450bb342e764/dlrm_s_pytorch.py#L483-L515 it seems that the only possible values are `dot` and `cat`--is that the implementation you were referring to?
</blockquote></details>

Agree enum may make more sense. Do you have an example of using enum in dtgen? I can change to enum following that.
___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KaPj5nVGVoS-yFCX:-OCkQ8xPDakDCjjdZPAs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` (see https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3KCVzBHRvW3WmKCxD for explanation)
</blockquote></details>

Done.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDosA8Cpl0LdtWv9jW:-OCkQJBr6TNZjlyQxCO-:b-b5iu69) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why have this in the `.cc` file rather than the `.h` file? Does it make any difference in the rendered doxygen docs? (recall that you can run `proj doxygen --browser` to see the docs)
</blockquote></details>

No particular reason. Have moved to `.h` file.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OB3LOKD3ORzVtu_8w_O:-OCkQUFC6SmiAe9ZMtnE:b-jcfz5y) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you change this to a permalink? Right now if `inference` moves or deletes the `dlrm.cc` file this url is going to 404, or could also just end up going out-of-date and being confusing. For this type of thing I'd prefer permalinks wherever possible
</blockquote></details>

Have updated to the permalink. Thanks for the suggestion - I wasn't aware of this "permalink" until you pointed out.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 44 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUvmfI9gweQ8AOWtCo:-OCkRTdw1_uorNqDXZgF:bxzv7ph) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This at least looks similar? https://github.com/facebookresearch/dlrm/blob/64063a359596c72a29c670b4fcc9450bb342e764/dlrm_s_pytorch.py#L218-L228
</blockquote></details>

Good point. I have linked the permalink in the code.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDoICWEoybs5ri-oN0:-OCkTdIsCL2hQOpsjelk:bgup6iv) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You could also just zip `mlp_layers` and `mlp_layers[1:]` if you want to avoid all the careful index calculation
</blockquote></details>

Yes, agree that should work as well. But this current version should be clear to audience as well (hopefully lol).
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 102 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OBDm1qM1SURjQPX4_F0:-OCkSZ350pJtE7y1-d0A:b-jfz24d) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Considering that there are only two interaction ops, it might be cleaner to just use an enum?
</blockquote></details>

Agree. I can switch to enum if we have an example in dtgen.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 128 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUyBepDX4Q5mQhVaEL:-OCkT4PC9F3HDa4DZPAD:b7ow250) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L128)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Using a lambda would fix it. I'm actually a bit confused about how this current code compiles--based on the source code of `repeat` (https://github.com/flexflow/FlexFlow/blob/1d5140d5e98c18e73ce576673aa34022ad6d804f/lib/utils/include/utils/containers/repeat.h#L16), doesn't `F` need to be callable?
</blockquote></details>

Hmm, yea, I actually meant I couldn't switch to use `repeat` after a few attempts. The quote above was your original suggestion in the lost PR.

I guess the main question here is that whether we want to create "multiple copies" of `tensor_guid_t` in this vector here.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 145 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1532#-OAUwibW0-jZ9fWE2xWc:-OCkUKfA3FABwLENukrH:b-jzvr68) ([raw file](https://github.com/flexflow/FlexFlow/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L145)):*
<details><su [...]

2024-12-19 06:55 UTC, lockshaw requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1532)* status: all files reviewed, 3 unresolved discussions (waiting on @easyeasydev and @reyna-abhyankar)

___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 45 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OB3Kl1v92e2wjIl_0uO:-OESez8w0oLJmU9v5_6O:b-vux3d5) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L45)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Agree enum may make more sense. Do you have an example of using enum in dtgen? I can change to enum following that.
</blockquote></details>

https://github.com/flexflow/flexflow-train/blob/master/lib/op-attrs/include/op-attrs/activation.enum.toml
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OBDoICWEoybs5ri-oN0:-OESgdja7CpHWCDSIpoR:b-kqtwaw) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L49)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Yes, agree that should work as well. But this current version should be clear to audience as well (hopefully lol).
</blockquote></details>

Fair enough--in the future I probably prefer the zip approach (handcoded arithmetic is just easier to accidentally mess up), but it's not a big issue here
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 128 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OAUyBepDX4Q5mQhVaEL:-OESgLWv1pVY1Xma83jc:brezoqj) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L128)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Hmm, yea, I actually meant I couldn't switch to use `repeat` after a few attempts. The quote above was your original suggestion in the lost PR.

I guess the main question here is that whether we want to create "multiple copies" of `tensor_guid_t` in this vector here.
</blockquote></details>

Based on https://github.com/flexflow/flexflow-train/blob/78307b0e8beb5d41ee003be8b5db168c2b3ef4e2/examples/cpp/DLRM/dlrm.cc#L138-L143 I'd say you want multiple different `tensor_guid_t`s, in which case you should use the `repeat` code snippet you included above (and if you get any build errors using it, send me the error message so I can help debug) 
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 145 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OAUwibW0-jZ9fWE2xWc:-OESfZ-TC9Vy4rMfWtRj:b-5pq4ap) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L145)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Hmm, this compilation error looks like:

```
/home/eric/ff3/FlexFlow/lib/models/src/models/dlrm/dlrm.cc: In function ‘FlexFlow::ComputationGraph FlexFlow::get_dlrm_computation_graph(const FlexFlow::DLRMConfig&)’:
/home/eric/ff3/FlexFlow/lib/models/src/models/dlrm/dlrm.cc:155:51: error: no matching function for call to ‘transform(std::vector<std::pair<int, FlexFlow::tensor_guid_t>, std::allocator<std::pair<int, FlexFlow::tensor_guid_t> > >, FlexFlow::get_dlrm_computation_graph(const FlexFlow::DLRMConfig&)::<lambda(std::pair<int, FlexFlow::tensor_guid_t>&)>)’
  155 | std::vector<tensor_guid_t> emb_outputs = transform(
      |                                          ~~~~~~~~~^
  156 |       zip(config.embedding_size, sparse_inputs),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
  157 |       [&](std::pair<int, tensor_guid_t> &combined_pair) -> tensor_guid_t {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  158 |         return create_dlrm_sparse_embedding_network(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  159 |             /*cgb=*/cgb,
      |             ~~~~~~~~~~~~                           
  160 |             /*config=*/config,
      |             ~~~~~~~~~~~~~~~~~~                     
  161 |             /*input=*/combined_pair.second,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
  162 |             /*input_dim=*/combined_pair.first,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
  163 |             /*output_dim=*/config.embedding_dim);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  164 |       });
      |       ~~ 
```

I can check the `zip_with.h` implementation.
</blockquote></details>

In the future a little more of the error message would be helpful (you can also just include a link to a paste of the full error output somewhere if you'd prefer), but I think in this case it's because the lambda should take the `pair` as `const &`, not as mutable `&`


<!-- Sent from Reviewable.io -->

2025-01-23 02:07 UTC, easyeasydev reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1532)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/include/models/dlrm/dlrm_config.struct.toml` line 45 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OB3Kl1v92e2wjIl_0uO:-OHFrVsz6F2RiYrN7PWw:bplcj5x) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/include/models/dlrm/dlrm_config.struct.toml#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

https://github.com/flexflow/flexflow-train/blob/master/lib/op-attrs/include/op-attrs/activation.enum.toml
</blockquote></details>

Converted it to an enum type.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 128 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OAUyBepDX4Q5mQhVaEL:-OHFoxna7VAAMKJSmqYH:bp3pdc6) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L128)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Based on https://github.com/flexflow/flexflow-train/blob/78307b0e8beb5d41ee003be8b5db168c2b3ef4e2/examples/cpp/DLRM/dlrm.cc#L138-L143 I'd say you want multiple different `tensor_guid_t`s, in which case you should use the `repeat` code snippet you included above (and if you get any build errors using it, send me the error message so I can help debug)
</blockquote></details>

Updated to use the `repeat`.
___
*[`lib/models/src/models/dlrm/dlrm.cc` line 145 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1532#-OAUwibW0-jZ9fWE2xWc:-OHFq9mI6pXvKciKSTrn:b-hb75qu) ([raw file](https://github.com/flexflow/flexflow-train/blob/aca2810dbea6c97b39bd8910f088a268d830d716/lib/models/src/models/dlrm/dlrm.cc#L145)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In the future a little more of the error message would be helpful (you can also just include a link to a paste of the full error output somewhere if you'd prefer), but I think in this case it's because the lambda should take the `pair` as `const &`, not as mutable `&`
</blockquote></details>

Thanks! This was indeed because of the `const`. I have updated this.


<!-- Sent from Reviewable.io -->

2025-02-10 00:27 UTC, lockshaw approved these changes
> Reviewed 5 of 5 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1532)* status: 2 of 22 files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2025-02-10 01:29 UTC, merged