Changed ff_dim to ff_dim_t, added in nonnegative_int type
flexflow/flexflow-train pull request #1533
Opened 2024-10-31 04:51 UTC by victorli2002

**Description of changes:**

- draft
- renamed ff_dim to ff_dim_t
- added a nonnegative_int type with some unit tests
- added a relative_ff_dim_t type for now (unused)

2024-11-16 00:52 UTC, Marsella8 requested changes
great PR! left some small comments and fyis, nothing too important : )

> Reviewed 15 of 32 files at r1, 70 of 70 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-:-OBmS3si1CdG-EpT2ZnY:b-h67a2j)* status: all files reviewed, 8 unresolved discussions (waiting on @lockshaw and @victorli2002)

___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmPe9A4RwG4jDs7QkG:-OBmPe9A4RwG4jDs7QkH:be6tk1b) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("slice(FFOrdered<T>, ff_dim_t, ff_dim_t)") {
> ```

Better to have a test case with 6 subcases, since this way you have to define d only once and you can then reuse it across subcases) (Or also 2 tests with 3 subcases each)
___
*[`lib/op-attrs/src/op-attrs/ops/concat.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmP1L_1X2wvGS3MuyO:-OBmP1L_1X2wvGS3MuyP:b1o2jk9) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ops/concat.cc#L50)):*
> ```cpp
>     }
>     std::map<ff_dim_t, size_t> returned_wrapped;
>     for (const auto &[key, value] : returned.value()) {
> ```

see `map_keys` in `utils/containers/map_keys.h`: )
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 342 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmL5OKAdSAvPa3Nizi:-OBmL5OKAdSAvPa3Nizj:b-j9k590) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L342)):*
> ```objc
> std::vector<ff_dim_t> inner_to_outer_idxs(FFOrdered<T> const &ff_ordered) {
>   std::vector<ff_dim_t> idxs;
>   for (size_t i = 0; i < ff_ordered.size(); i++) {
> ```

alternatively, you can also use range() in 'utils/containers/range.h' (containers in general is pretty awesome, there's a lot of useful functions), though obviously like this is perfectly fine. 
___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.h` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmK6xk5zBEDvogOzc_:-OBmK6xk5zBEDvogOzca:b2aw9kn) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/relative_ff_dim_t.h#L7)):*
> ```objc
> #include "rapidcheck.h"
> 
> namespace rc {
> ```

for rapidcheck support for dtgen types you can add the "rapidcheck" string in the features array (inside of the .struct.toml file). Not sure if it applies here, just an fyi : ) 
___
*[`lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmRlZbAt3yVuOQzvFL:-OBmRlZbAt3yVuOQzvFM:bsrp83y) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc#L26)):*
> ```cpp
>     nonnegative_int nn_int_2 = nonnegative_int{2};
>     SUBCASE("LHS: nonnegative_int, RHS: nonnegative_int, equal") {
>       CHECK((nn_int_1a == nn_int_1b) == true);
> ```

to add support for doctest fmting, take a look at `utils/fmt/` (this way you can do direct comparisons inside the `CHECK`)
___
*[`lib/op-attrs/src/op-attrs/ff_dim_t.cc` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmOM8LBel_AEtjT75V:-OBmOM8LBel_AEtjT75W:b-4nm9wz) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ff_dim_t.cc#L9)):*
> ```cpp
>                [](int value) { return FlexFlow::nonnegative_int(value); }));
> }
> } // namespace rc
> ```

see my rapidcheck comment
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 853 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmQLTIB1SMt-pZkPEf:-OBmQLTJ0kKO3jGIFmjq:b5dkygc) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L853)):*
> ```cpp
> 
>   stack_vector<ff_dim_t, MAX_TENSOR_DIM> axes_stack;
>   std::transform(axes.begin(),
> ```

better`utils/containers/transform.h` (if you haven't tried it, might misbehave with stack_vector)
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 123 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmN6-S8vMnxssi4IFZ:-OBmN6-S8vMnxssi4IF_:b-u50q98) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L123)):*
> ```objc
>       d,
>       std::optional<relative_ff_dim_t>{start},
>       std::optional<relative_ff_dim_t>{end});
> ```

template <typename T>
FFOrdered<T> slice(FFOrdered<T> const& d,
                   std::optional<relative_ff_dim_t> const& start = std::nullopt,
                   std::optional<relative_ff_dim_t> const& end = std::nullopt) {
    return relative_ff_dim_t_nonoverloaded_slice(d, start, end);
}

As an alternative to group together these 3 overloads? (ditto for the other 3 overloads). If you pass a value to a function that takes in an optional it will get implictly casted (and also handles the additional case of both being std::nullopt, not sure if you'd want that or not).



_Code quote:_
```objc
template <typename T>
FFOrdered<T> slice(FFOrdered<T> const &d,
                   std::nullopt_t const &start,
                   relative_ff_dim_t const &end) {
  return relative_ff_dim_t_nonoverloaded_slice(
      d,
      std::optional<relative_ff_dim_t>{start},
      std::optional<relative_ff_dim_t>{end});
}

template <typename T>
FFOrdered<T> slice(FFOrdered<T> const &d,
                   relative_ff_dim_t const &start,
                   std::nullopt_t const &end) {
  return relative_ff_dim_t_nonoverloaded_slice(
      d,
      std::optional<relative_ff_dim_t>{start},
      std::optional<relative_ff_dim_t>{end});
}

template <typename T>
FFOrdered<T> slice(FFOrdered<T> const &d,
                   relative_ff_dim_t const &start,
                   relative_ff_dim_t const &end) {
  return relative_ff_dim_t_nonoverloaded_slice(
      d,
      std::optional<relative_ff_dim_t>{start},
      std::optional<relative_ff_dim_t>{end});
```


<!-- Sent from Reviewable.io -->

2024-11-19 04:45 UTC, lockshaw requested changes
> Reviewed 15 of 32 files at r1, 70 of 70 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1533)* status: all files reviewed, 19 unresolved discussions (waiting on @Marsella8 and @victorli2002)

___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.h` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmK6xk5zBEDvogOzc_:-OBmUjQA1yZcUGbZ4Wmx:b-vdzjan) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/relative_ff_dim_t.h#L7)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

for rapidcheck support for dtgen types you can add the "rapidcheck" string in the features array (inside of the .struct.toml file). Not sure if it applies here, just an fyi : )
</blockquote></details>

Since `ff_dim_t` and `relative_ff_dim_t` are bounded by the `MAX_TENSOR_DIM`, unfortunately I don't think we can use the `dtgen` support as convenient as it would be.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 342 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmL5OKAdSAvPa3Nizi:-OC1j7TeA_wNIY0aOWzZ:b-pykh9f) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L342)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

alternatively, you can also use range() in 'utils/containers/range.h' (containers in general is pretty awesome, there's a lot of useful functions), though obviously like this is perfectly fine.
</blockquote></details>

`range` would definitely be good, but honestly a bunch of these index manipulation functions are super out-of-date and should probably just be removed entirely. @victorli2002 can you do a quick pass and remove any that aren't used anymore?
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 123 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmN6-S8vMnxssi4IFZ:-OC1iNBC3FWl6pcqO1iX:bqsifmm) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L123)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

template <typename T>
FFOrdered<T> slice(FFOrdered<T> const& d,
                   std::optional<relative_ff_dim_t> const& start = std::nullopt,
                   std::optional<relative_ff_dim_t> const& end = std::nullopt) {
    return relative_ff_dim_t_nonoverloaded_slice(d, start, end);
}

As an alternative to group together these 3 overloads? (ditto for the other 3 overloads). If you pass a value to a function that takes in an optional it will get implictly casted (and also handles the additional case of both being std::nullopt, not sure if you'd want that or not).
</blockquote></details>

IIRC we were having some issues with overload resolution functioning properly with the unified signature, though I unfortunately seem to have forgotten what the exact issue was. @victorli2002 if you want you could try changing to @Marsella8's proposed signature and see if anything breaks
___
*[`lib/op-attrs/src/op-attrs/ff_dim_t.cc` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmOM8LBel_AEtjT75V:-OC1hX7fE_AQDEnImNOk:b-pa3olu) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ff_dim_t.cc#L9)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

see my rapidcheck comment
</blockquote></details>

Link: https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmK6xk5zBEDvogOzc_
___
*[`lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmRlZbAt3yVuOQzvFL:-OC1daxF3Q6vue_Fp4kF:b-543g1f) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc#L26)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

to add support for doctest fmting, take a look at `utils/fmt/` (this way you can do direct comparisons inside the `CHECK`)
</blockquote></details>

IIRC all ostream-able types should automatically be printable by doctest. What error are you running into @victorli2002? 

@Marsella8 is correct that this code should be refactored to `CHECK(nn_int_1a == nn_int_1b)`
___
*[`lib/local-execution/src/legion_tensor_shape.cc` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmTbGH8ZWDvvC63ZM5:-OBmTbGH8ZWDvvC63ZM6:b-lxp9l5) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/local-execution/src/legion_tensor_shape.cc#L10)):*
> ```cpp
> }
> 
> legion_dim_t legion_dim_from_ff_dim(ff_dim_t ff_dim, TensorShape const &shape) {
> ```

Might be better to just forward the call to `legion_dim_from_ff_dim(ff_dim_t, int)` in `legion_dim.cc` (doesn't really have to do with your changes, but while we're looking at this file)
___
*[`lib/local-execution/src/ops/split.cc` line 109 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmUInO6tzubcBkYu2Z:-OBmUInO6tzubcBkYu2_:bfe5axs) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/local-execution/src/ops/split.cc#L109)):*
> ```cpp
>                     out_block_size[i],
>                     output_grad.shape,
>                     attrs.axis.value.get_value());
> ```

Might be better to instead change the signature of `calc_block_size`?



_Code quote:_
```cpp
attrs.axis.value.get_value());
```
___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.h` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmV3Qb9MgEyaQyJc9_:-OBmV3Qb9MgEyaQyJc9a:b-ihjg6m) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/relative_ff_dim_t.h#L9)):*
> ```objc
> namespace rc {
> template <>
> struct Arbitrary<FlexFlow::relative_ff_dim_t> {
> ```

Not a big deal, but absolute namespaces are a bit less ambiguous



_Suggestion:_
```objc
struct Arbitrary<::FlexFlow::relative_ff_dim_t> {
```
___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.struct.toml` line 10 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmVCgnEkcCMbhYx963:-OBmVCgnEkcCMbhYx964:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/relative_ff_dim_t.struct.toml#L10)):*
> ```TOML
>   "json",
>   "fmt",
> ]
> ```





_Suggestion:_
```TOML
features = [
  "eq",
  "ord",
  "hash",
  "json",
  "fmt",
  "rapidcheck",
]
```
___
*[`lib/utils/include/utils/nonnegative_int/nonnegative_int.h` line 48 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1evWW0Chs8-_DR9kl:-OC1evWXD3U81Mla9G6-:b-kxsavf) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/utils/include/utils/nonnegative_int/nonnegative_int.h#L48)):*
> ```objc
>   int value_;
> };
> } // namespace FlexFlow
> ```

Add support for `fmt` (https://fmt.dev/11.0/)



_Suggestion:_
```objc
private:
  int value_;
};

int format_as(nonnegative_int);

} // namespace FlexFlow
```
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/enumerate.h` line 21 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmVKqhA5dr05MRz2E8:-OBmVKqhA5dr05MRz2E9:b-16g9ux) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d5140d5e98c18e73ce576673aa34022ad6d804f/lib/op-attrs/include/op-attrs/dim_ordered/enumerate.h#L21)):*
> ```objc
> std::map<ff_dim_t, T> enumerate(FFOrdered<T> const &ff_ordered) {
>   std::map<ff_dim_t, T> result;
>   for (int raw_ff_dim : count(ff_ordered.size())) {
> ```

We could probably even change `count` to return `nonnegative_int`s (doesn't have to be done now, but could be an option in the future)

 [...]

2024-11-27 09:25 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1533)* status: all files reviewed, 19 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/kernels/test/src/test_transpose_kernel.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmTO2ZAywsm-JSRabO:-OCeuaJJAYwXKFOz0oqP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/kernels/test/src/test_transpose_kernel.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Shouldn't this be `1` based on the old code?
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 342 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmL5OKAdSAvPa3Nizi:-OCewjLuA9eJP_9Wi0j2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L342)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`range` would definitely be good, but honestly a bunch of these index manipulation functions are super out-of-date and should probably just be removed entirely. @victorli2002 can you do a quick pass and remove any that aren't used anymore?
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 123 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmN6-S8vMnxssi4IFZ:-OCgvoTXD5nqJePbTRTh:baaaioe) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L123)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

IIRC we were having some issues with overload resolution functioning properly with the unified signature, though I unfortunately seem to have forgotten what the exact issue was. @victorli2002 if you want you could try changing to @Marsella8's proposed signature and see if anything breaks
</blockquote></details>

Tried it, got the following error message (which iirc was the same message I got earlier).



_Code snippet:_
```objc
/home/vli42/ff/nn_int/lib/op-attrs/include/op-attrs/dim_ordered/slice.h:17:21: error: could not convert 'FlexFlow::transform<FlexFlow::nonoverloaded_slice<FlexFlow::ff_dim_t, int>(const FlexFlow::DimOrdered<FlexFlow::ff_dim_t, int>&, const std::optional<FlexFlow::ff_dim_t>&, const std::optional<FlexFlow::ff_dim_t>&)::<lambda(const std::optional<FlexFlow::ff_dim_t>&)>::<lambda(const FlexFlow::ff_dim_t&)>, FlexFlow::ff_dim_t>((* & idx), <lambda closure object>FlexFlow::nonoverloaded_slice<FlexFlow::ff_dim_t, int>(const FlexFlow::DimOrdered<FlexFlow::ff_dim_t, int>&, const std::optional<FlexFlow::ff_dim_t>&, const std::optional<FlexFlow::ff_dim_t>&)::<lambda(const std::optional<FlexFlow::ff_dim_t>&)>::<lambda(const FlexFlow::ff_dim_t&)>{})' from 'optional<FlexFlow::nonnegative_int>' to 'optional<int>'
   17 |     return transform(idx, [](Idx const &i) { return i.value; });
      |            ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     optional<FlexFlow::nonnegative_int>
```
___
*[`lib/op-attrs/src/op-attrs/ops/combine.cc` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1bqjDBVxsTuwEpxaO:-OCglBDK5I3OasmrFSXJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ops/combine.cc#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might not be the worst idea to add a conversion function from `ff_dim_t` to `relative_ff_dim_t`?
</blockquote></details>

Done.
___
*[`lib/op-attrs/src/op-attrs/ops/concat.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmP1L_1X2wvGS3MuyO:-OCezz36ElCfmBcNufvZ:b-uj7kle) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ops/concat.cc#L50)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

see `map_keys` in `utils/containers/map_keys.h`: )
</blockquote></details>

That map_keys takes std::unordered_map, if I'm not mistaken. Is there a good way to use it with std::map?
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmPe9A4RwG4jDs7QkG:-OCezwEm8ucT-bUyIsaY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L7)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Better to have a test case with 6 subcases, since this way you have to define d only once and you can then reuse it across subcases) (Or also 2 tests with 3 subcases each)
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 795 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1cRiA2yzdRqpJVCaO:-OCgvhLa2fPnmRXP0wWn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L795)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We actually probably want `axis` to be treated as relative here (i.e., this function should take in `axis`, wrap it as a `relative_ff_dim_t`, and then do the conversion to `ff_dim_t` and store the `ff_dim_t` in `attrs`)
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 813 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1cde25uH3vh3y8amx:-OCgkMTZ6h76yxfwWGdS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L813)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We actually probably want `start_dim` and `end_dim` to be treated as relative here
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 853 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmQLTIB1SMt-pZkPEf:-OCf-9xf2fn4VpMCvMla:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L853)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

better`utils/containers/transform.h` (if you haven't tried it, might misbehave with stack_vector)
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 900 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1ct6W1yW4BFzLsEXV:-OCgkN5bER8L0YUiwLAG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L900)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`maybe_dim` here should be treated as relative (generally any dim in the `ComputationGraphBuilder` interface should be treated as `relative`)
</blockquote></details>

Done.
___
*[`lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc` line 26 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmRlZbAt3yVuOQzvFL:-OCgsD89EFDQNbsfuczX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

IIRC all ostream-able types should automatically be printable by doctest. What error are you running into @victorli2002? 

@Marsella8 is correct that this code should be refactored to `CHECK(nn_int_1a == nn_int_1b)`
</blockquote></details>

Done.
___
*[`lib/utils/test/src/ [...]

2024-11-28 05:01 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1533)* status: 67 of 88 files reviewed, 19 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.variant.toml` line 17 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OBmUS3D-G27z0ujTl_5:-OCl8DsG8kGklgKQ2h3C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.variant.toml#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not sure this should be `relative` (just style-wise/semantically). What breaks if you make it `ff_dim_t`?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/nonnegative_int/nonnegative_int.h` line 48 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1533#-OC1evWW0Chs8-_DR9kl:-OCl6L2ZA0yzmTAgfgET:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/utils/include/utils/nonnegative_int/nonnegative_int.h#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add support for `fmt` (https://fmt.dev/11.0/)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-20 08:04 UTC, lockshaw requested changes
> Reviewed 21 of 21 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 20 unresolved discussions (waiting on @Marsella8 and @victorli2002)

___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.struct.toml` line 10 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmVCgnEkcCMbhYx963:-OEXnlV095rJ63z1MmrE:bxlacxn) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/relative_ff_dim_t.struct.toml#L10)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

The original doesn't have ff_dim.struct.toml; why do we need it here?
</blockquote></details>

True, this shouldn't be here due to https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmK6xk5zBEDvogOzc_
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 123 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmN6-S8vMnxssi4IFZ:-OEY4MqcCu2Zz2clinyD:b-vc0s2e) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L123)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

Tried it, got the following error message (which iirc was the same message I got earlier).
</blockquote></details>

That type error seems unsurprising: line 17 declares that it will return a `std::optional<int>`, but instead of returning `i.value.get_value()` you return `i.value`, which would result in returning a `std::optional<nonnegative_int>`. There very well may be a type issue, but this doesn't seem like one of them.

I'd recommend using `utils/archetypes/value_type.h` to force these overloads to be typechecked, e.g., https://github.com/flexflow/FlexFlow/blob/89c143d33b9e02faf8d6818a9c47b0d5da68a610/lib/utils/src/utils/containers/get_all_assignments.cc#L6-L10
___
*[`lib/op-attrs/src/op-attrs/ops/concat.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmP1L_1X2wvGS3MuyO:-OEXomor3v93ig-l-v_C:b-r9na9d) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ops/concat.cc#L50)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

That map_keys takes std::unordered_map, if I'm not mistaken. Is there a good way to use it with std::map?
</blockquote></details>

Add an overload for `std::map`--we often just materialize the overloads lazily as needed rather than trying to get them all up-front
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 7 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmPe9A4RwG4jDs7QkG:-OEY3W9E0ZpsWRwiLjhp:b-f5wjtx) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L7)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In general we prefer one test-case per function, but in cases like this where there's a huge degree of overlap combining them can be a good idea
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 853 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmQLTIB1SMt-pZkPEf:-OEXpo8cDK0DJABDPWkn:b-n09gor) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L853)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing `std::transform`?
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpHjE7my4jALCHhtQ:-OEXpHjFE1ldSUAO9Lni:bcxwyq0) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("FF_DIM_T_TO_RELATIVE_FF_DIM_T") {
> ```

Remove all caps?



_Code quote:_
```cpp
 TEST_CASE("FF_DIM_T_TO_RELATIVE_FF_DIM_T") {
```
___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.h` line 9 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXn_XM8ntstNe8_gYu:-OEXn_XU3WvM-76UNAof:b-k5ud3m) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/include/op-attrs/relative_ff_dim_t.h#L9)):*
> ```objc
> 
> namespace FlexFlow {
> ff_dim_t relative_ff_dim_t_to_ff_dim_t(relative_ff_dim_t ff_dim, int input_dim);
> ```

Could make this a `nonnegative_int` if you wanted



_Code quote:_
```objc
int input_dim)
```
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY3fhFCpuzd59WL6PY:-OEY3fhFCpuzd59WL6PZ:bem7ma8) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("slice(FFOrdered<T>, ..., ...") {
> ```

Test error cases (e.g., out-of-bounds behavior, start being > stop, etc.)
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpVFi1QQBHSQh0Efh:-OEXpVFi1QQBHSQh0Efi:bcxwyq0) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("RELATIVE_FF_DIM_T_TO_FF_DIM_T") {
> ```

Remove all caps?
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpRMp1Sc-iyB-JdGc:-OEXpRMp1Sc-iyB-JdGd:b-b951ls) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L34)):*
> ```cpp
>       relative_ff_dim_t relative_ff_dim = relative_ff_dim_t{-10};
>       CHECK_THROWS(relative_ff_dim_t_to_ff_dim_t(relative_ff_dim, input_dim));
>     }
> ```

Also check the other out of range (i.e., too high)



_Code quote:_
```cpp
    SUBCASE("OUT OF RANGE") {
      relative_ff_dim_t relative_ff_dim = relative_ff_dim_t{-10};
      CHECK_THROWS(relative_ff_dim_t_to_ff_dim_t(relative_ff_dim, input_dim));
    }
```
___
*[`lib/op-attrs/src/op-attrs/relative_ff_dim_t.cc` line 5 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXo9oz-_Wd1qTSwidz:-OEXo9p-8R5ZTi4ZNQEL:bn04szd) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/src/op-attrs/relative_ff_dim_t.cc#L5)):*
> ```cpp
> 
> namespace FlexFlow {
> ff_dim_t relative_ff_dim_t_to_ff_dim_t(relative_ff_dim_t ff_dim,
> ```

What's the expected behavior if `ff_dim.value` > `input_dim`? I'm fine with the behavior in the current code below, just make sure it's tested
___
*[`lib/op-attrs/src/op-attrs/ops/layer_norm.cc` line 169 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXov_ACIVNZvmAKFqK:-OEXov_ACIVNZvmAKFqL:bvo1cf) ([raw file](https://github.com/flexflow/flexflow-train/blob/e56aeb7a7369d403a9e25045f4ae5e3e634d5ecb/lib/op-attrs/src/op-attrs/ops/layer_norm.cc#L169)):*
> ```cpp
>       transform(non_layer_norm_dim_idxs, [&](ff_dim_t const &dim_idx) {
>         return shard_dim_at_idx(input_shape,
>                                 ff_dim_t_to_relative_ff_dim_t(dim_idx));
> ```

I'd prefer `relative_ff_dim_t_from_ff_dim_t` as the sides of the name match up nicer (i.e., the argument type is next to where the argument actually is) (and usually same for other conversion functions)



_Code quote:_
```cpp
ff_di [...]

2024-12-24 06:32 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: 72 of 88 files reviewed, 20 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/op-attrs/include/op-attrs/relative_ff_dim_t.h` line 9 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXn_XM8ntstNe8_gYu:-OErLyMPBrG39VpcSGWz:bnw452e) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/include/op-attrs/relative_ff_dim_t.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Could make this a `nonnegative_int` if you wanted
</blockquote></details>

I think this change would fight better in the later PR where I put nonnegative_int in more places.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 335 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY2ynBBEtz6Gnxtwn0:-OEaCpbvDT_cl4Q5si7P:b-liybub) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L335)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Out of curiosity, where is this used?
</blockquote></details>

it's in local-execution/src/ops/transpose.cc
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_shape.cc` line 144 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY3IOE2hor5nRk6RpX:-OEaDn4_DJaH5rgeWSbb:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/src/op-attrs/parallel_tensor_shape.cc#L144)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer brace initialization
</blockquote></details>

Done.
___
*[`lib/op-attrs/src/op-attrs/relative_ff_dim_t.cc` line 5 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXo9oz-_Wd1qTSwidz:-OEmFiik6pY-JwEnLwCH:b6ginfs) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/src/op-attrs/relative_ff_dim_t.cc#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's the expected behavior if `ff_dim.value` > `input_dim`? I'm fine with the behavior in the current code below, just make sure it's tested
</blockquote></details>

Added a test; currently it just makes a ff_dim_t with the same value as ff_dim.value.
___
*[`lib/op-attrs/src/op-attrs/ops/concat.cc` line 50 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmP1L_1X2wvGS3MuyO:-OEpVfwg3g73M_cHeBMU:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/src/op-attrs/ops/concat.cc#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add an overload for `std::map`--we often just materialize the overloads lazily as needed rather than trying to get them all up-front
</blockquote></details>

Done.
___
*[`lib/op-attrs/src/op-attrs/ops/layer_norm.cc` line 169 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXov_ACIVNZvmAKFqK:-OEm9MUR7V44gVVUzzFt:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/src/op-attrs/ops/layer_norm.cc#L169)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'd prefer `relative_ff_dim_t_from_ff_dim_t` as the sides of the name match up nicer (i.e., the argument type is next to where the argument actually is) (and usually same for other conversion functions)
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpHjE7my4jALCHhtQ:-OEaEjuU6A3lKVHHH4uB:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove all caps?
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpVFi1QQBHSQh0Efh:-OEaEvNL2Fc0BCA_Uwhf:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove all caps?
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEXpRMp1Sc-iyB-JdGc:-OEaHaSw8RP3zCvznJIr:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also check the other out of range (i.e., too high)
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 7 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY3fhFCpuzd59WL6PY:-OEaPPti1OotuDy2MiB7:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Test error cases (e.g., out-of-bounds behavior, start being > stop, etc.)
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 853 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmQLTIB1SMt-pZkPEf:-OEaRBKB7LmEmDqwhww5:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/pcg/src/pcg/computation_graph_builder.cc#L853)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm still seeing `std::transform`?
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 337 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY2uWh0_ecMXMXvlmM:-OEaDWVyES6vHjAfBwy9:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L337)):*
> ```objc
> std::vector<ff_dim_t> inner_to_outer_idxs(FFOrdered<T> const &ff_ordered) {
>   std::vector<ff_dim_t> idxs;
>   for (int i : range(0, ff_ordered.size())) {
> ```

Done.
___
*[`lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc` line 250 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY2Jo71Ky5lDTrxTw5:-OEm9dx_2lsbht4vGQhW:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/utils/test/src/utils/nonnegative_int/nonnegative_int.cc#L250)):*
> ```cpp
>   }
> 
>   TEST_CASE("nonnegative int fmt::to_string") {
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_shape.cc` line 146 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY3O2X4n4Q7-rreJl1:-OEaDmqyAcFSp2JiCDRB:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/src/op-attrs/parallel_tensor_shape.cc#L146)):*
> ```cpp
>            return parallel_tensor_dim_idx_t(ff_dim_t{nonnegative_int{idx}});
>          }));
>   indices.insert(parallel_tensor_dim_idx_t(ReplicaType::SUM));
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_shape.cc` line 147 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY3QGyAywQv0XYenBU:-OEaDmhb9bzhKiD3I8sS:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/3 [...]

2024-12-25 19:29 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: 71 of 88 files reviewed, 20 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 123 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OBmN6-S8vMnxssi4IFZ:-OEw82FI2hs6N1wxGYwk:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/35bd5d9e1a39f835d8984c9f6a7f9ed63d524617/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L123)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

That type error seems unsurprising: line 17 declares that it will return a `std::optional<int>`, but instead of returning `i.value.get_value()` you return `i.value`, which would result in returning a `std::optional<nonnegative_int>`. There very well may be a type issue, but this doesn't seem like one of them.

I'd recommend using `utils/archetypes/value_type.h` to force these overloads to be typechecked, e.g., https://github.com/flexflow/FlexFlow/blob/89c143d33b9e02faf8d6818a9c47b0d5da68a610/lib/utils/src/utils/containers/get_all_assignments.cc#L6-L10
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-10 01:04 UTC, lockshaw requested changes
> Reviewed 16 of 16 files at r5, 1 of 1 files at r7, all commit messages.
> Dismissed @Marsella8 from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 17 unresolved discussions (waiting on @victorli2002)

___
*[`lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h` line 335 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OEY2ynBBEtz6Gnxtwn0:-OGCipeF28z-YBJIRiNf:b-l7ccd0) ([raw file](https://github.com/flexflow/flexflow-train/blob/332a119ce54a4b65c8282bf5c4e1a6a1aae0587a/lib/op-attrs/include/op-attrs/dim_ordered/dim_ordered.h#L335)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

it's in local-execution/src/ops/transpose.cc
</blockquote></details>

If that's the only place, I'd just inline this function there and then remove the definition here--I don't think this is an operation that necessarily makes a whole lot of sense to have on `FFOrdered`
___
*[`lib/op-attrs/include/op-attrs/dim_ordered/slice.h` line 13 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCfe53DWNQI8wUiWwo:-OGCfe53DWNQI8wUiWwp:b-kh31fg) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/include/op-attrs/dim_ordered/slice.h#L13)):*
> ```objc
> namespace FlexFlow {
> 
> using T = value_type<0>;
> ```

Should be done in the `slice.cc` file, not in the `.h` file



_Code quote:_
```objc
using T = value_type<0>;
```
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 7 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgjkN28g07TL8zPVI:-OGCgjkN28g07TL8zPVJ:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("ff_dim_to_to_relative_ff_dim_t") {
> ```





_Suggestion:_
```cpp
  TEST_CASE("relative_ff_dim_t_from_ff_dim_t") {
```
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 8 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgdAtD6Y5Gibun0-c:-OGCgdAtD6Y5Gibun0-d:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L8)):*
> ```cpp
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("ff_dim_to_to_relative_ff_dim_t") {
>     SUBCASE("Zero") {
> ```





_Suggestion:_
```cpp
    SUBCASE("absolute index is zero") {
```
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgngP0QL3mXcD_6Ux:-OGCgngP0QL3mXcD_6Uy:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L15)):*
> ```cpp
>     }
> 
>     SUBCASE("Positive") {
> ```





_Suggestion:_
```cpp
    SUBCASE("absolute index is positive") {
```
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 10 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgycoATe1qWdlCORo:-OGCgycp0wn79-8WnvIH:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L10)):*
> ```cpp
>     int input_dim = 5;
> 
>     SUBCASE("Zero") {
> ```





_Suggestion:_
```cpp
    SUBCASE("relative index is zero") {
```
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCguNL9AlUoxUJyhBX:-OGCguNL9AlUoxUJyhBY:b45h) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L13)):*
> ```cpp
>       relative_ff_dim_t relative_ff_dim = relative_ff_dim_t{0};
>       ff_dim_t ff_dim =
>           ff_dim_t_from_relative_ff_dim_t_ff_dim_t(relative_ff_dim, input_dim);
> ```





_Suggestion:_
```cpp
ff_dim_t_from_relative_ff_dim_t
```
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 17 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCh09xBn5g9BSJo7MY:-OGCh09xBn5g9BSJo7MZ:b45h) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L17)):*
> ```cpp
>     }
> 
>     SUBCASE("Positive") {
> ```





_Suggestion:_
```cpp
   SUBCASE("relative index is positive") {
```
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 24 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGChEBc2XQkbv_ZvV_g:-OGChEBc2XQkbv_ZvV_h:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L24)):*
> ```cpp
>     }
> 
>     SUBCASE("Negative") {
> ```





_Suggestion:_
```cpp
    SUBCASE("relative index is negative") {
```
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 31 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGChGRoCo5WuoYZBu4s:-OGChGRoCo5WuoYZBu4t:b-bobmgt) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L31)):*
> ```cpp
>     }
> 
>     SUBCASE("Negative out of range") {
> ```

Ideally two nested subcases under "relative index is negative"--one where it is in range and one where it is out of range
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 42 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCh5-qEzMr4wj1Knby:-OGCh5-r6JIAmUIE1IYZ:b-k4sxt9) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L42)):*
> ```cpp
>           ff_dim_t_from_relative_ff_dim_t_ff_dim_t(relative_ff_dim, input_dim);
>       CHECK(ff_dim == ff_dim_t{nonnegative_int{10}});
>     }
> ```

Ideally two nested subcases under "relative index is positive"--one where it is in range, and one where it is out of range



_Code quote:_
```cpp
    SUBCASE("Positive out of range") {
      relative_ff_dim_t relative_ff_dim = relative_ff_dim_t{10};
      ff_dim_t ff_dim =
          ff_dim_t_from_relative_ff_dim_t_ff_dim_t(relative_ff_dim, input_dim);
      CHECK(ff_dim == ff_dim_t{nonnegative_int{10}});
    }
```
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 68 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCjSSp4QgYD081F41V:-OGCjSSp4QgYD081F41W:b-kfg9c4) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L68)):*
> ```cpp
>       CHECK(result == correct);
>     }
>     SUBCASE("start index > stop index") {
> ```

Is there a reason we don't throw in this case?
___
*[`lib/op-attrs/src/op-attrs/ff_dim_t.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCg0t88zHpIQzk38u-:-OGCg0t88zHpIQzk38u0:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/src/op-attrs/ff_dim_t.cc#L13)):*
> ```cpp
>   return gen::construct<::FlexFlow::ff_dim_t>(
>       gen::map(gen::inRange<int>(0, MAX_TENSOR_DIM),
>                [](int value) { return FlexFlow::nonnegative_int(value); }));
> ```





_Suggestion:_
```cpp
               [](int value) { return FlexFlow::nonnegative_int{value}; }));
```
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 865 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCi53q5nhl424-FRet:-OGCi53q5nhl424-FReu:bqc6noz) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/pcg/src/pcg/computation_graph_builder.cc#L865)):*
> ```cpp
>             std::back_inserter(axes_stack [...]

2025-01-10 22:45 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 17 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 31 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGChGRoCo5WuoYZBu4s:-OGEZyFJ0CZ4aSVaQoPc:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L31)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally two nested subcases under "relative index is negative"--one where it is in range and one where it is out of range
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 42 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCh5-qEzMr4wj1Knby:-OGEZylfEo95US_432Lv:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L42)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally two nested subcases under "relative index is positive"--one where it is in range, and one where it is out of range
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc` line 68 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCjSSp4QgYD081F41V:-OGEBUh6C1Mn-nPxMIo3:b-zh3dwv) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/dim_ordered/slice.cc#L68)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is there a reason we don't throw in this case?
</blockquote></details>

That's just how the behavior works atm, can fix if needed. (It uses the `subvec` function)
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 865 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCi53q5nhl424-FRet:-OGHMw_z8E_jLeUxQvBj:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/pcg/src/pcg/computation_graph_builder.cc#L865)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Normalization should be done before the bounds-checking on `axes`, not afterward
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 926 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCi09f6__69p3ydeIt:-OGHM5R440S7ReJOfTVO:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/pcg/src/pcg/computation_graph_builder.cc#L926)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Normalization should be ideally done before the bounds checking on `dim`
</blockquote></details>

Done.
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 7 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgjkN28g07TL8zPVI:-OGHDhsGARBTG7NImqnD:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L7)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("ff_dim_to_to_relative_ff_dim_t") {
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 8 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgdAtD6Y5Gibun0-c:-OGHDiKG4eLsgDiIJHef:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L8)):*
> ```cpp
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("ff_dim_to_to_relative_ff_dim_t") {
>     SUBCASE("Zero") {
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/ff_dim_t.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgngP0QL3mXcD_6Ux:-OGHDifU3o-FWXr3eTAE:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/ff_dim_t.cc#L15)):*
> ```cpp
>     }
> 
>     SUBCASE("Positive") {
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 10 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCgycoATe1qWdlCORo:-OGEIYu7AHnAxUAi46yq:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L10)):*
> ```cpp
>     int input_dim = 5;
> 
>     SUBCASE("Zero") {
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCguNL9AlUoxUJyhBX:-OGEIqImDxU9FRzfXZZt:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L13)):*
> ```cpp
>       relative_ff_dim_t relative_ff_dim = relative_ff_dim_t{0};
>       ff_dim_t ff_dim =
>           ff_dim_t_from_relative_ff_dim_t_ff_dim_t(relative_ff_dim, input_dim);
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 17 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCh09xBn5g9BSJo7MY:-OGEJM5y9IT3igt3ZmEY:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L17)):*
> ```cpp
>     }
> 
>     SUBCASE("Positive") {
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc` line 24 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGChEBc2XQkbv_ZvV_g:-OGEJMWH03nDtc_ccH7W:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/test/src/op-attrs/relative_ff_dim_t.cc#L24)):*
> ```cpp
>     }
> 
>     SUBCASE("Negative") {
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/ff_dim_t.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGCg0t88zHpIQzk38u-:-OGHCe7v-BGe2hgBkA7Y:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/op-attrs/src/op-attrs/ff_dim_t.cc#L13)):*
> ```cpp
>   return gen::construct<::FlexFlow::ff_dim_t>(
>       gen::map(gen::inRange<int>(0, MAX_TENSOR_DIM),
>                [](int value) { return FlexFlow::nonnegative_int(value); }));
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-15 03:03 UTC, lockshaw requested changes
> Reviewed 28 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 13 unresolved discussions (waiting on @victorli2002)

___
*[`lib/utils/src/utils/stack_vector/stack_vector_of.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrhBv8xf52WS9KDb7:-OGbrhBv8xf52WS9KDb8:bbpkvwx) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector_of.cc#L1)):*
> ```cpp
> #include "utils/stack_vector/stack_vector_of.h"
> ```

Add explicit instantiation of `stack_vector_of` for `stack_vector<value_type, ...>`
___
*[`lib/local-execution/src/ops/transpose.cc` line 43 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbsNQUD3UnNuDDTF_b:-OGbsNQUD3UnNuDDTF_c:b-61bmvn) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L43)):*
> ```cpp
>   auto const &attrs = acc.get_argument<TransposeAttrs>(ATTRS);
>   std::vector<ff_dim_t> perm;
>   size_t const &size = attrs.perm.size();
> ```

Don't use variables with reference type unless you're certain they're useful (which in this case it's not, the pointer is probably no smaller than the size_t anyway)



_Suggestion:_
```cpp
size_t size = attrs.perm.size();
```
___
*[`lib/local-execution/src/ops/transpose.cc` line 46 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbu--g51Z42rM5ubX4:-OGbu--h0GdCXzQ9f0dS:bbwrttv) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L46)):*
> ```cpp
>   for (size_t const i : range(size)) {
>     perm.push_back(ff_dim_t{nonnegative_int{size - i - 1}});
>   }
> ```

Avoid unnecessary `const`



_Suggestion:_
```cpp
  for (size_t i : range(size)) {
    perm.push_back(ff_dim_t{nonnegative_int{size - i - 1}});
  }
```
___
*[`lib/local-execution/src/ops/transpose.cc` line 46 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbuDJ86W1_B-fCgFzI:-OGbuDJ86W1_B-fCgFzJ:b-yq9xw9) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L46)):*
> ```cpp
>   for (size_t const i : range(size)) {
>     perm.push_back(ff_dim_t{nonnegative_int{size - i - 1}});
>   }
> ```

Prefer performing multi-step initialization in its own block unless it's essentially the only thing in the current block



_Suggestion:_
```cpp
  std::vector<ff_dim_t> perm = [&] {
    std::vector<ff_dim_t> result;
    size_t size = attrs.perm.size();
    for (size_t const i : range(size)) {
      result.push_back(ff_dim_t{nonnegative_int{size - i - 1}});
    }
    return result;
  }();
```
___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGbrp5KEtu1PBYldszG:bli6m5g) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
> ```cpp
> #include "utils/stack_vector/stack_vector.h"
> ```

Add explicit instantiation of `stack_vector<value_type, ...>`
___
*[`lib/op-attrs/src/op-attrs/dim_ordered/slice.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbqlNQ80tVpdJyJhhY:-OGbqlNQ80tVpdJyJhhZ:b-h9h2r0) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/op-attrs/src/op-attrs/dim_ordered/slice.cc#L11)):*
> ```cpp
> using T = value_type<0>;
> 
> } // namespace FlexFlow
> ```

You actually have to instantiate the template functions (the `using T` is just declaring a type alias)



_Suggestion:_
```cpp
namespace FlexFlow {

using T = value_type<0>;

template
  FFOrdered<T> ff_dim_t_nonoverloaded_slice(FFOrdered<T> const &d,
                                            std::optional<ff_dim_t> const &start,
                                            std::optional<ff_dim_t> const &end);

template
  FFOrdered<T> relative_ff_dim_t_nonoverloaded_slice(
    FFOrdered<T> const &d,
    std::optional<relative_ff_dim_t> const &start,
    std::optional<relative_ff_dim_t> const &end);

template
  FFOrdered<T> slice(FFOrdered<T> const &d,
                     std::optional<ff_dim_t> const &start,
                     std::optional<ff_dim_t> const &end);

template
  FFOrdered<T> slice(FFOrdered<T> const &d,
                     std::optional<relative_ff_dim_t> const &start,
                     std::optional<relative_ff_dim_t> const &end);

} // namespace FlexFlow
```
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 860 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbswhBCQXdCU0Creyp:-OGbswhBCQXdCU0Creyq:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/pcg/src/pcg/computation_graph_builder.cc#L860)):*
> ```cpp
>   if (any_of(axes_stack, [&](ff_dim_t axis) {
>         return axis.value >= num_dims(input_shape);
>       })) {
> ```





_Suggestion:_
```cpp
  auto resolve_dim_idx = [&](int dim_idx) {
    return ff_dim_t_from_relative_ff_dim_t(relative_ff_dim_t{axis},
                                           num_dims(input_shape));
  };
  
  stack_vector<ff_dim_t, MAX_TENSOR_DIM> axes_stack =
      stack_vector_of<MAX_TENSOR_DIM>(transform(axes, resolve_dim_idx));

  if (any_of(axes_stack, [&](ff_dim_t axis) {
        return axis.value >= num_dims(input_shape);
      })) {
```
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 860 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbtHvpCNeHjvpy7doQ:-OGbtHvqEfd20zbDnjXC:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/pcg/src/pcg/computation_graph_builder.cc#L860)):*
> ```cpp
>   if (any_of(axes_stack, [&](ff_dim_t axis) {
>         return axis.value >= num_dims(input_shape);
>       })) {
> ```





_Suggestion:_
```cpp
tensor_guid_t ComputationGraphBuilder::layer_norm(
    tensor_guid_t const &input,
    std::vector<int> const &relative_axes,
    bool elementwise_affine,
    float eps,
    std::optional<std::string> const &maybe_name) {

  TensorShape input_shape = this->get_shape(input);

  stack_vector<ff_dim_t, MAX_TENSOR_DIM> axes =
      stack_vector_of<MAX_TENSOR_DIM>(transform(relative_axes, [&](int axis) {
        return ff_dim_t_from_relative_ff_dim_t(relative_ff_dim_t{axis},
                                               num_dims(input_shape));
      }));

  if (any_of(axes, [&](ff_dim_t axis) {
        return axis.value >= num_dims(input_shape);
      })) {
```
___
*[`lib/utils/include/utils/stack_vector/stack_vector_of.h` line 8 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbranw8UrG5AsdNgyM:-OGbranw8UrG5AsdNgyN:bp6dgti) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/include/utils/stack_vector/stack_vector_of.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> template <size_t max_size, typename C, typename E = typename C::value_type>
> ```

We generally have template params in ALL_CAPS



_Suggestion:_
```objc
template <size_t MAX_SIZE, typename C, typename E = typename C::value_type>
```
___
*[`lib/utils/test/src/utils/stack_vector/stack_vector_of.cc` line 15 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbs1FeAQiwbWo53op_:-OGbs1FeAQiwbWo53opa:bqktwjz) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/test/src/utils/stack_vector/stack_vector_of.cc#L15)):*
> ```cpp
>     CHECK(result[0] == 1);
>     CHECK(result[1] == 2);
>     CHECK(result[2] == 3);
> ```

Prefer `.at` for bounds-checking



_Suggestion:_
```cpp
    CHECK(result.at(0) == 1);
    CHECK(result.at( [...]

2025-01-15 05:07 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 13 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/src/ops/transpose.cc` line 43 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbsNQUD3UnNuDDTF_b:-OGbxzO5399ViP-VDsDl:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't use variables with reference type unless you're certain they're useful (which in this case it's not, the pointer is probably no smaller than the size_t anyway)
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/transpose.cc` line 46 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbu--g51Z42rM5ubX4:-OGby0USDi_hUDoawMFH:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Avoid unnecessary `const`
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/transpose.cc` line 46 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbuDJ86W1_B-fCgFzI:-OGbzkD54JFwKnPFlwxQ:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/local-execution/src/ops/transpose.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer performing multi-step initialization in its own block unless it's essentially the only thing in the current block
</blockquote></details>

Done.
___
*[`lib/op-attrs/src/op-attrs/dim_ordered/slice.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbqlNQ80tVpdJyJhhY:-OGcKLrQ9ylmEJrz4M44:bc985pt) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/op-attrs/src/op-attrs/dim_ordered/slice.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You actually have to instantiate the template functions (the `using T` is just declaring a type alias)
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/U90ppmrTisrQKBmObYVrPCIc/image.png)
Getting these errors
___
*[`lib/utils/include/utils/stack_vector/stack_vector_of.h` line 8 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbranw8UrG5AsdNgyM:-OGc1NyiA4Zp3CDoRz_a:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/include/utils/stack_vector/stack_vector_of.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We generally have template params in ALL_CAPS
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGcKRTZ207MBbIJYtqx:balyu9u) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add explicit instantiation of `stack_vector<value_type, ...>`
</blockquote></details>

What do you mean explicit instantiation?
___
*[`lib/utils/test/src/utils/stack_vector/stack_vector_of.cc` line 15 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbs1FeAQiwbWo53op_:-OGc443x9PR57tflTtoV:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/test/src/utils/stack_vector/stack_vector_of.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `.at` for bounds-checking
</blockquote></details>

Done.
___
*[`lib/utils/test/src/utils/stack_vector/stack_vector_of.cc` line 15 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbs9wT0O4ZL1r7qsSS:-OGc5XnL9ihUKiJ5IVvd:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/test/src/utils/stack_vector/stack_vector_of.cc#L15)):*
> ```cpp
>     CHECK(result[0] == 1);
>     CHECK(result[1] == 2);
>     CHECK(result[2] == 3);
> ```

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 860 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbswhBCQXdCU0Creyp:-OGc0ZAvCLA4cmfROV-e:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/pcg/src/pcg/computation_graph_builder.cc#L860)):*
> ```cpp
>   if (any_of(axes_stack, [&](ff_dim_t axis) {
>         return axis.value >= num_dims(input_shape);
>       })) {
> ```

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 860 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbtHvpCNeHjvpy7doQ:-OGc123rCo4yvS8rX75Z:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/pcg/src/pcg/computation_graph_builder.cc#L860)):*
> ```cpp
>   if (any_of(axes_stack, [&](ff_dim_t axis) {
>         return axis.value >= num_dims(input_shape);
>       })) {
> ```

Done.
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 867 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGChf7M3jRG12-TzuGQ:-OGJehVKAcbR0l84zD3Z:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4dcd72e1ddfbdd6637bebc49b99af6513debef04/lib/pcg/src/pcg/computation_graph_builder.cc#L867)):*
> ```cpp
>               return ff_dim_t_from_relative_ff_dim_t_ff_dim_t(
>                   relative_ff_dim_t{axis}, num_dims(input_shape));
>             });
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-15 05:33 UTC, lockshaw requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 5 unresolved discussions (waiting on @victorli2002)

___
*[`lib/op-attrs/src/op-attrs/dim_ordered/slice.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbqlNQ80tVpdJyJhhY:-OGcRU0YEQtgRwrVIIo1:bk71ezt) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/op-attrs/src/op-attrs/dim_ordered/slice.cc#L11)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/U90ppmrTisrQKBmObYVrPCIc/image.png)
Getting these errors
</blockquote></details>

I think the issue here is the `ifndef`s in this file--you should only have header guards in headers
___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGcRc7jEIvZcBZbJkBg:bhc2olm) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

What do you mean explicit instantiation?
</blockquote></details>

```
using T = value_type<0>;

template struct stack_vector<T, 5>;
```


<!-- Sent from Reviewable.io -->

2025-01-15 05:51 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 5 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/src/op-attrs/dim_ordered/slice.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbqlNQ80tVpdJyJhhY:-OGcSLJ33nIir5LVFzWH:biffdld) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/op-attrs/src/op-attrs/dim_ordered/slice.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think the issue here is the `ifndef`s in this file--you should only have header guards in headers
</blockquote></details>

oops lol
___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGcVhBd96EmZFkrfPHv:bwbbwhe) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

```
using T = value_type<0>;

template struct stack_vector<T, 5>;
```
</blockquote></details>

value_type looks like it's missing some operators that are used in stack_vector
![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/Gh5_qju3e0hcsPg7403lzZOA/image.png)


<!-- Sent from Reviewable.io -->

2025-01-15 05:56 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @victorli2002)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGcX7EtAy8_WVtd-era:b-cck4cq) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

value_type looks like it's missing some operators that are used in stack_vector
![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/Gh5_qju3e0hcsPg7403lzZOA/image.png)
</blockquote></details>

In that case try using `ordered_value_type` instead


<!-- Sent from Reviewable.io -->

2025-01-15 07:51 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGcwEPU8R7Ox9mfKDYg:bfkkvic) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case try using `ordered_value_type` instead
</blockquote></details>

I can't find that type. Is it in the main branch?


<!-- Sent from Reviewable.io -->

2025-01-15 21:06 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @victorli2002)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGfmMay7QdR_QU6xo-t:ba2mywt) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

I can't find that type. Is it in the main branch?
</blockquote></details>

Good point, go ahead and copy it into this branch: implementation [here](https://github.com/lockshaw/FlexFlow/blob/5e774c65501b97d376c5383e6098b9cd53bfccd2/lib/utils/include/utils/archetypes/ordered_value_type.h)


<!-- Sent from Reviewable.io -->

2025-01-15 22:37 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGg6JUY-C2N5criXUTO:bxwwj1y) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Good point, go ahead and copy it into this branch: implementation [here](https://github.com/lockshaw/FlexFlow/blob/5e774c65501b97d376c5383e6098b9cd53bfccd2/lib/utils/include/utils/archetypes/ordered_value_type.h)
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/-ZToLw4TYtHKbnRLCz1rqxK6/image.png)
Is there a way to give it support for std::optional?


<!-- Sent from Reviewable.io -->

2025-01-15 23:50 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @victorli2002)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGgMYm56tzgK_lDBjdw:b-mmolvn) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/32348970/-ZToLw4TYtHKbnRLCz1rqxK6/image.png)
Is there a way to give it support for std::optional?
</blockquote></details>

That's actually a correctly-detected error: `ordered_value_type` is not default-constructible, so `element_type` is `std::optional<ordered_value_type>`, but then the type of the `.data()` method is incorrect. For now just remove that method


<!-- Sent from Reviewable.io -->

2025-01-16 03:08 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/utils/stack_vector/stack_vector.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrp5KEtu1PBYldszF:-OGgs1f425GB44b3dGVV:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

That's actually a correctly-detected error: `ordered_value_type` is not default-constructible, so `element_type` is `std::optional<ordered_value_type>`, but then the type of the `.data()` method is incorrect. For now just remove that method
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/stack_vector/stack_vector_of.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGbrhBv8xf52WS9KDb7:-OGh4F9G9gqBONSX9ifo:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5e08c11fb59774af2359f1d24f176046f6816a15/lib/utils/src/utils/stack_vector/stack_vector_of.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add explicit instantiation of `stack_vector_of` for `stack_vector<value_type, ...>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-16 07:23 UTC, victorli2002 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: 99 of 106 files reviewed, 6 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/utils/include/utils/stack_vector/stack_vector.h` line 295 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGhwja6B9KOSJaSld8C:-OGhwja6B9KOSJaSld8D:b-yarmb7) ([raw file](https://github.com/flexflow/flexflow-train/blob/727fd85d6cc7fc26bf4c4ceb3cc95911d56953b4/lib/utils/include/utils/stack_vector/stack_vector.h#L295)):*
> ```objc
>   }
> 
>   std::array<element_type, MAXSIZE> stack_contents() const {
> ```

Changed this due to the type errors with `ordered_value_type`. `stack_string.h` still called the data function, so I created this to give it access to `contents`
___
*[`lib/utils/include/utils/stack_string.h` line 62 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1533#-OGhz7LU3rZBxJ6WR9Qo:-OGhz7LU3rZBxJ6WR9Qp:b-fuzl2d) ([raw file](https://github.com/flexflow/flexflow-train/blob/727fd85d6cc7fc26bf4c4ceb3cc95911d56953b4/lib/utils/include/utils/stack_string.h#L62)):*
> ```objc
>   friend fmt::basic_string_view<Char>
>       format_as(stack_basic_string<Char, MAXSIZE> const &s) {
>     return {s.contents.stack_contents().data(), s.length()};
> ```

changed to match `stack_vector` change


<!-- Sent from Reviewable.io -->

2025-01-16 23:30 UTC, lockshaw approved these changes
> Reviewed 5 of 7 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1533)* status: all files reviewed, 4 unresolved discussions (waiting on @Marsella8 and @victorli2002)



<!-- Sent from Reviewable.io -->

2025-01-17 00:00 UTC, merged