Add SimVP model computational graph
flexflow/flexflow-train pull request #1549
Opened 2024-12-05 01:50 UTC by easyeasydev

**Description of changes:**

This PR is to add the computational graph of the SimVP model.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-12-21 09:36 UTC, lockshaw requested changes
Have you double checked the model using the model viewer to make sure everything looks as expected?

Also, there need to be a lot more comments/links referencing the original code--the goal with these is to make it trivial for someone else a year or two in the future to look through the code without you and easily double check everything against the reference implementation without having to track a whole bunch of stuff down. Ideally also some assertions on tensor shapes.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-:-OEcZR1QA06pZkuLAcI0:bm3egis)* status: all files reviewed, 21 unresolved discussions (waiting on @easyeasydev and @reyna-abhyankar)

___
*[`lib/models/src/models/simvp/simvp.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXHjnC7hIuWl9UC3t:-OEcXHjnC7hIuWl9UC3u:b-co3jbi) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L24)):*
> ```cpp
> 
> std::vector<bool> create_simvp_samplings(size_t N_S, bool reverse) {
>   size_t N_S_even_floor = (N_S / 2) * 2;
> ```

Pull out a separate function named `round_down_to_nearest_even` to improve readbility



_Code quote:_
```cpp
 size_t N_S_even_floor = (N_S / 2) * 2;
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWr0zCYjopfeckmyd:-OEcWr0zCYjopfeckmye:b-8pi8lm) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L26)):*
> ```cpp
>   size_t N_S_even_floor = (N_S / 2) * 2;
> 
>   auto const change_to_true = [&](size_t idx) -> bool {
> ```

Is this actually the name used in the reference implementation? It seems rather weird.



_Code quote:_
```cpp
change_to_true
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWzylCtPAWIL3ab4E:-OEcWzylCtPAWIL3ab4F:b-5b584s) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L37)):*
> ```cpp
>   }
> 
>   return samplings;
> ```

In all of these PRs use functions from `utils/containers` more frequently to improve readbility.



_Suggestion:_
```cpp
  return transform(range(N_S_even_floor), change_to_true);
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWjBb6-VYX8gmJ1qt:-OEcWjBb6-VYX8gmJ1qu:b-abjouc) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L43)):*
> ```cpp
>                                   SimVPConfig const &config,
>                                   tensor_guid_t const &input,
>                                   size_t in_dim,
> ```

Prefer `int` over `size_t`
___
*[`lib/models/src/models/simvp/simvp.cc` line 68 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXTwH1WESGcxC5tCR:-OEcXTwH1WESGcxC5tCS:b-3l21tw) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L68)):*
> ```cpp
>                          SimVPConfig const &config,
>                          tensor_guid_t const &input) {
>   size_t C = config.in_shape.at(1); // Channel
> ```

It seems like `in_shape` has a fixed number of dimension, so it would probably be better to use four named fields (or even an additional struct) rather than a `vector`



_Code quote:_
```cpp
  size_t C = config.in_shape.at(1); // Channel
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 81 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWFr541B87iDeAH6k:-OEcWFr541B87iDeAH6l:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L81)):*
> ```cpp
>   tensor_guid_t latent = enc1;
> 
>   for (size_t i = 1; i < samplings.size(); i++) {
> ```





_Suggestion:_
```cpp
  for (int sampling : subvec(samplings, 1, std::nullopt)) {
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 88 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWDjZ99eaIk7dFBgI:-OEcWDjZ99eaIk7dFBgJ:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L88)):*
> ```cpp
>                                  config.hid_S,
>                                  config.spatio_kernel_enc,
>                                  samplings[i],
> ```





_Suggestion:_
```cpp
                                 samplings.at(i)
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcW8TECYLdiI0Daz5S:-OEcW8TECYLdiI0Daz5T:b-jhlp68) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L105)):*
> ```cpp
>                                         float drop_path,
>                                         float init_value) {
>   return input;
> ```

Seems to be missing an actual implementation?
___
*[`lib/models/src/models/simvp/simvp.cc` line 134 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUlTZ9-1MTDvLIbya:-OEcUlTZ9-1MTDvLIbyb:bmcudg3) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L134)):*
> ```cpp
>                                       float drop,
>                                       float drop_path) {
>   if (config.model_type != "gSTA") {
> ```

Prefer an dtgen enum instead of a string for the model type
___
*[`lib/models/src/models/simvp/simvp.cc` line 147 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcVmdyA1bbfVywX_Yh:-OEcVmdyA1bbfVywX_Yi:b-7m4nmi) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L147)):*
> ```cpp
>   // Downsample
>   z = create_simvp_gsta_meta_block(
>       cgb, config, z, channel_in, channel_hid, mlp_ratio, drop, drop_path);
> ```

Add argument name comments for all invocations of these many-argument functions for readability



_Suggestion:_
```cpp
  z = create_simvp_gsta_meta_block(
      /*cgb=*/cgb, 
      /*config=*/config, 
      /*input=*/z, 
      /*in_channels=*/channel_in, 
      /*out_channels=*/channel_hid, 
      /*mlp_ratio=*/mlp_ratio, 
      /*drop=*/drop, 
      /*drop_path=*/drop_path);
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 150 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXsJS2_DV18sDevwU:-OEcXsJS2_DV18sDevwV:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L150)):*
> ```cpp
> 
>   // Middle layers
>   for (size_t i = 1; i < config.N_T - 1; i++) {
> ```





_Suggestion:_
```cpp
  for (int i : range(1, config.N_T - 1)) {
```
___
*[`lib/models/src/models/simvp/simvp.cc` line 153 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcY8Gp-NVHaiUbveI3:-OEcY8Gp-NVHaiUbveI4:b-9mp0gs) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L153)):*
> ```cpp
>     z = create_simvp_gsta_meta_block(
>         cgb, config, z, channel_hid, channel_hid, mlp_ratio, drop, drop_path);
>   }
> ```

Considering that this `f(f(f(f(...f(x_0)...))))` pattern keeps showing up in model definitions, it might be nice to pull it out into a separate function in `utils/containers` named something like "primitive_recurse" or "recurse_n" or something. Thoughts? I'm sure @Marsella8 would be happy to add such a function



_Code qu [...]

2024-12-21 21:05 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1549)* status: all files reviewed, 21 unresolved discussions (waiting on @easyeasydev, @lockshaw, and @reyna-abhyankar)

___
*[`lib/models/src/models/simvp/simvp.cc` line 153 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcY8Gp-NVHaiUbveI3:-OEf0jUuDqxd1YtDs842:b-y05576) ([raw file](https://github.com/flexflow/flexflow-train/blob/017042a451f0cfc252fb2651b1b2851c8adccdd4/lib/models/src/models/simvp/simvp.cc#L153)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Considering that this `f(f(f(f(...f(x_0)...))))` pattern keeps showing up in model definitions, it might be nice to pull it out into a separate function in `utils/containers` named something like "primitive_recurse" or "recurse_n" or something. Thoughts? I'm sure @Marsella8 would be happy to add such a function
</blockquote></details>

See #1563     


<!-- Sent from Reviewable.io -->

2025-02-06 01:43 UTC, easyeasydev reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1549)* status: 2 of 6 files reviewed, 21 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/include/models/simvp/simvp.h` line 18 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcVLYAEFPMzz9F53aE:-OINgtTbDWzgnNgDahU4:b70eeqi) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/include/models/simvp/simvp.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would be nice to have links here in the docstrings to wherever the equivalent code in OpenSTL is for each of these functions
</blockquote></details>

Added the links to docstrings.
___
*[`lib/models/include/models/simvp/simvp_config.struct.toml` line 28 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUUl21Zq8B8rte7BH:-OINiiLsAXClYVsBqtzi:bb6un1j) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/include/models/simvp/simvp_config.struct.toml#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` over `size_t`
</blockquote></details>

Done
___
*[`lib/models/include/models/simvp/simvp_config.struct.toml` line 43 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUPMJ7aRslRzbc3xB:-OINiKDNEslpcX36ILmj:bgvi8q8) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/include/models/simvp/simvp_config.struct.toml#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Let's keep variable names lower-case
</blockquote></details>

This was actually to match with original implementation. Do we want to follow the OpenSTL convention or change here?
___
*[`lib/models/src/models/simvp/simvp.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXHjnC7hIuWl9UC3t:-OINjM5w5hyFRxcoH2Hg:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull out a separate function named `round_down_to_nearest_even` to improve readbility
</blockquote></details>

Done.
___
*[`lib/models/src/models/simvp/simvp.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWr0zCYjopfeckmyd:-OINjfVvCcPvzFudQLWv:bk03f8f) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this actually the name used in the reference implementation? It seems rather weird.
</blockquote></details>

Hmm, actually this is what I named it. This function was a bit nonintuitive in the original function.

I have changed this function name to `change_to_true_at_idx`
___
*[`lib/models/src/models/simvp/simvp.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWzylCtPAWIL3ab4E:-OINmO-Y75YrW9FrfDMH:b8cw6df) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In all of these PRs use functions from `utils/containers` more frequently to improve readbility.
</blockquote></details>

TBH, I doubt it will be a bit hard to understand by converting to this transform call in this function. But I have updated it, which is definitely more concise.
___
*[`lib/models/src/models/simvp/simvp.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcWjBb6-VYX8gmJ1qt:-OINmpWHCjJiSR8d6gHK:b7ejtph) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int` over `size_t`
</blockquote></details>

Could you remind me why we try to avoid `size_t` in flexflow? I remember that's some limitation in FF codebase right?
___
*[`lib/models/src/models/simvp/simvp.cc` line 68 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXTwH1WESGcxC5tCR:-OINn8PO5uv4FhgtkESi:b6h29sn) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L68)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It seems like `in_shape` has a fixed number of dimension, so it would probably be better to use four named fields (or even an additional struct) rather than a `vector`
</blockquote></details>

This was mainly to mimic the original implementation. I can change this if we really want. https://github.com/chengtan9907/OpenSTL/blob/b658dab3da427c8750c8595316e7ae9d70b818df/examples/tutorial.ipynb
___
*[`lib/models/src/models/simvp/simvp.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcW8TECYLdiI0Daz5S:-OINohHWCwiJX1TltufA:b-6unrlv) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L105)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Seems to be missing an actual implementation?
</blockquote></details>

Hmm, missed this somehow. Will add this.
___
*[`lib/models/src/models/simvp/simvp.cc` line 134 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUlTZ9-1MTDvLIbya:-OINpJCH0cDrSVwpIbgU:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L134)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer an dtgen enum instead of a string for the model type
</blockquote></details>

Done.
___
*[`lib/models/src/models/simvp/simvp.cc` line 147 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcVmdyA1bbfVywX_Yh:-OINryUMAISS7i2mUlPs:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L147)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add argument name comments for all invocations of these many-argument functions for readability
</blockquote></details>

Done.
___
*[`lib/models/src/models/simvp/simvp.cc` line 168 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcVY8o4c2TyjY2-WKt:-OINsNgh-iSH1_iU_Rim:beg9lp7) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L168)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove prints. 

Also, I assume if you were looking at the shapes then you know what they should be, so you should add in asserts on the tensor shapes where possible to improve readability and reduce the possibility of bugs
</blockquote></details>

This function looks like this because we may need a reshape op for this model. Without reshape op, I wasn't sure how to implement this the same as the reference implementation.
___
*[`lib/models/src/models/simvp/simvp.cc` line 207 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcVa_P0whE2xycgYzq:-OINswiFCxN_R2Xy4mU1:b9iazfr) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L207)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove prints
</blockquote></d [...]

2025-03-04 17:56 UTC, reyna-abhyankar requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1549)* status: all files reviewed, 26 unresolved discussions (waiting on @easyeasydev and @lockshaw)

___
*[`lib/models/include/models/simvp/simvp_config.struct.toml` line 28 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUUl21Zq8B8rte7BH:-OKXA-z9-MV3SBUxHakQ:bopuw7a) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/include/models/simvp/simvp_config.struct.toml#L28)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Done
</blockquote></details>

We now have a `nonnegative_int` type that should be used over int/size_t whenever applicable, so you can use that instead.
___
*[`lib/models/src/models/simvp/simvp.cc` line 68 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcXTwH1WESGcxC5tCR:-OKXCRN_58249K5tlA64:bsa1glh) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L68)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

This was mainly to mimic the original implementation. I can change this if we really want. https://github.com/chengtan9907/OpenSTL/blob/b658dab3da427c8750c8595316e7ae9d70b818df/examples/tutorial.ipynb
</blockquote></details>

How about using `TensorShape` (since that's actually what `in_shape` is)?
___
*[`lib/models/src/models/simvp/simvp.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcW8TECYLdiI0Daz5S:-OKXCxIF7M0AomEqieRA:bnozd9l) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L105)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Hmm, missed this somehow. Will add this.
</blockquote></details>

Still missing
___
*[`lib/models/src/models/simvp/simvp.cc` line 134 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OEcUlTZ9-1MTDvLIbya:-OKXDb8h9im18OHFbwz_:bkhgcnv) ([raw file](https://github.com/flexflow/flexflow-train/blob/7d39b8b7fbc1e5177098e2082957405d8ef6840d/lib/models/src/models/simvp/simvp.cc#L134)):*
<details><summary><i>Previously, easyeasydev wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXAcOJ2qsSRySR1KS2
___
*[`lib/models/src/models/simvp/simvp.cc` line 16 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXAcOJ2qsSRySR1KS2:-OKXAcOJ2qsSRySR1KS3:bd91zft) ([raw file](https://github.com/flexflow/flexflow-train/blob/f2471248d3bef1ed8e3b14ec2e4b260b07b7af2a/lib/models/src/models/simvp/simvp.cc#L16)):*
> ```cpp
>       /*N_S=*/4,
>       /*N_T=*/4,
>       /*model_type=*/FlexFlow::SimVPModelType::gSTA,
> ```

Don't think `FlexFlow::` is needed here
___
*[`lib/models/src/models/simvp/simvp.cc` line 23 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXAkyU3rBWjqZEsD5u:-OKXAkyU3rBWjqZEsD5v:baw9xlu) ([raw file](https://github.com/flexflow/flexflow-train/blob/f2471248d3bef1ed8e3b14ec2e4b260b07b7af2a/lib/models/src/models/simvp/simvp.cc#L23)):*
> ```cpp
>       /*spatio_kernel_dec=*/3,
>       /*in_shape=*/
>       {10, 3, 32, 32},
> ```

Where is this shape obtained from?
___
*[`lib/models/src/models/simvp/simvp.cc` line 151 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXHpiNAfcLdZjk3708:-OKXHpiNAfcLdZjk3709:bxzk1u3) ([raw file](https://github.com/flexflow/flexflow-train/blob/f2471248d3bef1ed8e3b14ec2e4b260b07b7af2a/lib/models/src/models/simvp/simvp.cc#L151)):*
> ```cpp
> 
>   tensor_guid_t z = embed;
> ```

Missing implementation for stochastic depth decay rule? https://github.com/chengtan9907/OpenSTL/blob/b658dab3da427c8750c8595316e7ae9d70b818df/openstl/models/simvp_model.py#L220
___
*[`lib/models/src/models/simvp/simvp.cc` line 206 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXHMBD-KFCHFhk5gTN:-OKXHMBD-KFCHFhk5gTO:byj3jdq) ([raw file](https://github.com/flexflow/flexflow-train/blob/f2471248d3bef1ed8e3b14ec2e4b260b07b7af2a/lib/models/src/models/simvp/simvp.cc#L206)):*
> ```cpp
>                                  config.hid_S,
>                                  config.spatio_kernel_dec,
>                                  false,
> ```

Add comment for what this boolean value is (same for next line)
___
*[`lib/models/include/models/simvp/simvp.h` line 63 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1549#-OKXGnERBZQfnHHQzBJf:-OKXGnERBZQfnHHQzBJg:b-nzqlmz) ([raw file](https://github.com/flexflow/flexflow-train/blob/f2471248d3bef1ed8e3b14ec2e4b260b07b7af2a/lib/models/include/models/simvp/simvp.h#L63)):*
> ```objc
> // Refer to
> // https://github.com/chengtan9907/OpenSTL/blob/b658dab3da427c8750c8595316e7ae9d70b818df/openstl/models/simvp_model.py#L100
> tensor_guid_t create_simvp_middle_net(ComputationGraphBuilder &cgb,
> ```

This definition doesn't match the link provided. Did you mean https://github.com/chengtan9907/OpenSTL/blob/b658dab3da427c8750c8595316e7ae9d70b818df/openstl/models/simvp_model.py#L211

Also there seem to be two "middle nets", one that's inception-based and one that isn't. Which one(s) are we trying to add in this PR?


<!-- Sent from Reviewable.io -->

2025-07-12 12:59 UTC, closed without merging