Update README & other docs post-repo-split
flexflow/flexflow-train pull request #1564
Opened 2024-12-27 05:18 UTC by lockshaw

**Description of changes:**

Update docs post-repo split, especially the developer/setup docs in CONTRIBUTING.md.

Also aggressively remove a whole bunch of outdated files. Remember that these are all available in the archived master and inference branches, as well as in the git history.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2025-01-17 22:43 UTC, victorli2002 reviewed
> Reviewed 47 of 453 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1564)* status: 47 of 453 files reviewed, 1 unresolved discussion (waiting on @eric-zheng, @lockshaw, and @Marsella8)

___
*[`CONTRIBUTING.md` line 15 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1564#-OGqPVX77drpD2amcSoD:-OGqPVX77drpD2amcSoE:bu25wqh) ([raw file](https://github.com/flexflow/flexflow-train/blob/8476c2627abba9c3edfa50a076f21c699c9b5006/CONTRIBUTING.md#L15)):*
> ```Markdown
> 
>    2. If you don't have root permissions: [DavHau/nix-portable](https://github.com/DavHau/nix-portable). 
>       Note that nix-portable does not work particularly well if the nix store is in NFS, so if you are running on an 
> ```

It might be helpful to say what NFS is (idk what it is).


<!-- Sent from Reviewable.io -->

2025-01-19 03:27 UTC, Marsella8 requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1564)* status: 47 of 453 files reviewed, 2 unresolved discussions (waiting on @eric-zheng and @lockshaw)

___
*[`CONTRIBUTING.md` line 59 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1564#-OGwZ3oH9PYzM07VSjvo:-OGwZ3oH9PYzM07VSjvp:b-jmsagx) ([raw file](https://github.com/flexflow/flexflow-train/blob/8476c2627abba9c3edfa50a076f21c699c9b5006/CONTRIBUTING.md#L59)):*
> ```Markdown
> (ff) $ proj cmake
> ...
> (ff) $ proj test
> ```

also add a comment related to running tests without running the GPU tests? I think you mentioned something like that in the last meeting


<!-- Sent from Reviewable.io -->

2025-01-20 02:37 UTC, lockshaw reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1564)* status: 46 of 453 files reviewed, 1 unresolved discussion (waiting on @eric-zheng, @Marsella8, and @victorli2002)

___
*[`CONTRIBUTING.md` line 15 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1564#-OGqPVX77drpD2amcSoD:-OH0Z_yw2R0jhOmrv7H4:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/b2c615f923f815fb9340ceffd6e2de4335df0bf9/CONTRIBUTING.md#L15)):*
<details><summary><i>Previously, victorli2002 (Victor Li) wrote…</i></summary><blockquote>

It might be helpful to say what NFS is (idk what it is).
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 59 at r2](https://reviewable.io/reviews/flexflow/flexflow-train/1564#-OGwZ3oH9PYzM07VSjvo:-OH0ZZpv9fT9k8meEEmc:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/b2c615f923f815fb9340ceffd6e2de4335df0bf9/CONTRIBUTING.md#L59)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

also add a comment related to running tests without running the GPU tests? I think you mentioned something like that in the last meeting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-20 06:45 UTC, Marsella8 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1564)* status: 46 of 453 files reviewed, all discussions resolved (waiting on @eric-zheng and @victorli2002)



<!-- Sent from Reviewable.io -->

2025-01-20 22:39 UTC, merged