Task Simulator
flexflow/flexflow-train pull request #1565
Opened 2024-12-27 22:37 UTC by Marsella8

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

2025-01-09 23:55 UTC, lockshaw requested changes
> Reviewed 10 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 10 of 28 files reviewed, 4 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/src/compiler/cost_estimator/cost_estimator.cc` line 1 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCTeCw-PE8lx1EGF_Y:-OGCTeCw-PE8lx1EGF_Z:b5d2y13) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/cost_estimator.cc#L1)):*
> ```cpp
> 
> ```

Why a newline?
___
*[`lib/compiler/test/src/compiler/cost_estimator_for_test.h` line 37 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCU1lM5OgxQKMUpC8m:-OGCU1lM5OgxQKMUpC8n:b-4shy9v) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator_for_test.h#L37)):*
> ```objc
> 
> CostEstimator make_fake_constant_cost_estimator(float const &op_cost,
>                                                 float const &comm_cost);
> ```

Generally pass primitives by value



_Suggestion:_
```objc
CostEstimator make_fake_constant_cost_estimator(float op_cost,
                                                float comm_cost);
```
___
*[`lib/compiler/include/compiler/cost_estimator/timed_dependency.struct.toml` line 1 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCTOeC3wvsfc2YJHJl:-OGCTOePEBbZJqqml52D:b-v1teqy) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/include/compiler/cost_estimator/timed_dependency.struct.toml#L1)):*
> ```TOML
> 
> ```

Why a leading newline in a bunch of these files?
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 27 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCTlUy6CHl2HMvpQ8X:-OGCTlUy6CHl2HMvpQ8Y:b-q1ey4n) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/allowed_machine_views.cc#L27)):*
> ```cpp
>                            OperatorTaskSpace const &task,
>                            MachineSpecification const &ms) {
>   if (num_dims(mv) != num_dims(task)) {
> ```

Is this true? I don't remember where projection is handled--is a (8,) machine view a valid view for a (2, 4) task? Just double-checking :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2025-01-10 00:44 UTC, lockshaw requested changes
> Reviewed 18 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 22 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/cost_estimator/task_simulator.h` line 10 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCUr-K6ELR1AkYzX-w:-OGCUr-L8vL6kgfyqycu:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/include/compiler/cost_estimator/task_simulator.h#L10)):*
> ```objc
> 
> namespace FlexFlow {
> float task_simulator_forward_pass(ParallelComputationGraph const &pcg,
> ```





_Suggestion:_
```objc
float task_simulator_estimate_forward_pass_time
```
___
*[`lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCabW9DqkYQRqUnqah:-OGCabW9DqkYQRqUnqai:brfd2bz) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc#L38)):*
> ```cpp
> TEST_SUITE(FF_TEST_SUITE) {
>   CostEstimator estimator =
>       make_fake_constant_cost_estimator(/*op_cost*/ 10.0f, /*comm_cost*/ 1.0f);
> ```

I'd recommend at least also doing some tests with a cost estimator that differentiates between different ops and comms to validate that the right ops and comms are getting passed in.



_Code quote:_
```cpp
     make_fake_constant_cost_estimator(/*op_cost*/ 10.0f, /*comm_cost*/ 1.0f);
```
___
*[`lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc` line 41 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCaJNC1EAYTUl-Xz3o:-OGCaJNC1EAYTUl-Xz3p:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc#L41)):*
> ```cpp
>   MachineSpecification machine_spec = MachineSpecification{3, 3, 3, 1, 1};
> 
>   TEST_CASE("task_simulator: linear graph") {
> ```





_Suggestion:_
```cpp
TEST_SUITE(FF_TEST_SUITE) {
  TEST_CASE("task_simulator_forward_pass") {
    CostEstimator estimator =
      make_fake_constant_cost_estimator(/*op_cost*/ 10.0f, /*comm_cost*/ 1.0f);
    MachineSpecification machine_spec = MachineSpecification{3, 3, 3, 1, 1};

    SUBCASE("linear graph") {
```
___
*[`lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc` line 166 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCazPz1flXeCgxHi9_:-OGCazPz1flXeCgxHi9a:bs4sc9e) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc#L166)):*
> ```cpp
>             MachineViewDimension{stride_t{1},
>                                  MachineSpecificationDimension::INTER_NODE},
>         }};
> ```

Might make things a bit more readable



_Suggestion:_
```cpp
    std::vector<MachineViewDimension> dims = 
      {
            MachineViewDimension{stride_t{1},
                                 MachineSpecificationDimension::INTER_NODE},
            MachineViewDimension{stride_t{1},
                                 MachineSpecificationDimension::INTER_NODE},
            MachineViewDimension{stride_t{1},
                                 MachineSpecificationDimension::INTER_NODE},
        };
    MachineView mv0 = MachineView{
        MachineSpaceCoordinate{0, 0, DeviceType::GPU},
        dims,
        };
    MachineView mv1 = MachineView{
        MachineSpaceCoordinate{0, 1, DeviceType::GPU},
        dims};
    MachineView mv2 = MachineView{
        MachineSpaceCoordinate{1, 0, DeviceType::GPU},
        dims};
    MachineView mv3 = MachineView{
        MachineSpaceCoordinate{1, 1, DeviceType::GPU},
        dims};
```
___
*[`lib/utils/src/utils/graph/dataflow_graph/algorithms/get_outgoing_edges.cc` line 6 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCUdkW0psLWhdB0XZJ:-OGCUdkW0psLWhdB0XZK:b2bysb9) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/utils/src/utils/graph/dataflow_graph/algorithms/get_outgoing_edges.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> 
> std::unordered_set<DataflowEdge> get_outgoing_edges(DataflowGraphView const &g,
> ```

Add unit tests for these
___
*[`lib/compiler/src/compiler/machine_mapping/machine_mapping_problem_tree/unmapped_op_cost_estimate_key.cc` line 36 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCVYrZ0QqYYHh42qvR:-OGCVYrZ0QqYYHh42qvS:b-aufzr0) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/machine_mapping/machine_mapping_problem_tree/unmapped_op_cost_estimate_key.cc#L36)):*
> ```cpp
> }
> 
> OpCostEstimateKey get_mapped_op_cost_estimate_key_for_layer(
> ```

Should probably be moved to the file for `OpCostEstimateKey` instead of here, as the signature doesn't really involve `UnmappedOpCostEstimateKey`
___
*[`lib/pcg/src/pcg/machine_specification.cc` line 55 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCX9ip8WLKbVNnPWiQ:-OGCX9ip8WLKbVNnPWiR:b-g6clnz) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/src/pcg/machine_specification.cc#L55)):*
> ```cpp
> 
> std::unordered_set<device_id_t>
>     get_device_ids(MachineSpecification const &ms,
> ```

Normally we don't have dedicated overloads for a function `f` that are just (`transform f`)--is there a compelling argument why this is needed here? The problem is adding them in explodes the number of functions you have to write, and they don't contribute a lot as you already have `transform` 
___
*[`lib/pcg/src/pcg/machine_view.cc` line 46 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCXXF88snacgJGjqnx:-OGCXXF88snacgJGjqny:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/src/pcg/machine_view.cc#L46)):*
> ```cpp
>   if (strides.size() != dims.size()) {
>     throw mk_runtime_error(
>         fmt::format("Dimensions of {} and {} must match when calling "
> ```





_Suggestion:_
```cpp
        fmt::format("Length of strides ({}) and dims ({}) must match when calling "
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 64 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCXcI67tHZ78jR0Psj:-OGCXcI67tHZ78jR0Psk:baxqf7e) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/src/pcg/machine_view.cc#L64)):*
> ```cpp
>     MachineSpecification const &machine_specification) {
> 
>   assert(num_dims(machine_view) == task.degrees.size());
> ```

Prefer a throw with an actual error message
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 0 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCefoU0xkuZ4bS8t8K:-OGCefoU0xkuZ4bS8t8L:b-8z6zuu) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L0)):*
Overall this implementation is pretty solid, and the lambdas do a lot to improve readability. If it's possible to pull out some composite data structures so that not all of the raw data structure manipulation has to be done directly, that might be nice--don't know if it's possible, but would be worth considering
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 68 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCdOM03-uueVHoju72:-OGCdOM03-uueVHoju73:b-s4rw36) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L68)):*
> ```cpp
> }
> 
> float task_simulator_forward_pass(ParallelComputationGraph const &pcg [...]

2025-01-10 23:09 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 8 of 36 files reviewed, 22 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator/timed_dependency.struct.toml` line 1 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCTOeC3wvsfc2YJHJl:-OGFzNU4Dcgfx-OWnVF8:b-7ql1td) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/include/compiler/cost_estimator/timed_dependency.struct.toml#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why a leading newline in a bunch of these files?
</blockquote></details>

fixed
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 27 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCTlUy6CHl2HMvpQ8X:-OGFzalHDKMmazuhMbOX:b-l666sc) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/allowed_machine_views.cc#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this true? I don't remember where projection is handled--is a (8,) machine view a valid view for a (2, 4) task? Just double-checking :slightly_smiling_face:
</blockquote></details>

Yes, `MachineView` stores the starting point (in the machine space, the 2D one) and an N dimensional vector (which "lives" in the task space) which says for each degree of the OperatorTaskSpace what is the stride and projection. So for a (2,4) task that we want to project across the INTER_NODE dimension in the machine space we would have MachineView((a, INTER_NODE), (b, INTER_NODE)) where a,b are some strides.
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 82 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCbfyY5u1RDgeJ_iAc:-OGGgZiz6g1gm2Ze3XuA:bs1tt5f) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L82)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this a cohesive data structure that could be factored out? Seems like you're using it for both `TimedLayer` and `TimedDependency`? Not a huge deal, just might simplify a bit of the code
</blockquote></details>

yeah you are right, I've stepped back a bit and the behaviour for how the dependencies and layers are processed is pretty much the same, only difference is how you finish processing them. I have refactored the code accordingly, we now have a `TimedComponent` (variant of the other 2) and a single queue that stores both.


(Way cleaner, thanks a lot for pointing it out)
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 82 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCcpFv-Cc9JW2V2eiV:-OGGBdDb1sIRroa-q43Z:bh0gjnd) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L82)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any reason for using separate priority queues instead of having a single priority queue that holds something like `type Task = (float, variant<Layer, Edge>)`?
</blockquote></details>

Yeah you are absolutely right, have changed it accordingly.
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 98 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCc6hH2J-uZozl4K4u:-OGGhUPsCkaFmFI64Gx_:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L98)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe something like "ready_layers" might make it a bit clearer what these are? At least to me "frontier" could indicate the latest executed layers or the next to execute layers or the frontier of layers that aren't ready yet, so this name alone is a bit ambiguous
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 107 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCcZHw6W681v3VjATT:-OGGhYz23Bj_pWQTjklN:bttgpkc) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L107)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

So in this current version there's no modelling of congestion or tensor reuse at all, correct?
</blockquote></details>

correct, how should I go about modelling it (Something along the lines of, for a given instant of time t, a given device can at most transfer x tensors to any other device?).

Isn't it generally better for the task simulator to supply the tensors to the cost_estimator intelligently, and then let it figure out the costs, rather than trying to simulate those things directly with the task simulator (genuine question, I'm not sure how accurately the cost estimator models things).
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line  at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCefoU0xkuZ4bS8t8K:-OGGA4Uy0YABUmcDrych:b-j2pdd7) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Overall this implementation is pretty solid, and the lambdas do a lot to improve readability. If it's possible to pull out some composite data structures so that not all of the raw data structure manipulation has to be done directly, that might be nice--don't know if it's possible, but would be worth considering
</blockquote></details>

I have changed the device map `std::unordered_map<parallel_layer_guid_t, std::unordered_set<device_id_t>>` to be `DeviceMapping`, but I'm not sure which other ones would be worth pulling out.
___
*[`lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc` line 166 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCazPz1flXeCgxHi9_:-OGGn2iY6HmEMygwL53c:bqet56p) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might make things a bit more readable
</blockquote></details>

refactored the test cases, should be a lot more readable now
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h` line 44 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCWYwtE_rcz9e1WizH:-OGHCJf_-D3_BQt5K7A2:bsd38is) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

To avoid overloading the term "source" (since we also have `get_source_layer` for edges), maybe could use a different name like "get_initial_layers" (so you'd have source/(sink/destination) edges, and initial/terminal for the overall graph)? Not super important, just a thought
</blockquote></details>

you're right, changed
___
*[`lib/pcg/src/pcg/machine_specification.cc` line 55 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCX9ip8WLKbVNnPWiQ:-OGHD3Uh0gmBLE6CGsF3:brpmqc3) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/src/pcg/machine_specification.cc#L55)):*
<details><summary><i>P [...]

2025-01-12 00:31 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 8 of 36 files reviewed, 22 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCabW9DqkYQRqUnqah:-OGMuyhdBpjcfqXjAkqe:b-7tfmjp) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/compiler/test/src/compiler/cost_estimator/task_simulator.cc#L38)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'd recommend at least also doing some tests with a cost estimator that differentiates between different ops and comms to validate that the right ops and comms are getting passed in.
</blockquote></details>

added


<!-- Sent from Reviewable.io -->

2025-01-16 00:49 UTC, lockshaw requested changes
> Reviewed 17 of 28 files at r2, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 26 of 39 files reviewed, 8 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/cost_estimator/timed_component.variant.toml` line 0 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGbzcMX8zXaGqI8a6om:-OGbzcMX8zXaGqI8a6on:b-f9172k) ([raw file](https://github.com/flexflow/flexflow-train/blob/694e4b9aec736af05f3334826aef2b274898a90a/lib/compiler/include/compiler/cost_estimator/timed_component.variant.toml#L0)):*
Why not `(time, variant<layer, edge>)` instead of `variant<(time, layer), (time, edge)>`?


<!-- Sent from Reviewable.io -->

2025-01-17 21:03 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 26 of 41 files reviewed, 8 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator/timed_component.variant.toml` line  at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGbzcMX8zXaGqI8a6om:-OGq3R9j6Tiawf2qTGRc:b-g9j4sx) ([raw file](https://github.com/flexflow/flexflow-train/blob/694e4b9aec736af05f3334826aef2b274898a90a/lib/compiler/include/compiler/cost_estimator/timed_component.variant.toml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not `(time, variant<layer, edge>)` instead of `variant<(time, layer), (time, edge)>`?
</blockquote></details>

for some functions you only want to take in either a `TimedLayer` or a `TimedComponent`, find it more convenient to do the variant this way since otherwise I would have to either pass the variant and manually assert that it has the right type of unpacking and then passing time and layer/edge separately, which wasn't super elegant. tried both and the current one seemed to fit a bit better, not too much of a difference either way. 


<!-- Sent from Reviewable.io -->

2025-01-18 22:04 UTC, lockshaw requested changes
> Reviewed 2 of 16 files at r6, 1 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 23 of 47 files reviewed, 21 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 2 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvQj8VDGo0hUl4yx5H:-OGvQj8VDGo0hUl4yx5I:b-tlu3yi) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TaskGraph"
> ```

It would be nice if `TaskGraph` was a bit more semantically-rich, i.e., has node labels of type `Task`, where `Task` is a `variant.toml` of `parallel_layer_guid_t` and whatever your communication representation is. Then, your actual simulator code would take in a `DiGraphView` and a couple `std::function`s, which would be based on the `TaskGraph`. Right now it kinda feels like you have two levels of structures, (1) the full PCG, and (2) a fully anonymized DiGraphView, which makes the conversion/lowering code rather complex. It would be nice to have an intermediate structure to simplify things a bit. 
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 27 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvNJFdDe9YKboDE68_:-OGvNJFdDe9YKboDE68a:b-ykes1c) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L27)):*
> ```TOML
> 
> [[fields]]
> name = "is_allowed_to_run"
> ```

Conceptually shouldn't be part of the `TaskGraph`--should be passed as a separate parameter probably, or `TaskGraph` should be renamed/re-structured. `TaskGraph` to me conveys the set of tasks and the data dependencies between them, which `is_allowed_to_run` isn't part of
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 28 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvMhfz2eAbnSkf1rzD:-OGvMhfz2eAbnSkf1rzE:bulrlmu) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L28)):*
> ```TOML
> [[fields]]
> name = "is_allowed_to_run"
> type = "std::function<bool(::FlexFlow::Node, ::FlexFlow::TasksStateTracker)>"
> ```

Probably shouldn't take in the whole `TasksStateTracker`, as it shouldn't need to access the set of ready tasks or the current time. In fact, they don't even need the `TimedTask`s in the other two fields of the tracker, just two sets of `Node`: finished and in-progress 
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 28 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvMq6k06xGo-EMVXY6:-OGvMq6k06xGo-EMVXY7:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L28)):*
> ```TOML
> [[fields]]
> name = "is_allowed_to_run"
> type = "std::function<bool(::FlexFlow::Node, ::FlexFlow::TasksStateTracker)>"
> ```





_Suggestion:_
```TOML
type = "std::function<bool(::FlexFlow::Node, ::FlexFlow::TasksStateTracker const &)>"
```
___
*[`lib/compiler/include/compiler/cost_estimator/tasks_state_tracker.struct.toml` line 2 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOVfQ6KxOlKCUg6tZ:-OGvOVfQ6KxOlKCUg6t_:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/tasks_state_tracker.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TasksStateTracker"
> ```





_Suggestion:_
```TOML
name = "TaskGraphExecutionState"
```
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 0 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvPE6f2wm17lL2Go9T:-OGvPE6f2wm17lL2Go9U:b-giaqap) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L0)):*
`simulate_task_graph_execution.cc`
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvP2fw6ao81eOmQrcM:-OGvP2fw6ao81eOmQrcN:b23zrgi) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L47)):*
> ```cpp
>   return state_tracker.ready_tasks.empty() &&
>          state_tracker.tasks_processing.empty();
> }
> ```

Now that the domain-specific logic is factored out, feel free to make these lambdas again



_Code quote:_
```cpp
static void start_task_processing(TasksStateTracker &state_tracker,
                                  TaskGraph const &task_graph,
                                  Node const &task) {
  float cost = task_graph.cost_map.at(task);
  state_tracker.tasks_processing.push(
      TimedTask{state_tracker.current_time + cost, task});
  state_tracker.ready_tasks.erase(task);
}

static bool dependencies_are_satisfied(TasksStateTracker const &state_tracker,
                                       TaskGraph const &task_graph,
                                       Node const &task) {
  std::unordered_set<Node> incoming_dependencies =
      get_predecessors(task_graph.graph, task);
  return is_subseteq_of(incoming_dependencies, state_tracker.processed_tasks);
}

static void finish_task_processing(TasksStateTracker &state_tracker,
                                   TaskGraph const &task_graph,
                                   TimedTask const &timed_task) {
  state_tracker.processed_tasks.insert(timed_task.node);
  for (Node const &task : get_successors(task_graph.graph, timed_task.node)) {
    if (dependencies_are_satisfied(state_tracker, task_graph, task)) {
      state_tracker.ready_tasks.insert(task);
    }
  }
  state_tracker.current_time = timed_task.endtime;
}

static bool is_processing_done(TasksStateTracker const &state_tracker) {
  return state_tracker.ready_tasks.empty() &&
         state_tracker.tasks_processing.empty();
}
```
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOZXy1S3eDB3ZzjHs:-OGvOZXy1S3eDB3ZzjHt:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L55)):*
> ```cpp
> }
> 
> float simulate_forward_pass(TaskGraph const &task_graph) {
> ```





_Suggestion:_
```cpp
 simulate_task_graph_execution
```
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOdwn91AbvvGwANGE:-OGvOdwn91AbvvGwANGF:b7s9qdh) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L55)):*
> ```cpp
> }
> 
> float simulate_forward_pass(TaskGraph const &task_graph) {
> ```

TaskGraphProfile



_Code quote:_
```cpp
float
```
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 70 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvQQW_2Okoj0Z9zwgf:-OGvQQW_2Okoj0Z9zwgg:bp657g8) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L70)):*
> ```cpp
>   DiGraph digraph = DiGraph::create<AdjacencyDiGraph>();
>   bidict<Node,
>          std::variant<parallel_layer_guid_t, ParallelComputationGraphEdge>>
> ```

Avoid raw variants, introduce a `Task` type using `dtgen` [...]

2025-01-19 21:12 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 23 of 47 files reviewed, 21 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 27 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvNJFdDe9YKboDE68_:-OGxYZiT7bw2_1o5jQzb:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Conceptually shouldn't be part of the `TaskGraph`--should be passed as a separate parameter probably, or `TaskGraph` should be renamed/re-structured. `TaskGraph` to me conveys the set of tasks and the data dependencies between them, which `is_allowed_to_run` isn't part of
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 28 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvMhfz2eAbnSkf1rzD:-OGxY_5q9De0tBBQCuY0:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably shouldn't take in the whole `TasksStateTracker`, as it shouldn't need to access the set of ready tasks or the current time. In fact, they don't even need the `TimedTask`s in the other two fields of the tracker, just two sets of `Node`: finished and in-progress
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvP2fw6ao81eOmQrcM:-OH-KW8U-3P7H1qXuGdu:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Now that the domain-specific logic is factored out, feel free to make these lambdas again
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOdwn91AbvvGwANGE:-OH-NeJS0NOXmrwOojzJ:b-sierj6) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L55)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

TaskGraphProfile
</blockquote></details>

wouldn't it be better to return the entire profile rather than only the endtime? (since this way in testing I can check against the entire trace, and given the profile you can choose to discard everything but the endtime). 
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line  at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvPE6f2wm17lL2Go9T:-OGzsry33AQYyzRF6BwR:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`simulate_task_graph_execution.cc`
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 70 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvQQW_2Okoj0Z9zwgf:-OH-M12g3TAxGDwN-0Xg:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_simulator.cc#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Avoid raw variants, introduce a `Task` type using `dtgen`'s `variant.toml`
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/timed_component_comparator.h` line 10 at r4](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvPNmm1wQSgNqNFqbq:-OGzsUtv8m4-XXfNAa30:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/694e4b9aec736af05f3334826aef2b274898a90a/lib/compiler/include/compiler/cost_estimator/timed_component_comparator.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I actually like having the explicit comparator, can you bring this back? It removes the need to understand what code the `ord` feature in `dtgen` generates, which is nice as it avoids ambiguity
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/timed_task.struct.toml` line 2 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvNmRj0ZdzBzInoita:-OGx_wau1wEqc3FV_CT9:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/13a9b7554a9e00eb317829c72643a8638de4d7ec/lib/compiler/include/compiler/cost_estimator/timed_task.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TimedTask"
> ```

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/tasks_state_tracker.struct.toml` line 2 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOVfQ6KxOlKCUg6tZ:-OGxZHRVDyz8X3c1MxJn:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/tasks_state_tracker.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TasksStateTracker"
> ```

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 28 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvMq6k06xGo-EMVXY6:-OGxY_y43u4crNhxT1li:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L28)):*
> ```TOML
> [[fields]]
> name = "is_allowed_to_run"
> type = "std::function<bool(::FlexFlow::Node, ::FlexFlow::TasksStateTracker)>"
> ```

Done.
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph_profile.struct.toml` line 2 at r7](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOsVPA3bkzturkUS2:-OGxZ6B7CZ4zTfFAYXnY:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/13a9b7554a9e00eb317829c72643a8638de4d7ec/lib/compiler/include/compiler/cost_estimator/task_graph_profile.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TaskGraphProfile"
> ```

Done.
___
*[`lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGvOZXy1S3eDB3ZzjHs:-OGztwONDPUt0RkL6d8p:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a18e23d77e1408828bfe9893ecc980cb9362cebc/lib/compiler/src/compiler/cost_estimator/task_graph_traversal.cc#L55)):*
> ```cpp
> }
> 
> float simulate_forward_pass(TaskGraph const &task_graph) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-19 22:45 UTC, lockshaw requested changes
> Reviewed 8 of 29 files at r2, 3 of 18 files at r6, 23 of 24 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 52 of 55 files reviewed, 23 unresolved discussions (waiting on @Marsella8)

___
*[`lib/pcg/src/pcg/operator_task_space.cc` line 41 at r1](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OGCY4m_-i1kDBn6sJQT:-OH-iinF-0R73K6crwR3:bb5mem0) ([raw file](https://github.com/flexflow/flexflow-train/blob/7b04ccbbc47a18b838fa04ba0cb5edb22c5d1acb/lib/pcg/src/pcg/operator_task_space.cc#L41)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I have changed it accordingly, but yeah the operator task space still does not make too much sense. I'm generally a bit confused about how the `MachineView` mapping to Operator should work. MachineView describes a N-dimensional strided orthotope (which then gets mapped to the MachineSpace etc...), but how does this match with an operator, which is instead a function that returns a tuple of vectors, each with it's own dimension. Right now `OperatorTaskSpace` is essentially copying the parallel degrees of the *first* output tensor, but are these the same across all output tensors (or am I just making the arbitrary decision of fetching the first output tensor shape, rather than any other one)?
</blockquote></details>

The latter--it's an arbitrary choice. Eventually the dependencies will be moved into the PCG/inferrable from the PCG itself as part of #1569 
___
*[`lib/compiler/include/compiler/cost_estimator/task_constraint.struct.toml` line 2 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-fUa03wg6UASKj7uT:-OH-fUa03wg6UASKj7uU:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/cost_estimator/task_constraint.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TaskConstraint"
> ```





_Suggestion:_
```TOML
name = "TaskExecutionConstraint"
```
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 19 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-gMFnAs2SkRXmOvYd:-OH-gGbO1x09BMO3Kr68:b-oudbh) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L19)):*
> ```cpp
> 
> TaskGraphExecutionTrace
>     simulate_task_graph_execution(TaskGraph const &task_graph,
> ```

Might want to assert that the task graph is acylic? Just to improve debuggability
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 23 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-bRUHC5_4b7Y54wg7:-OH-bRUHC5_4b7Y54wg8:bn2jcay) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L23)):*
> ```cpp
> 
>   TaskGraphExecutionState execution_state =
>       TaskGraphExecutionState{get_sources(task_graph.graph), {}, {}, 0.0};
> ```

Add argument name comments



_Code quote:_
```cpp
      TaskGraphExecutionState{get_sources(task_graph.graph), {}, {}, 0.0};
```
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 52 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-bijgD5_2kwUUF26X:-OH-bijgD5_2kwUUF26Y:b-3onzfh) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L52)):*
> ```cpp
>         TaskProfile{in_progress_task.node,
>                     in_progress_task.endtime -
>                         task_graph.cost_map.at(in_progress_task.node),
> ```

Why not just have `InProgressTask` have a `start_time`? This seems easier/more-intuitive than having to infer if after it's already been executed
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 68 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-c1kj-2H01kDCFd5Y:-OH-c1kj-2H01kDCFd5Z:bl3bwer) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L68)):*
> ```cpp
>   };
>   while (!is_processing_done()) {
>     for (Node const &task : sorted(execution_state.ready_tasks)) {
> ```

Might be better to just have `ready_tasks` be a `std::set` so you have a non-insertion-order-based-order and don't have to keep sorting as iteration in a `std::set` is already ordered?



_Code quote:_
```cpp
sorted(execution_state.ready_tasks)
```
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 80 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-g4JmAVMC9y2qRbUB:-OH-g4JmAVMC9y2qRbUC:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L80)):*
> ```cpp
> 
>     if (!execution_state.tasks_processing.empty()) {
>       InProgressTask next_task = get_next_task();
> ```





_Suggestion:_
```cpp
get_next_task_to_finish
```
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 87 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-gB4qEhdIUjGc9IHE:-OH-gB4qEhdIUjGc9IHF:be6p6q) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L87)):*
> ```cpp
>   }
> 
>   return TaskGraphExecutionTrace{task_profiles, execution_state.current_time};
> ```

Would be good to include a check that all tasks were executed
___
*[`lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml` line 2 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-i24v6wPFTae5GjxD:-OH-i24w25KFNaZ1OEpB:bvmaomo) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/cost_estimator/task_graph.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TaskGraph"
> ```

I would get rid of `TaskGraph`, and just have the simulate function take in a DiGraphView, a cost function (as a std::function or a wrapped std::function, depending on your preference), and a constraint function
___
*[`lib/compiler/include/compiler/machine_mapping/device_mapping.cc` line 1 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-eGWf0HxbsCaW2Hav:-OH-eGWf0HxbsCaW2Haw:b-35fljq) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/machine_mapping/device_mapping.cc#L1)):*
> ```cpp
> 
> ```

Leading newline?
___
*[`lib/compiler/include/compiler/machine_mapping/device_mapping.cc` line 24 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-exwE1wlaXZNSlt28:-OH-exwE1wlaXZNSlt29:b-666z12) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/machine_mapping/device_mapping.cc#L24)):*
> ```cpp
>     device_mapping.insert(
>         {layer, get_device_ids(op, machine_view, machine_spec)});
>   }
> ```

Change to `map_values`?



_Code quote:_
```cpp
  std::unordered_map<parallel_layer_guid_t, std::unordered_set<device_id_t>>
      device_mapping;
  for (auto const &[layer, machine_view] : machine_mapping.machine_views) {
    OperatorTaskSpace op =
        get_operator_task_space(pcg, layer));
    device_mapping.insert(
        {layer, get_device_ids(op, machine_view, machine_spec)});
  }
```
___
*[`lib/compiler/src/compiler/cost_estimator/task_simulator.cc` line 64 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-hLpX2QamEQD8o [...]

2025-01-20 01:42 UTC, lockshaw requested changes
> Reviewed 1 of 29 files at r2, 18 of 19 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 54 of 55 files reviewed, 15 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/machine_mapping/unstructured_device_mapping.h` line 12 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0MNT5812k7MMmG-6f:-OH0MNT5812k7MMmG-6g:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/include/compiler/machine_mapping/unstructured_device_mapping.h#L12)):*
> ```objc
> 
> UnstructuredDeviceMapping
>     get_device_mapping(MachineMapping const &machine_mapping,
> ```





_Suggestion:_
```objc
get_unstructured_device_mapping
```
___
*[`lib/compiler/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc` line 97 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0LXUO91GrUSO4y6ka:-OH0LXUP062yYql6DoPz:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc#L97)):*
> ```cpp
>   }
>   if (execution_state.finished_tasks.size() != num_nodes(task_graph.graph)) {
>     throw mk_runtime_error("Some tasks within the TaskGraph are unreachable");
> ```





_Suggestion:_
```cpp
("Failed to execute all tasks in TaskGraph");
```
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 37 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0M9p5B8MceCz-q86m:-OH0M9p5B8MceCz-q86n:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L37)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("task_simulator") {
> ```





_Suggestion:_
```cpp
 TEST_CASE("task_simulator_estimate_forward_pass_time") {
```
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc` line 17 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0Mgm-DTcXo_K5n2NI:-OH0Mgm-DTcXo_K5n2NJ:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/test/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc#L17)):*
> ```cpp
> 
>     SUBCASE("linear graph") {
>       DiGraph g = DiGraph::create<AdjacencyDiGraph>();
> ```





_Suggestion:_
```cpp
    DiGraph g = DiGraph::create<AdjacencyDiGraph>();
    SUBCASE("linear graph") {
```
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc` line 87 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0MxOVD2hgHcXNulW7:-OH0MxOW5BepTNii-nVp:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/test/src/compiler/task_graph_simulator/simulate_task_graph_execution.cc#L87)):*
> ```cpp
>       }
> 
>       SUBCASE("processing constraint") {
> ```





_Suggestion:_
```cpp
      SUBCASE("constrained to one node at a time")
```
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 131 at r9](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH0Li17DMmu8AMo2mSY:-OH0Li17DMmu8AMo2mSZ:bydb6xd) ([raw file](https://github.com/flexflow/flexflow-train/blob/81bfbc5ac8e354d5084d26d299cfa7489e7fe663/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L131)):*
> ```cpp
>       transform(layer_nodes, [&](Node const &n) {
>         return node_map.at_l(n).require_layer();
>       });
> ```

`filtrans` would probably be cleaner



_Code quote:_
```cpp
  std::unordered_set<Node> layer_nodes =
      filter(in_progress_tasks,
             [&](Node const &n) { return node_map.at_l(n).is_layer(); });
  std::unordered_set<parallel_layer_guid_t> layers =
      transform(layer_nodes, [&](Node const &n) {
        return node_map.at_l(n).require_layer();
      });
```


<!-- Sent from Reviewable.io -->

2025-01-20 20:56 UTC, lockshaw requested changes
> Reviewed 37 of 37 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 19 unresolved discussions (waiting on @Marsella8)

___
*[`lib/utils/include/utils/deduplicated_priority_queue.h` line 41 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-j68SEhwb9Q8UgscF:-OH4Q9vZ-p697mzCZdWe:bdfsdu9) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/utils/include/utils/deduplicated_priority_queue.h#L41)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

pulls out all the contents of the deduplicated priority queue. Needed since i have to pass it to the constraint function.
</blockquote></details>

It's a sorted container of things without duplicates, so probably makes more sense to return a `std::set` using `Compare`?
___
*[`lib/compiler/include/compiler/machine_mapping/device_mapping.cc` line 24 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-exwE1wlaXZNSlt28:-OH4SNjr80RaNsNbBKYy:b-3nzjj4) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/machine_mapping/device_mapping.cc#L24)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

don't think it's doable elegantly, given that the new value is a function of both the key (layer) and the original value.
</blockquote></details>

Fair enough. Might be good to add a containers function to handle that at some point (e.g., `map_values_with_key` or something), but this is fine for now
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 68 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-c1kj-2H01kDCFd5Y:-OH4OuS-4bum-ZlaBaw5:b-aowahn) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L68)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

the `sorted` is more so for consistency during testing (if there are multiple available tasks, process the one with the associated smallest node). It's more to have a fixed, arbitrary order than anything else, so probably better to not have this property embedded into the execution_tracker itself?
</blockquote></details>

I think having a fixed/predictable order is actually a desirable property, so I don't really have any issue embedding it in execution_tracker
___
*[`lib/compiler/include/compiler/task_graph_simulator/task_graph_execution_trace.h` line 8 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4R5PW5CWwjYeIsVUO:-OH4R5PW5CWwjYeIsVUP:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/include/compiler/task_graph_simulator/task_graph_execution_trace.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> float get_endtime(TaskGraphExecutionTrace const &trace);
> ```





_Suggestion:_
```objc
get_total_execution_time
```
___
*[`lib/utils/test/src/utils/containers/func_from_map.cc` line 14 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4QhcgEUcTShHxG4NK:-OH4QhcgEUcTShHxG4NL:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/utils/test/src/utils/containers/func_from_map.cc#L14)):*
> ```cpp
> 
>     SUBCASE("existing keys") {
>       auto func = func_from_map(map);
> ```





_Suggestion:_
```cpp
std::function<int(std::string)> func = func_from_map(map);
```
___
*[`lib/utils/test/src/utils/containers/func_from_map.cc` line 20 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4QlzuBZl01pwGsJ-T:-OH4QlzuBZl01pwGsJ-U:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/utils/test/src/utils/containers/func_from_map.cc#L20)):*
> ```cpp
> 
>     SUBCASE("missing key") {
>       auto func = func_from_map(map);
> ```





_Suggestion:_
```cpp
      std::function<int(std::string)> func = func_from_map(map);
```
___
*[`lib/utils/test/src/utils/containers/func_from_map.cc` line 26 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Qpga47pFrE447zIH:-OH4Qpga47pFrE447zII:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/utils/test/src/utils/containers/func_from_map.cc#L26)):*
> ```cpp
>     SUBCASE("empty map") {
>       std::unordered_map<std::string, int> map = {};
>       auto func = func_from_map(map);
> ```





_Suggestion:_
```cpp
        std::function<int(std::string)> func = func_from_map(map);
```
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 67 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4TWQG1DZI8RlmfIkD:-OH4TWQH6v-68SX-7O3M:b-e9kjby) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L67)):*
> ```cpp
>       {SingleTensorMovement{tensor_shape, {src_mv}, {dst_mv}}}};
>   return estimator.estimate_cost(movement);
> }
> ```

Make these lambdas



_Code quote:_
```cpp
static float
    single_parallel_layer_cost_estimator(parallel_layer_guid_t const &layer,
                                         ParallelComputationGraph const &pcg,
                                         MachineMapping const &machine_mapping,
                                         CostEstimator const &estimator) {
  MachineView mv = machine_mapping.machine_views.at(layer);
  return estimator
      .estimate_cost(get_mapped_op_cost_estimate_key_for_layer(pcg, layer, mv))
      .runtime;
}

static float single_dependency_cost_estimator(
    ParallelComputationGraphEdge const &dependency,
    ParallelComputationGraph const &pcg,
    MachineMapping const &machine_mapping,
    CostEstimator const &estimator) {
  parallel_layer_guid_t incoming = get_src_layer(dependency);
  parallel_layer_guid_t outgoing = get_dst_layer(dependency);
  MachineView src_mv = machine_mapping.machine_views.at(incoming);
  MachineView dst_mv = machine_mapping.machine_views.at(outgoing);
  ParallelTensorShape tensor_shape = get_parallel_tensor_shape(
      pcg, parallel_tensor_guid_t{dependency.raw_edge.src});
  TensorSetMovement movement = TensorSetMovement{
      {SingleTensorMovement{tensor_shape, {src_mv}, {dst_mv}}}};
  return estimator.estimate_cost(movement);
}
```
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH4POTCAJcLonFPlFUY:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
> ```cpp
>       PCGTask task = task_graph.node_map.at_l(n);
>       return task.is_layer() ? std::make_optional(task.require_layer())
>                              : std::nullopt;
> ```





_Suggestion:_
```cpp
      return task.try_require_layer();
```
___
*[`lib/compiler/test/src/compiler/cost_estimator_for_test.cc` line 46 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Pvgd-jFqJ-V1ZNwN:-OH4Pvgd-jFqJ-V1ZNwO:b11yr4z) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/cost_estimator_for_test.cc#L46)):*
> ```cpp
> CostEstimator make_fake_constant_cost_estimator(float op_cost,
>                                                 float comm_cost,
>                                                 size_t memory_cost) {
> ```

Prefer `nonnegative_int`



_Code quote:_
```cpp
size_t
```
___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml` line 21 at r10](https: [...]

2025-01-20 22:28 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 54 of 92 files reviewed, 19 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/compiler/task_graph_simulator/task_graph_execution_trace.cc` line 9 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Pna94DXVfuw5sDVC:-OH4eOMsCKbnhuzxW3SH:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_graph_execution_trace.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also, return maximum - minimum so it matches the expected semantics of the new name
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/deduplicated_priority_queue.h` line 41 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-j68SEhwb9Q8UgscF:-OH4i_SWETs8YYwdgAjp:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/utils/include/utils/deduplicated_priority_queue.h#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's a sorted container of things without duplicates, so probably makes more sense to return a `std::set` using `Compare`?
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/device_mapping.cc` line 24 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-exwE1wlaXZNSlt28:-OH4bvVZAPpPplOXsI-M:b44tpx) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/include/compiler/machine_mapping/device_mapping.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Fair enough. Might be good to add a containers function to handle that at some point (e.g., `map_values_with_key` or something), but this is fine for now
</blockquote></details>

👍
___
*[`lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc` line 68 at r8](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH-c1kj-2H01kDCFd5Y:-OH4cPFq7knz59UlR96d:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/97e8ea52f1d3d85fa23f84cd620039081d5692e3/lib/compiler/src/compiler/cost_estimator/simulate_task_graph_execution.cc#L68)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think having a fixed/predictable order is actually a desirable property, so I don't really have any issue embedding it in execution_tracker
</blockquote></details>

Done.
___
*[`lib/utils/src/utils/containers/func_from_map.cc` line 1 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4QT1LChszeWcmmUJ4:-OH4mam_9SGz6YWUvhOI:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/utils/src/utils/containers/func_from_map.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add a explicit `value_type` specialization to force typechecking
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml` line 21 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4V0dREr5lrme9_LTn:-OH4mp5q09xrQfI4K_yO:b1z3izr) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Feels like it would be better if this was a `TensorSetMovement`. Thoughts?
</blockquote></details>

I think its also a valid choice, but at that point instead of `parallel_layer_guid_t` I would have `OpCostEstimateKey` (given that it's OpCostMetric on which the cost estimator ultimately executes). Depends on whether you want the nodes in the task graph to refer to.
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 67 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4TWQG1DZI8RlmfIkD:-OH4nwrU5L3NIka7nAGy:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Make these lambdas
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/cost_estimator_for_test.cc` line 46 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Pvgd-jFqJ-V1ZNwN:-OH4hWC-9a_o7ZUZ8Oh0:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/cost_estimator_for_test.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `nonnegative_int`
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 39 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Tk-SCzTXVwSkT7YZ:-OH4hsrvD5iOaUJOicM7:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add argument name comments
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 170 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4UbqV-RBLqxDf3ms-:-OH4oPjt6_dc67pRMg2O:b-ulut7p) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L170)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`OpCostMetrics` should probably  be refactored to represent forward pass and backward pass separately if the function name is "estimate_forward_pass_cost_time"
</blockquote></details>

In the sense of having ForwardOpCostMetrics and BackwardOpCost metrics?
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH4f96r9ktEezUvbWLr:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
> ```cpp
>       PCGTask task = task_graph.node_map.at_l(n);
>       return task.is_layer() ? std::make_optional(task.require_layer())
>                              : std::nullopt;
> ```

Done.
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 78 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4Tey82DRF5LCnX6LE:-OH4i7tk4g0zcA_cEraG:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L78)):*
> ```cpp
>       SUBCASE("constant op, comm cost") {
>         CostEstimator estimator = make_fake_constant_cost_estimator(
>             /*op_cost*/ 10.0f, /*comm_cost*/ 1.0f, /*memory_cost*/ 0);
> ```

Done.
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 159 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4ToUy81pt0ymnbKgG:-OH4i8j10NE7XH2GzSc7:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L159)):*
> ```cpp
>         SUBCASE("constant op, comm cost") {
>           CostEstimator estimator = make_fake_constant_cost_estimator(
>               [...]

2025-01-20 22:30 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 54 of 92 files reviewed, 19 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml` line 21 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4V0dREr5lrme9_LTn:-OH4p7lg8SiKm7LR_MiE:bh7f9vu) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml#L21)):*
meant `OpCostEstimateKey`
> OpCostMetric

Basically, if we use TensorSetMovement, the digraph is not a representation of only the PCG, but of PCG + DeviceMapping + MachineSpecification ....


<!-- Sent from Reviewable.io -->

2025-01-20 23:26 UTC, lockshaw requested changes
Can you add unit tests for `get_device_ids` and for 
`std::unordered_set<DataflowEdge> get_outgoing_edges(DataflowGraphView const &g, std::unordered_set<Node> const &ns)`?

> Reviewed 38 of 38 files at r11, 18 of 18 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-:-OH50mwrD-mAdd-HImMp:bhn675t)* status: all files reviewed, 8 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH4z0M28GSMqVkyA-Mb:bbkbjv0) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing this change?
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 170 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4UbqV-RBLqxDf3ms-:-OH4zcse7rn9Yv7oHflJ:bcsz3k2) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L170)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

In the sense of having ForwardOpCostMetrics and BackwardOpCost metrics?
</blockquote></details>

Just change `OpCostMetrics` to have a `forward_execution_time` and a `backward_execution_time`
___
*[`lib/compiler/include/compiler/cost_estimator/tensor_set_movement.h` line 0 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4ybZu1uWMm4gF-FnE:-OH4ybZu1uWMm4gF-FnF:b33ef6z) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/compiler/include/compiler/cost_estimator/tensor_set_movement.h#L0)):*
Empty file?
___
*[`lib/utils/include/utils/deduplicated_priority_queue.h` line 42 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4zrPhAaZdGTcGeksP:-OH4zrPiC1bpJNCggE7d:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/deduplicated_priority_queue.h#L42)):*
> ```objc
>   }
> 
>   std::set<Elem> contents() const {
> ```





_Suggestion:_
```objc
  std::set<Elem, Compare> 
```
___
*[`lib/utils/include/utils/archetypes/value_type.h` line 42 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4zws6AhitvbEkYjlL:-OH4zws6AhitvbEkYjlM:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/archetypes/value_type.h#L42)):*
> ```objc
>   std::ostringstream oss;
>   oss << "<value_type<" << TAG << ">>";
>   return oss.str();
> ```





_Suggestion:_
```objc
  assert(false);
```
___
*[`lib/utils/include/utils/archetypes/value_type.h` line 47 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5--6S-I5PXjPzvIfk:-OH5--6S-I5PXjPzvIfl:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/archetypes/value_type.h#L47)):*
> ```objc
> template <int TAG>
> std::ostream &operator<<(std::ostream &s, value_type<TAG> const &x) {
>   return s << format_as(x);
> ```





_Suggestion:_
```objc
  assert(false);
```
___
*[`lib/utils/test/src/utils/containers/lookup_in_map.cc` line 15 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5-hWD8mHHK3DhICOd:-OH5-hWD8mHHK3DhICOe:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/a439bd8a7ea9dbc57c9424aab4e643a7e760448f/lib/utils/test/src/utils/containers/lookup_in_map.cc#L15)):*
> ```cpp
> 
>     SUBCASE("existing keys") {
>       std::function<int(std::string)> func = lookup_in_map(map);
> ```





_Suggestion:_
```cpp
      std::function<int(std::string const &)>
```


<!-- Sent from Reviewable.io -->

2025-01-20 23:27 UTC, lockshaw commented
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml` line 21 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4V0dREr5lrme9_LTn:-OH51ZPE0tCqr-1LkRYJ:b6yv3rm) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml#L21)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

meant `OpCostEstimateKey`
> OpCostMetric

Basically, if we use TensorSetMovement, the digraph is not a representation of only the PCG, but of PCG + DeviceMapping + MachineSpecification ....
</blockquote></details>

Yes, but I think that's a good idea. The idea of the task graph is to represent the actual computation that occurs, not an abstracted partial version of it, so including the machine mapping information and making the communication explicit is exactly what I'd want.


<!-- Sent from Reviewable.io -->

2025-01-21 02:10 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 60 of 95 files reviewed, 8 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/include/compiler/cost_estimator/tensor_set_movement.h` line  at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4ybZu1uWMm4gF-FnE:-OH5b76bEXSZwXTsPMfj:b-7ql1td) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/compiler/include/compiler/cost_estimator/tensor_set_movement.h#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Empty file?
</blockquote></details>

fixed
___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml` line 21 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4V0dREr5lrme9_LTn:-OH5b8PO6C7-hlUwlP8R:b6983ug) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/include/compiler/task_graph_simulator/pcg_task.variant.toml#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, but I think that's a good idea. The idea of the task graph is to represent the actual computation that occurs, not an abstracted partial version of it, so including the machine mapping information and making the communication explicit is exactly what I'd want.
</blockquote></details>

yeah ur right, done :)
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH5Ek0L8TXih4R_ROMw:b1qkxmt) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing this change?
</blockquote></details>

sorry, forgot to mention that `try_require_layer` does not exist
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 170 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4UbqV-RBLqxDf3ms-:-OH5F4NZ9iL8VsGI26us:bjeicjr) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L170)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just change `OpCostMetrics` to have a `forward_execution_time` and a `backward_execution_time`
</blockquote></details>

`OpCostMetrics`was not made by me, and it's predominantly used within @wmdi 's machine mapping so I don't wanna make changes that break her code, possibly a good topic for next week's meeting?
___
*[`lib/utils/include/utils/archetypes/value_type.h` line 42 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4zws6AhitvbEkYjlL:-OH5FafBB37_fCVDkaDf:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/archetypes/value_type.h#L42)):*
> ```objc
>   std::ostringstream oss;
>   oss << "<value_type<" << TAG << ">>";
>   return oss.str();
> ```

Done.
___
*[`lib/utils/include/utils/archetypes/value_type.h` line 47 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5--6S-I5PXjPzvIfk:-OH5Fb0I712puWqZri4W:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/archetypes/value_type.h#L47)):*
> ```objc
> template <int TAG>
> std::ostream &operator<<(std::ostream &s, value_type<TAG> const &x) {
>   return s << format_as(x);
> ```

Done.
___
*[`lib/utils/include/utils/deduplicated_priority_queue.h` line 42 at r11](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4zrPhAaZdGTcGeksP:-OH5FUaS-yHB74W8yCaT:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/b9e7ae3488f95b2a54dd069b4124d9f2cf8dc34e/lib/utils/include/utils/deduplicated_priority_queue.h#L42)):*
> ```objc
>   }
> 
>   std::set<Elem> contents() const {
> ```

Done.
___
*[`lib/utils/test/src/utils/containers/lookup_in_map.cc` line 15 at r12](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5-hWD8mHHK3DhICOd:-OH5FlNtAiaRBLv1welW:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/a439bd8a7ea9dbc57c9424aab4e643a7e760448f/lib/utils/test/src/utils/containers/lookup_in_map.cc#L15)):*
> ```cpp
> 
>     SUBCASE("existing keys") {
>       std::function<int(std::string)> func = lookup_in_map(map);
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-21 02:29 UTC, lockshaw requested changes
> Reviewed 35 of 35 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH5dO4j1UUaoOhWjPGy:b-36c89e) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

sorry, forgot to mention that `try_require_layer` does not exist
</blockquote></details>

Then `try_require_operator`? afaik it should be generated by `dtgen`
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 170 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4UbqV-RBLqxDf3ms-:-OH5cf7_0tE8VfXdpUXh:baulwiy) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L170)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

`OpCostMetrics`was not made by me, and it's predominantly used within @wmdi 's machine mapping so I don't wanna make changes that break her code, possibly a good topic for next week's meeting?
</blockquote></details>

It's fine to make that change, we've actually been discussing it for a while--iirc `CostEstimator` already provides that information, it's just not currently preserved by `OpCostMetrics` 
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 46 at r13](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5dovA5d6zP6pFVL7n:-OH5dovA5d6zP6pFVL7o:undefined) ([raw file](https://github.com/flexflow/flexflow-train/blob/5cd8ebe0faa2795ffeccabdf757133238933e177/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L46)):*
> ```cpp
>     }
> 
>     auto running_ops = filtrans(in_progress_tasks, [&](Node const &n) {
> ```





_Suggestion:_
```cpp
in_progress_ops
```
___
*[`lib/pcg/include/pcg/operator_task_space.h` line 26 at r13](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5g7ox8hj4vFvlCFIn:-OH5g7ox8hj4vFvlCFIo:b5axyva) ([raw file](https://github.com/flexflow/flexflow-train/blob/5cd8ebe0faa2795ffeccabdf757133238933e177/lib/pcg/include/pcg/operator_task_space.h#L26)):*
> ```objc
>                                        parallel_layer_guid_t const &layer);
> 
> OperatorTaskSpace get_operator_task_space_from_parallel_tensor_shape(
> ```

Don't allow this operation, for now the operator task space should rely on the `parallel_layer_guid_t`. It seems you're using this to get the device set for the task graph--you should instead compute that ahead of time when you have the `parallel_layer_guid_t` and save it in the `PCGTask`s in the `TaskGraph`


<!-- Sent from Reviewable.io -->

2025-01-21 05:02 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/pcg/include/pcg/operator_task_space.h` line 26 at r13](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5g7ox8hj4vFvlCFIn:-OH6E7cH7v1J7HicymnS:bhcnxad) ([raw file](https://github.com/flexflow/flexflow-train/blob/5cd8ebe0faa2795ffeccabdf757133238933e177/lib/pcg/include/pcg/operator_task_space.h#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't allow this operation, for now the operator task space should rely on the `parallel_layer_guid_t`. It seems you're using this to get the device set for the task graph--you should instead compute that ahead of time when you have the `parallel_layer_guid_t` and save it in the `PCGTask`s in the `TaskGraph`
</blockquote></details>

ur right, have added a `node_to_layer` bidict to the PCGTaskGraph (we would technically need a tridict to have perfect "make invalid states unrepresentable", but I think this suffices hahah)
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 104 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4POTCAJcLonFPlFUX:-OH5zkZcEbzeUWSfJZxc:boc1urd) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L104)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Then `try_require_operator`? afaik it should be generated by `dtgen`
</blockquote></details>

sorry, totally missed it.
___
*[`lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc` line 170 at r10](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH4UbqV-RBLqxDf3ms-:-OH5zEG86VBxEbkqqx_q:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/aef3b4f78cea13cb13258b3cf744a5b319961132/lib/compiler/test/src/compiler/task_graph_simulator/task_simulator.cc#L170)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's fine to make that change, we've actually been discussing it for a while--iirc `CostEstimator` already provides that information, it's just not currently preserved by `OpCostMetrics`
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc` line 46 at r13](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH5dovA5d6zP6pFVL7n:-OH5zOhb8HIkHdCJmngI:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/5cd8ebe0faa2795ffeccabdf757133238933e177/lib/compiler/src/compiler/task_graph_simulator/task_simulator.cc#L46)):*
> ```cpp
>     }
> 
>     auto running_ops = filtrans(in_progress_tasks, [&](Node const &n) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-21 05:09 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: 63 of 100 files reviewed, 7 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 245 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6G4ds1PfNi3DJ_tOj:-OH6G4ds1PfNi3DJ_tOk:bqg43hm) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L245)):*
> ```cpp
>     float cost =
>         context.cost_estimator.estimate_cost(mapped)
>             .forward_runtime; // TODO(@pietro)(@wmdi) incorporate backward pass?
> ```

@wmdi 
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc` line 35 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6FfhG099_hj1r6YlH:-OH6FfhG099_hj1r6YlI:bqg43hm) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc#L35)):*
> ```cpp
>       if (mapping.cost.forward_runtime >=
>               other_mapping.cost
>                   .forward_runtime && // TODO(@wmdi) does it have to be modified
> ```

@wmdi 
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc` line 104 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6FloL3tm0gqLblyvA:-OH6FloL3tm0gqLblyvB:bqg43hm) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc#L104)):*
> ```cpp
>             std::max(lhs_mm.cost.forward_runtime, rhs_mm.cost.forward_runtime),
>             std::max(lhs_mm.cost.backward_runtime,
>                      rhs_mm.cost.backward_runtime), //(@wmdi) is this correct?
> ```

@wmdi 


<!-- Sent from Reviewable.io -->

2025-01-21 05:15 UTC, lockshaw requested changes
> Reviewed 37 of 37 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw, @Marsella8, and @wmdi)

___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 245 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6G4ds1PfNi3DJ_tOj:-OH6GO5s6O7F4nLQ-Swv:biamv08) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L245)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

@wmdi
</blockquote></details>

Should should be the sum of the forward and backward runtimes
___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task_graph.struct.toml` line 24 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6HAgS3XfxM-WQDpYB:-OH6HAgS3XfxM-WQDpYC:b-qdvcu) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/include/compiler/task_graph_simulator/pcg_task_graph.struct.toml#L24)):*
> ```TOML
> [[fields]]
> name = "node_to_layer"
> type = "::FlexFlow::bidict<::FlexFlow::Node, ::FlexFlow::parallel_layer_guid_t>"
> ```

I would lean toward making this a `std::unordered_set<DeviceId>` (i.e., pre-compute the device sets and save the result) rather than saving the `parallel_layer_guid_t` directly, especially since this will stop being a `bidict` once you have both forward and backward tasks. Thoughts?


<!-- Sent from Reviewable.io -->

2025-01-21 23:56 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/include/compiler/task_graph_simulator/pcg_task_graph.struct.toml` line 24 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6HAgS3XfxM-WQDpYB:-OHAFYYQ4UHwJaxrJ052:bvb54t5) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/include/compiler/task_graph_simulator/pcg_task_graph.struct.toml#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I would lean toward making this a `std::unordered_set<DeviceId>` (i.e., pre-compute the device sets and save the result) rather than saving the `parallel_layer_guid_t` directly, especially since this will stop being a `bidict` once you have both forward and backward tasks. Thoughts?
</blockquote></details>

makes sense, updated
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 245 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6G4ds1PfNi3DJ_tOj:-OHAGrCz6sLTCX2NrZrX:b-gcw5l5) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L245)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should should be the sum of the forward and backward runtimes
</blockquote></details>

thanks, added, not sure how to update the associated tests accordingly, I've commented them out for now, hopefully @wmdi could fix them?


<!-- Sent from Reviewable.io -->

2025-01-22 00:34 UTC, lockshaw requested changes
> Reviewed 26 of 26 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 245 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6G4ds1PfNi3DJ_tOj:-OHAPzX42Fe0HIfr15a8:br5zr49) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L245)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

thanks, added, not sure how to update the associated tests accordingly, I've commented them out for now, hopefully @wmdi could fix them?
</blockquote></details>

They'll need to be uncommented before this is merged so you may as well keep them uncommented right now (if at least to reduce the diff size for review)


<!-- Sent from Reviewable.io -->

2025-01-23 03:17 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 3 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc` line 35 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6FfhG099_hj1r6YlH:-OHFzmpM0uPtiNruN8vK:bud4f7m) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc#L35)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

@wmdi
</blockquote></details>

I think so. Let's keep this comment for this PR, and I will fix it when I merge it.
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc` line 104 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6FloL3tm0gqLblyvA:-OHG95wO7mk1h9555tWa:b7u03hh) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc#L104)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

@wmdi
</blockquote></details>

Correct


<!-- Sent from Reviewable.io -->

2025-01-23 07:38 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 245 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6G4ds1PfNi3DJ_tOj:-OHH5HCu2Omlqn2qCJk6:b-896fix) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L245)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

They'll need to be uncommented before this is merged so you may as well keep them uncommented right now (if at least to reduce the diff size for review)
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc` line 35 at r14](https://reviewable.io/reviews/flexflow/flexflow-train/1565#-OH6FfhG099_hj1r6YlH:-OHGylSYBOivyDOsbDV1:bavz4zx) ([raw file](https://github.com/flexflow/flexflow-train/blob/4263607e80c200a1a74a46356b0b85bcb95f4667/lib/compiler/src/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_result.cc#L35)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think so. Let's keep this comment for this PR, and I will fix it when I merge it.
</blockquote></details>

great thanks.


<!-- Sent from Reviewable.io -->

2025-01-24 23:25 UTC, lockshaw approved these changes
> Reviewed 18 of 18 files at r16, 25 of 27 files at r17, 19 of 19 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow-train/1565)* status: all files reviewed, 1 unresolved discussion (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2025-01-24 23:55 UTC, merged