add test for the kernel help
flexflow/flexflow-train pull request #992
Opened 2023-08-19 09:36 UTC by lambda7xx

> **Description of changes:**
> 
> * [x]  `accessor.h`
> * [ ]  `allocation.h`
> * [x]  `array_shape.h`
> * [x]  `datatype_dispatch.h`
> * [x]  `legion_dim.h` (and its interaction with `ff_dim_t`)
> * [x]  `perf_metrics.h`
> * [x]  `per_device_op_state.h`
> * [x]  `profiling.h`
> 
> **Related Issues:**
> 
> Linked Issues:
> 
> * Issue [#948](https://github.com/flexflow/FlexFlow/issues/948)
> 
> Issues closed by this PR:
> 
> * Closes #
> 
> **Before merging:**
> 
> * [ ]  Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

2023-10-13 00:37 UTC, lockshaw requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/992)* status: all files reviewed, 19 unresolved discussions (waiting on @lambda7xx and @wmdi)

___
*[`cmake/cuda.cmake` line 86 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2fOy_2vqXqcHSHPvz:-Ne2fOya3uFmC-YTYFRh:bphgc05) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/cmake/cuda.cmake#L86)):*
> ```CMake
>   add_library(cuda INTERFACE)
>   target_include_directories(cuda SYSTEM INTERFACE "${CUDA_INCLUDE_DIRS}")
>   target_link_libraries(cuda INTERFACE
> ```

Why add this?
___
*[`lib/CMakeLists.txt` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eGNI2i79cfH1K2nf:-Ne2eGNI2i79cfH1K2ng:b-ixbmuu) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/CMakeLists.txt#L0)):*
This file should never be modified in PRs
___
*[`lib/kernels/include/kernels/array_shape.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eQ_PEGWFDhO9c-Hb:-Ne2eQ_PEGWFDhO9c-Hc:bqow2wa) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/include/kernels/array_shape.h#L41)):*
> ```objc
>   optional<std::size_t> at_maybe(std::size_t) const;
> 
>   bool operator==(ArrayShape const &other) const; // for test case
> ```

This already exists via `visitable`
___
*[`lib/kernels/include/kernels/profiling.h` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eXh60tNMw_wNjmKC:-Ne2eXh60tNMw_wNjmKD:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/include/kernels/profiling.h#L18)):*
> ```objc
>   int warmup_iters;
>   int measure_iters;
> };
> ```





_Suggestion:_
```objc
struct ProfilingSettings {
  int warmup_iters;
  req<int> measure_iters;
};
```
___
*[`lib/kernels/src/array_shape.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaR-3xDeLC6bKzquEL:-NgaR-3xDeLC6bKzquEM:bi1tp0x) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L10)):*
> ```cpp
> 
> std::size_t ArrayShape::get_volume() const {
>   return num_elements();
> ```

Use `this->` whenever possible--it makes code much clearer as the reader knows it's a method and not a function call (same for data members)
___
*[`lib/kernels/src/array_shape.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRFmn3b2Z9CRGiz4P:-NgaRFmn3b2Z9CRGiz4Q:b-ewgol2) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L51)):*
> ```cpp
> 
> ArrayShape ArrayShape::reversed_dim_order() const {
>   std::vector<std::size_t> dims_reversed(dims.rbegin(), dims.rend());
> ```

Do we have a function for this in containers?
___
*[`lib/kernels/src/array_shape.cc` line 63 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRQr_8Yn9gsFezE9h:-NgaRQr_8Yn9gsFezE9i:b-3tbr0l) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L63)):*
> ```cpp
> }
> 
> bool ArrayShape::operator==(ArrayShape const &other) const {
> ```

If array shape is visitable this should be removed
___
*[`lib/kernels/test/CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eiAH0vZ4Idu_luMm:-Ne2eiAH0vZ4Idu_luMn:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/CMakeLists.txt#L18)):*
> ```CMake
>   cuda
>   rapidcheck
>   doctest::doctest)
> ```





_Suggestion:_
```CMake
target_link_libraries(
  ${project_target}
  kernels
  cuda
  rapidcheck
  doctest)
```
___
*[`lib/kernels/test/src/test_array_shape.cc` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRu3XC-ZQn-Jk2b67:-NgaRu3XC-ZQn-Jk2b68:b-kl65hq) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_array_shape.cc#L15)):*
> ```cpp
>   CHECK(shape.num_dims() == 3);
>   CHECK(shape[legion_dim_t(1)] == 3);
>   CHECK(shape.at(legion_dim_t(2)) == 4);
> ```

Add checks for accessing via `ff_dim_t` too
___
*[`lib/kernels/test/src/test_datatype_dispatch.cc` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2f7ZREIJbRqmrrDee:-Ne2f7ZS5WC0BA3kwr8S:btaekb9) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_datatype_dispatch.cc#L23)):*
> ```cpp
>   int result = dispatch<Function1>(DataType::FLOAT, value);
>   CHECK(result == 11);
> }
> ```

Should also test the `DOUBLE` case



_Code quote:_
```cpp
TEST_CASE("Testing dispatch function") {
  int value = 10;
  int result = dispatch<Function1>(DataType::FLOAT, value);
  CHECK(result == 11);
}
```
___
*[`lib/kernels/test/src/test_datatype_dispatch.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2f5Mm9ERKRfjBCDq5:-Ne2f5Mm9ERKRfjBCDq6:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_datatype_dispatch.cc#L25)):*
> ```cpp
> }
> 
> // test DataTypeDispatch1
> ```


___
*[`lib/kernels/test/src/test_legion_dim.cc` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaS6dw0dy4XOERe4kY:-NgaS6dw0dy4XOERe4kZ:b-mta4wd) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L17)):*
> ```cpp
>   SUBCASE("at") {
>     DimOrdered<legion_dim_t, int> dimOrder = {1, 2, 3};
>     CHECK(dimOrder[legion_dim_t(0)] == 1);
> ```

Check accessing via `ff_dim_t`
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSJsR-d6N1KjCMH-K:-NgaSJsR-d6N1KjCMH-L:bl1n413) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L43)):*
> ```cpp
> TEST_CASE("Testing LegionTensorDims") {
> 
>   SUBCASE("LegionTensorDims Basic Operation") {
> ```

check `ff_dim_t` accesses too
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 46 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSDoi24siRTrr-2D9:-NgaSDoi24siRTrr-2DA:b-rtagwg) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L46)):*
> ```cpp
>     LegionTensorDims tensorDims = {100, 200};
> 
>     // tensorDims[legion_dim_t(1)] = 100;
> ```

delete
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSEgaAtNBMGrOLgB-:-NgaSEgaAtNBMGrOLgB0:b-rtagwg) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L49)):*
> ```cpp
>     CHECK(tensorDims[legion_dim_t(0)] == 100);
> 
>     //  tensorDims[legion_dim_t(2)] = 200;
> ```

delete
___
*[`lib/kernels/test/src/test_perf_metrics.cc` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSQv8EhLcqsiDkfUe:-NgaSQv8EhLcqsiDkfUf:b-s3u4vp) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_perf_metrics.cc#L7)):*
> ```cpp
> using namespace FlexFlow;
> 
> // Helper function to generate random values for PerfMetrics
> ```

Use rapidcheck for this
___
*[`lib/kernels/test/src/test_perf_metrics.cc` line 47 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSTf5BxmxeLABViN-:-NgaSTf5BxmxeLABViN0:b2ggvn4) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_perf_metrics.cc#L47)):*
> ```cpp
>     auto result = update(lhs, rhs);
>     CHECK(result.train_all >= 0);
>     // Add  [...]

2024-03-20 06:54 UTC, lambda7xx commented
*[`cmake/cuda.cmake` line 86 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2fOy_2vqXqcHSHPvz:-NtPctaT7UnaRgkMHZe9:b-ugvzii) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/cmake/cuda.cmake#L86)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why add this?
</blockquote></details>

i will remove


<!-- Sent from Reviewable.io -->

2024-03-20 06:54 UTC, lambda7xx commented
*[`lib/CMakeLists.txt` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eGNI2i79cfH1K2nf:-NtPcwDEAbYGbiI4V9Dh:b32wtd) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/CMakeLists.txt#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This file should never be modified in PRs
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2024-03-20 07:02 UTC, lambda7xx commented
*[`lib/kernels/src/array_shape.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRFmn3b2Z9CRGiz4P:-NtPeogZAEhFfIuWdOlg:biqc8w4) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Do we have a function for this in containers?
</blockquote></details>

yes, we have


<!-- Sent from Reviewable.io -->

2024-03-20 07:06 UTC, lambda7xx commented
*[`lib/kernels/test/src/test_legion_dim.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSEgaAtNBMGrOLgB-:-NtPfirw6uFa14KIXZgd:bfo10da) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

delete
</blockquote></details>

what need delete


<!-- Sent from Reviewable.io -->

2024-03-20 07:09 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/992)* status: 13 of 17 files reviewed, 19 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/array_shape.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eQ_PEGWFDhO9c-Hb:-NtPe2g8BMfpiv5rUAS2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/include/kernels/array_shape.h#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This already exists via `visitable`
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/profiling.h` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eXh60tNMw_wNjmKC:-NtPeOb_AlBum3jAAfiW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/include/kernels/profiling.h#L18)):*
> ```objc
>   int warmup_iters;
>   int measure_iters;
> };
> ```

Done.
___
*[`lib/kernels/src/array_shape.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaR-3xDeLC6bKzquEL:-NtPeggl2LKWsr2AByeU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `this->` whenever possible--it makes code much clearer as the reader knows it's a method and not a function call (same for data members)
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 63 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRQr_8Yn9gsFezE9h:-NtPevg05NtpKApYPDH7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If array shape is visitable this should be removed
</blockquote></details>

Done.
___
*[`lib/kernels/test/CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eiAH0vZ4Idu_luMm:-NtPf1cC4rEbU74znl4j:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/CMakeLists.txt#L18)):*
> ```CMake
>   cuda
>   rapidcheck
>   doctest::doctest)
> ```

Done.
___
*[`lib/kernels/test/src/test_array_shape.cc` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRu3XC-ZQn-Jk2b67:-NtPfB4V2oVjo-qK2x6C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_array_shape.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add checks for accessing via `ff_dim_t` too
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_datatype_dispatch.cc` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2f7ZREIJbRqmrrDee:-NtPfhDNA0U00xKNk2l8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_datatype_dispatch.cc#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should also test the `DOUBLE` case
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_datatype_dispatch.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2f5Mm9ERKRfjBCDq5:-NtPfSTV4-B5lgW67VxY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_datatype_dispatch.cc#L25)):*
> ```cpp
> }
> 
> // test DataTypeDispatch1
> ```

Done.
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaS6dw0dy4XOERe4kY:-NtPfi2i7qVobMz7crUl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Check accessing via `ff_dim_t`
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSJsR-d6N1KjCMH-K:-NtPf_TQ4gVePkwR_EJs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

check `ff_dim_t` accesses too
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_profiling.cc` line 6 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSc2pClJ_Jt9trAkX:-NtPgEHTCJF0LyHb5gSF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_profiling.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are there two tests for `PerfMetrics`? I think one should be deleted?
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/dim_ordered.h` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2fKLmCfEuSu1pvuTr:-NtPgN8rB6KGKUX7s8J3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/op-attrs/include/op-attrs/dim_ordered.h#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove, this is defined by the user via a cmake option
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 21:12 UTC, lockshaw requested changes
Since this is related to #1305 let's have @reyna-abhyankar take over and merge it as part of that PR 

> Reviewed 2 of 3 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/992#-:-Nu5tco88k4wHtl-v321:bgg42il)* status: all files reviewed, 19 unresolved discussions (waiting on @lambda7xx)

___
*[`deps/any` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3Dy6p9mrCGIzwHOv5:-Nu3Dy6p9mrCGIzwHOv6:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/any#L1)):*
> ```
> Subproject commit e88b1bfc160fa9b01e6174dd29c812eeeece3be9
> ```

Remove
___
*[`deps/googletest` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3E-jz1pVtJGy3Va4Y:-Nu3E-jz1pVtJGy3Va4Z:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/googletest#L1)):*
> ```
> Subproject commit 2fe3bd994b3189899d93f1d5a881e725e046fdc2
> ```

Remove
___
*[`deps/invoke` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3E0v_-MYtQOnIzblw:-Nu3E0v_-MYtQOnIzblx:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/invoke#L1)):*
> ```
> Subproject commit 2c1eabc2e20ab02961f95c704ff0c0818671ddd1
> ```

Remove
___
*[`deps/optional` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3E1fyCJISzp5ycaFy:-Nu3E1fyCJISzp5ycaFz:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/optional#L1)):*
> ```
> Subproject commit c28fcf74d207fc667c4ed3dbae4c251ea551c8c1
> ```

Remove
___
*[`deps/pybind11` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3E2ZR2z_15tu2nvNC:-Nu3E2ZR2z_15tu2nvND:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/pybind11#L1)):*
> ```
> Subproject commit 8de7772cc72daca8e947b79b83fea46214931604
> ```

Remove
___
*[`deps/variant` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3E3InEVsj6pmqm4lY:-Nu3E3InEVsj6pmqm4lZ:byp18fd) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/deps/variant#L1)):*
> ```
> Subproject commit 23cb94f027d4ef33bf48133acc2695c7e5c6f1e7
> ```

Remove
___
*[`lib/kernels/include/kernels/profiling.h` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eXh60tNMw_wNjmKC:-Nu3E6cs6omC6O21jyTI:bkwvvuj) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/include/kernels/profiling.h#L18)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The rest of the diff that was removed should be done too
___
*[`lib/kernels/src/array_shape.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRFmn3b2Z9CRGiz4P:-Nu3EHcOEP6jWjYQHXgZ:b7l0bat) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/src/array_shape.cc#L51)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

yes, we have
</blockquote></details>

Then let's use it here
___
*[`lib/kernels/test/CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Ne2eiAH0vZ4Idu_luMm:-Nu3ESpqEWptvGZ_VlSO:b-j3vzhg) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/CMakeLists.txt#L18)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You added a typo--should be "doctest", not "octest"
___
*[`lib/kernels/test/src/test_array_shape.cc` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaRu3XC-ZQn-Jk2b67:-Nu3EZoTBpTrmawh5sWb:b-n445dn) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_array_shape.cc#L15)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If they're both `== 4` this isn't a particularly good check as it would pass either way
___
*[`lib/kernels/test/src/test_datatype_dispatch.cc` line 40 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3Ej9vA3FRme5EJHsp:-Nu3Ej9vA3FRme5EJHsq:blk4fi8) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/lib/kernels/test/src/test_datatype_dispatch.cc#L40)):*
> ```cpp
> 
> 
> TEST_CASE("Testing DataTypeDispatch1 Double") {
> ```

This whole file (and all the other test files) should be wrapped in a `TEST_SUITE(FF_TEST_SUITE) { ... }`
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaS6dw0dy4XOERe4kY:-Nu3EwZP4NECMB5Q9ssJ:b-e7j2zc) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L17)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This isn't correct and won't pass--`ff_dim_t` and `legion_dim_t` should be flipped
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSJsR-d6N1KjCMH-K:-Nu3F52x74VXfdJGE14t:b-eauhg6) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L43)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing it
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 46 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSDoi24siRTrr-2D9:-Nu3F1yx6XQhqITSbeds:b-xxjuz9) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L46)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

what need delete
</blockquote></details>

The comment
___
*[`lib/kernels/test/src/test_legion_dim.cc` line 49 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/992#-NgaSEgaAtNBMGrOLgB-:-Nu3F1H14fBolkXvNQC3:b-xxjuz9) ([raw file](https://github.com/flexflow/FlexFlow/blob/22a9781ad51d7f447b52c0fd1d2f9623b336ecd6/lib/kernels/test/src/test_legion_dim.cc#L49)):*
<details><summary><i>Previously, lambda7xx (Lambda Shi ) wrote…</i></summary><blockquote>

what need delete
</blockquote></details>

The comment
___
*[`lib/kernels/test/src/test_perf_metrics.cc` line 79 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3FG7269eWxxDjwKHc:-Nu3FG7269eWxxDjwKHd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/lib/kernels/test/src/test_perf_metrics.cc#L79)):*
> ```cpp
>     PerfMetrics rhs(5, 3, 0.2, 0.2, 0.2, 0.2, 0.2, 200.0, 300.0);
> 
>     auto result = update(lhs, rhs);
> ```





_Suggestion:_
```cpp
    PerfMetrics result = update(lhs, rhs);
```
___
*[`lib/kernels/include/kernels/array_shape.h` line 38 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/992#-Nu3FRA34oSDoTO8i65_:-Nu3FRA34oSDoTO8i65a:bykb71k) ([raw file](https://github.com/flexflow/FlexFlow/blob/b2d6bfa593d9c7a7f3a80c3de0e787d1ec9b2f59/lib/kernels/include/kernels/array_shape.h#L38)):*
> ```objc
>   legion_dim_t neg_idx(int) const;
> 
>   std::optional<std::size_t> at_maybe(std::size_t) const;
> ```

This method should probably be removed as it's using a raw `std::size_t` rather than `legion_dim_t` or `ff_dim_t`


<!-- Sent from Reviewable.io -->

2025-02-25 04:00 UTC, oOTigger commented
Kept track of now in #1599

2025-02-25 04:00 UTC, closed without merging